// Continuação dos dados da trilha - Fases 3 e 4 (Dias 15-30)

export const dadosFase3e4 = {
  // ========== FASE 3 - Dias 15 a 21 ==========
  dia15: {
    exercicios: [
      {
        id: 'agach-alinhado-d15',
        nome: 'Agachamento com joelho alinhado',
        objetivo: 'Corrigir mecânica de movimento',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 40 graus mantendo joelhos alinhados com os pés.',
          'Use um espelho para verificar.',
          'Suba devagar.',
          '12 repetições.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'Imagine que está empurrando o chão para os lados.',
        pernas: false,
      },
      {
        id: 'ponte-gluteos-d15',
        nome: 'Ponte com foco em glúteos',
        objetivo: 'Maximizar ativação dos glúteos',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve o quadril.',
          'Aperte os glúteos com força no topo.',
          'Segure 5 segundos.',
          '12 repetições.',
        ],
        sensacao: 'queimação intensa nos glúteos.',
        evitar: 'dor lombar.',
        dica: 'Pense em "apertar uma moeda entre os glúteos".',
        pernas: false,
      },
      {
        id: 'mob-tornozelo-d15',
        nome: 'Mobilidade de tornozelo',
        objetivo: 'Manter amplitude de movimento',
        duracao: '4 min',
        instrucoes: [
          'Em pé, coloque um pé à frente.',
          'Leve o joelho para frente sem o calcanhar sair do chão.',
          '15 repetições por perna.',
          'Faça 2 séries.',
        ],
        sensacao: 'alongamento na panturrilha.',
        evitar: 'tirar o calcanhar do chão.',
        dica: 'Tornozelo móvel = agachamento melhor.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Alinhamento do joelho',
      conteudo: [
        'O alinhamento correto do joelho é fundamental:',
        '✅ Joelho deve seguir a linha do pé',
        '✅ Não deve cair para dentro',
        '✅ Não deve ultrapassar muito a ponta do pé',
        'Como corrigir:',
        '• Fortaleça glúteo médio',
        '• Ative glúteos durante movimentos',
        '• Use espelho para feedback visual',
        'Alinhamento correto = sem dor!',
      ],
    },
  },

  dia16: {
    exercicios: [
      {
        id: 'step-lateral-d16',
        nome: 'Step lateral suave',
        objetivo: 'Fortalecer glúteo médio funcionalmente',
        duracao: '5 min',
        instrucoes: [
          'Use um degrau baixo.',
          'Suba lateralmente com uma perna.',
          'Desça devagar.',
          '10 repetições por perna.',
        ],
        sensacao: 'ativação na lateral do quadril e perna.',
        evitar: 'perder o equilíbrio.',
        dica: 'Movimento lateral desafia o glúteo médio.',
        pernas: true,
      },
      {
        id: 'gluteo-faixa-d16',
        nome: 'Glúteo médio com faixa',
        objetivo: 'Aumentar resistência',
        duracao: '5 min',
        instrucoes: [
          'Coloque uma faixa elástica acima dos joelhos.',
          'Em pé, eleve a perna lateralmente contra a resistência.',
          '12 repetições por perna.',
        ],
        sensacao: 'queimação forte na lateral do quadril.',
        evitar: 'inclinar o tronco.',
        dica: 'A faixa aumenta muito o desafio.',
        pernas: true,
      },
      {
        id: 'along-quadriceps-d16',
        nome: 'Alongamento quadríceps',
        objetivo: 'Relaxar musculatura anterior',
        duracao: '4 min',
        instrucoes: [
          'Em pé, segure o pé atrás do corpo.',
          'Traga o calcanhar em direção ao glúteo.',
          'Segure 30 segundos por perna.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento na frente da coxa.',
        evitar: 'dor no joelho.',
        dica: 'Use uma parede para apoio.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Importância do glúteo médio',
      conteudo: [
        'O glúteo médio é o músculo mais importante para proteger seu joelho:',
        '✅ Estabiliza o quadril',
        '✅ Evita que o joelho caia para dentro',
        '✅ Reduz pressão na patela',
        '✅ Melhora equilíbrio',
        'Quando está fraco:',
        '❌ Joelho sofre mais',
        '❌ Dor aumenta',
        '❌ Risco de lesões',
        'Continue fortalecendo!',
      ],
    },
  },

  dia17: {
    exercicios: [
      {
        id: 'agach-iso-10s-d17',
        nome: 'Agachamento isométrico 10s',
        objetivo: 'Aumentar resistência muscular',
        duracao: '5 min',
        instrucoes: [
          'Encoste na parede.',
          'Desça 30–40 graus.',
          'Segure 10 segundos.',
          'Descanse 5 segundos.',
          '8 repetições.',
        ],
        sensacao: 'queimação intensa nas pernas.',
        evitar: 'descer muito ou sentir dor no joelho.',
        dica: 'Respire normalmente durante a contração.',
        pernas: false,
      },
      {
        id: 'elevacao-perna-d17',
        nome: 'Elevação de perna estendida',
        objetivo: 'Fortalecer quadríceps sem dobrar joelho',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de costas.',
          'Mantenha uma perna estendida.',
          'Eleve a perna 30 cm do chão.',
          'Segure 3 segundos.',
          '12 repetições por perna.',
        ],
        sensacao: 'ativação forte no quadríceps.',
        evitar: 'arquear a lombar.',
        dica: 'Mantenha a lombar colada no chão.',
        pernas: true,
      },
      {
        id: 'mob-quadril-d17',
        nome: 'Mobilidade quadril',
        objetivo: 'Melhorar amplitude de movimento',
        duracao: '4 min',
        instrucoes: [
          'Em pé, segure em uma parede.',
          'Faça círculos com o joelho.',
          '10 para cada lado.',
          'Repita com a outra perna.',
        ],
        sensacao: 'movimento livre do quadril.',
        evitar: 'movimentos bruscos.',
        dica: 'Quadril móvel = joelho protegido.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Posições seguras para o joelho',
      conteudo: [
        'Algumas posições são mais seguras para o joelho:',
        '✅ Agachamento raso (30–50 graus)',
        '✅ Joelho alinhado com o pé',
        '✅ Peso distribuído em toda a planta do pé',
        '✅ Movimentos controlados',
        '❌ Evite:',
        '• Agachamento muito profundo sem preparo',
        '• Joelhos caindo para dentro',
        '• Movimentos bruscos',
        'Pratique posições seguras!',
      ],
    },
  },

  dia18: {
    exercicios: [
      {
        id: 'agach-parcial-pausa-d18',
        nome: 'Agachamento parcial + pausa',
        objetivo: 'Aumentar controle e força',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 40 graus.',
          'Pause por 5 segundos.',
          'Suba devagar.',
          '10 repetições.',
        ],
        sensacao: 'queimação intensa nas pernas.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'A pausa aumenta muito o desafio.',
        pernas: false,
      },
      {
        id: 'ponte-unilateral-d18',
        nome: 'Ponte unilateral',
        objetivo: 'Fortalecer glúteos unilateralmente',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de costas.',
          'Estenda uma perna.',
          'Eleve o quadril.',
          'Segure 3 segundos.',
          '12 repetições por perna.',
        ],
        sensacao: 'queimação forte no glúteo.',
        evitar: 'dor lombar.',
        dica: 'Mantenha o quadril nivelado.',
        pernas: true,
      },
      {
        id: 'along-posterior-d18',
        nome: 'Alongamento posterior',
        objetivo: 'Manter flexibilidade',
        duracao: '4 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve uma perna estendida.',
          'Segure atrás da coxa.',
          'Mantenha 30 segundos.',
          'Repita 2 vezes por perna.',
        ],
        sensacao: 'alongamento suave atrás da coxa.',
        evitar: 'forçar demais.',
        dica: 'Respire profundamente.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Movimentos que aliviam dor',
      conteudo: [
        'Alguns movimentos ajudam a aliviar a dor:',
        '✅ Mobilidade suave do joelho',
        '✅ Alongamentos leves',
        '✅ Ativação de glúteos',
        '✅ Caminhada leve',
        '✅ Gelo após atividades',
        '❌ Evite quando estiver com dor:',
        '• Corrida',
        '• Pular',
        '• Agachamento profundo',
        'Ouça seu corpo!',
      ],
    },
  },

  dia19: {
    exercicios: [
      {
        id: 'step-alto-d19',
        nome: 'Step alto controlado',
        objetivo: 'Aumentar desafio funcional',
        duracao: '5 min',
        instrucoes: [
          'Use um degrau de 20–25 cm.',
          'Suba com controle.',
          'Desça devagar.',
          '10 repetições por perna.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'perder o equilíbrio ou descer rápido.',
        dica: 'Controle a descida - é onde o joelho mais trabalha.',
        pernas: true,
      },
      {
        id: 'gluteo-rep-lenta-d19',
        nome: 'Glúteo médio com repetição lenta',
        objetivo: 'Aumentar tempo sob tensão',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de lado.',
          'Eleve a perna em 3 segundos.',
          'Desça em 3 segundos.',
          '10 repetições por perna.',
        ],
        sensacao: 'queimação intensa na lateral do quadril.',
        evitar: 'movimentos rápidos.',
        dica: 'Lento = mais efetivo.',
        pernas: true,
      },
      {
        id: 'panturrilha-d19',
        nome: 'Panturrilha',
        objetivo: 'Fortalecer panturrilha',
        duracao: '4 min',
        instrucoes: [
          'Em pé, suba na ponta dos pés.',
          'Segure 3 segundos no topo.',
          'Desça devagar.',
          '15 repetições.',
          'Faça 2 séries.',
        ],
        sensacao: 'queimação na panturrilha.',
        evitar: 'perder o equilíbrio.',
        dica: 'Panturrilha forte ajuda na estabilidade.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Importância da panturrilha',
      conteudo: [
        'A panturrilha é essencial para o joelho:',
        '✅ Ajuda na absorção de impacto',
        '✅ Melhora equilíbrio',
        '✅ Estabiliza o tornozelo',
        '✅ Reduz sobrecarga no joelho',
        'Quando está fraca:',
        '❌ Tornozelo fica instável',
        '❌ Joelho compensa',
        '❌ Dor aumenta',
        'Continue fortalecendo!',
      ],
    },
  },

  dia20: {
    exercicios: [
      {
        id: 'agach-medio-d20',
        nome: 'Agachamento médio (40–50º) se sem dor',
        objetivo: 'Progredir amplitude com segurança',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 40–50 graus (se sem dor).',
          'Mantenha joelhos alinhados.',
          'Suba devagar.',
          '10 repetições.',
        ],
        sensacao: 'ativação forte em toda a perna.',
        evitar: 'dor no joelho ou joelhos caindo para dentro.',
        dica: 'Se sentir dor, volte para 30–40 graus.',
        pernas: false,
      },
      {
        id: 'mob-ativa-d20',
        nome: 'Mobilidade ativa',
        objetivo: 'Mobilizar com ativação muscular',
        duracao: '5 min',
        instrucoes: [
          'Rotação de tornozelo ativa (10 vezes cada).',
          'Elevação de joelho (10 vezes cada).',
          'Círculos de quadril (10 vezes cada).',
        ],
        sensacao: 'corpo aquecido e solto.',
        evitar: 'movimentos bruscos.',
        dica: 'Mobilidade ativa prepara o corpo para movimento.',
        pernas: false,
      },
      {
        id: 'quadriceps-leve-d20',
        nome: 'Quadríceps leve',
        objetivo: 'Manter ativação',
        duracao: '4 min',
        instrucoes: [
          'Sente-se com as costas apoiadas.',
          'Estenda uma perna.',
          'Contraia o quadríceps por 5 segundos.',
          '10 repetições por perna.',
        ],
        sensacao: 'ativação leve no quadríceps.',
        evitar: 'dor no joelho.',
        dica: 'Mantenha a ativação constante.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Entenda sua evolução',
      conteudo: [
        'Você já evoluiu muito! Compare:',
        '🔵 Início:',
        '• Dor frequente',
        '• Movimentos limitados',
        '• Joelho fraco',
        '🟢 Agora:',
        '• Menos dor',
        '• Mais amplitude',
        '• Joelho mais forte',
        'Continue praticando - você está quase lá!',
      ],
    },
  },

  dia21: {
    exercicios: [
      {
        id: 'mob-geral-d21',
        nome: 'Mobilidade geral',
        objetivo: 'Mobilizar todo o corpo',
        duracao: '5 min',
        instrucoes: [
          'Rotação de tornozelo.',
          'Mobilidade de joelho.',
          'Mobilidade de quadril.',
          'Mobilidade de coluna.',
          '10 repetições de cada.',
        ],
        sensacao: 'corpo solto e preparado.',
        evitar: 'movimentos bruscos.',
        dica: 'Faça com calma e atenção.',
        pernas: false,
      },
      {
        id: 'agach-leve-d21',
        nome: 'Agachamento leve',
        objetivo: 'Integrar movimento',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 30–40 graus.',
          'Suba devagar.',
          '12 repetições.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'Foque na qualidade.',
        pernas: false,
      },
      {
        id: 'along-completo-d21',
        nome: 'Alongamento completo',
        objetivo: 'Relaxar todo o corpo',
        duracao: '4 min',
        instrucoes: [
          'Alongamento posterior (30s cada).',
          'Alongamento de quadríceps (30s cada).',
          'Alongamento de glúteo (30s cada).',
          'Alongamento de panturrilha (30s cada).',
        ],
        sensacao: 'relaxamento completo.',
        evitar: 'forçar demais.',
        dica: 'Finalize a fase 3 com gratidão.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Semana 3 — o que mudou no seu joelho?',
      conteudo: [
        'Parabéns por completar a Fase 3! 🎉',
        'Mudanças que você deve notar:',
        '✅ Movimentos mais suaves',
        '✅ Menos dor no dia a dia',
        '✅ Mais confiança',
        '✅ Melhor alinhamento',
        'Na próxima fase, vamos retornar às atividades do dia a dia com segurança.',
        'Você está incrível!',
      ],
    },
  },

  // ========== FASE 4 - Dias 22 a 30 ==========
  dia22: {
    exercicios: [
      {
        id: 'agach-controlado-d22',
        nome: 'Agachamento controlado',
        objetivo: 'Fortalecer com amplitude funcional',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 40–50 graus com controle.',
          'Pause 2 segundos.',
          'Suba devagar.',
          '12 repetições.',
        ],
        sensacao: 'ativação forte em toda a perna.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'Você está pronto para mais amplitude.',
        pernas: false,
      },
      {
        id: 'step-alternado-d22',
        nome: 'Step alternado',
        objetivo: 'Simular subir escadas',
        duracao: '5 min',
        instrucoes: [
          'Use um degrau de 20 cm.',
          'Suba alternando as pernas.',
          'Desça com controle.',
          '10 repetições por perna.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'perder o equilíbrio.',
        dica: 'Você está preparando o joelho para escadas.',
        pernas: true,
      },
      {
        id: 'along-posterior-d22',
        nome: 'Alongamento posterior',
        objetivo: 'Manter flexibilidade',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve uma perna estendida.',
          'Segure 30 segundos.',
          'Repita 2 vezes por perna.',
        ],
        sensacao: 'alongamento suave.',
        evitar: 'forçar demais.',
        dica: 'Mantenha a flexibilidade.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Joelho forte no dia a dia',
      conteudo: [
        'Agora você está pronto para usar seu joelho no dia a dia:',
        '✅ Subir escadas',
        '✅ Agachar para pegar objetos',
        '✅ Caminhar longas distâncias',
        '✅ Ficar em pé por mais tempo',
        'Dicas para manter o joelho saudável:',
        '• Continue praticando exercícios 3x por semana',
        '• Mantenha peso saudável',
        '• Use calçados confortáveis',
        'Você está no caminho certo!',
      ],
    },
  },

  dia23: {
    exercicios: [
      {
        id: 'ponte-avancada-d23',
        nome: 'Ponte avançada',
        objetivo: 'Maximizar força dos glúteos',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve o quadril.',
          'Segure 8 segundos no topo.',
          'Desça devagar.',
          '10 repetições.',
        ],
        sensacao: 'queimação intensa nos glúteos.',
        evitar: 'dor lombar.',
        dica: 'Aperte os glúteos com força máxima.',
        pernas: false,
      },
      {
        id: 'gluteo-pe-faixa-d23',
        nome: 'Glúteo médio em pé com faixa',
        objetivo: 'Fortalecer com resistência',
        duracao: '5 min',
        instrucoes: [
          'Coloque faixa acima dos joelhos.',
          'Em pé, eleve a perna lateralmente.',
          '12 repetições por perna.',
        ],
        sensacao: 'queimação forte na lateral do quadril.',
        evitar: 'inclinar o tronco.',
        dica: 'A faixa aumenta muito o desafio.',
        pernas: true,
      },
      {
        id: 'mob-tornozelo-d23',
        nome: 'Mobilidade tornozelo',
        objetivo: 'Manter amplitude',
        duracao: '5 min',
        instrucoes: [
          'Em pé, coloque um pé à frente.',
          'Leve o joelho para frente.',
          '15 repetições por perna.',
          'Faça 2 séries.',
        ],
        sensacao: 'alongamento na panturrilha.',
        evitar: 'tirar o calcanhar do chão.',
        dica: 'Mantenha a mobilidade.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Transferindo força para movimento',
      conteudo: [
        'Você está forte! Agora vamos usar essa força no dia a dia:',
        '✅ Ao subir escadas: use a força dos glúteos',
        '✅ Ao agachar: mantenha joelhos alinhados',
        '✅ Ao caminhar: ative o core',
        '✅ Ao levantar: use as pernas, não as costas',
        'Força sem função = desperdício',
        'Função com força = joelho saudável',
        'Pratique movimentos funcionais!',
      ],
    },
  },

  dia24: {
    exercicios: [
      {
        id: 'agach-funcional-d24',
        nome: 'Agachamento funcional',
        objetivo: 'Simular movimentos do dia a dia',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça como se fosse pegar algo do chão.',
          'Mantenha joelhos alinhados.',
          'Suba devagar.',
          '12 repetições.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'Pratique o movimento que você faz no dia a dia.',
        pernas: false,
      },
      {
        id: 'elevacao-perna-d24',
        nome: 'Elevação de perna estendida',
        objetivo: 'Manter força do quadríceps',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve uma perna estendida.',
          'Segure 5 segundos.',
          '12 repetições por perna.',
        ],
        sensacao: 'ativação forte no quadríceps.',
        evitar: 'arquear a lombar.',
        dica: 'Mantenha a lombar colada no chão.',
        pernas: true,
      },
      {
        id: 'along-quadril-d24',
        nome: 'Alongamento de quadril',
        objetivo: 'Manter flexibilidade',
        duracao: '5 min',
        instrucoes: [
          'Em pé, coloque uma perna à frente.',
          'Incline o quadril.',
          'Segure 30 segundos por perna.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento na frente do quadril.',
        evitar: 'arquear demais a lombar.',
        dica: 'Quadril flexível = joelho protegido.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'O que é um movimento seguro?',
      conteudo: [
        'Movimento seguro tem 3 características:',
        '✅ 1. Alinhamento correto',
        '• Joelho alinhado com o pé',
        '• Quadril estável',
        '✅ 2. Controle',
        '• Movimentos lentos e controlados',
        '• Sem compensações',
        '✅ 3. Força adequada',
        '• Músculos ativados',
        '• Sem sobrecarga',
        'Pratique movimentos seguros sempre!',
      ],
    },
  },

  dia25: {
    exercicios: [
      {
        id: 'subir-descer-escada-d25',
        nome: 'Subir e descer escada',
        objetivo: 'Retornar à função de escadas',
        duracao: '5 min',
        instrucoes: [
          'Use uma escada real ou degrau alto.',
          'Suba com controle.',
          'Desça devagar (mais importante).',
          '10 repetições por perna.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'descer rápido.',
        dica: 'Você está pronto para escadas!',
        pernas: true,
      },
      {
        id: 'agach-parcial-pausa-d25',
        nome: 'Agachamento parcial com pausa',
        objetivo: 'Manter força e controle',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 40–50 graus.',
          'Pause 5 segundos.',
          'Suba devagar.',
          '10 repetições.',
        ],
        sensacao: 'queimação nas pernas.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'Mantenha a pausa para máximo benefício.',
        pernas: false,
      },
      {
        id: 'panturrilha-d25',
        nome: 'Panturrilha',
        objetivo: 'Fortalecer panturrilha',
        duracao: '5 min',
        instrucoes: [
          'Em pé, suba na ponta dos pés.',
          'Segure 3 segundos.',
          'Desça devagar.',
          '15 repetições.',
          'Faça 2 séries.',
        ],
        sensacao: 'queimação na panturrilha.',
        evitar: 'perder o equilíbrio.',
        dica: 'Panturrilha forte = escadas mais fáceis.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Como subir escadas sem dor',
      conteudo: [
        'Técnica correta para subir escadas:',
        '✅ Ao subir:',
        '• Use a força dos glúteos',
        '• Mantenha joelho alinhado',
        '• Suba com controle',
        '✅ Ao descer (mais importante):',
        '• Vá devagar',
        '• Controle o movimento',
        '• Use corrimão se necessário',
        '❌ Evite:',
        '• Descer rápido',
        '• Joelhos caindo para dentro',
        'Pratique a técnica!',
      ],
    },
  },

  dia26: {
    exercicios: [
      {
        id: 'agach-medio-d26',
        nome: 'Agachamento médio',
        objetivo: 'Aumentar amplitude com segurança',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 50 graus (se sem dor).',
          'Mantenha joelhos alinhados.',
          'Suba devagar.',
          '12 repetições.',
        ],
        sensacao: 'ativação forte em toda a perna.',
        evitar: 'dor no joelho.',
        dica: 'Você está cada vez mais forte!',
        pernas: false,
      },
      {
        id: 'gluteo-iso-15s-d26',
        nome: 'Glúteo médio isometria 15s',
        objetivo: 'Máxima resistência',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de lado.',
          'Eleve a perna 30 graus.',
          'Segure 15 segundos.',
          '6 repetições por perna.',
        ],
        sensacao: 'queimação intensa na lateral do quadril.',
        evitar: 'perder alinhamento.',
        dica: '15 segundos é desafiador - você consegue!',
        pernas: true,
      },
      {
        id: 'along-posterior-d26',
        nome: 'Alongamento posterior',
        objetivo: 'Manter flexibilidade',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve uma perna estendida.',
          'Segure 30 segundos.',
          'Repita 2 vezes por perna.',
        ],
        sensacao: 'alongamento suave.',
        evitar: 'forçar demais.',
        dica: 'Mantenha a flexibilidade.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Construindo estabilidade',
      conteudo: [
        'Estabilidade é a chave para um joelho saudável:',
        '✅ O que é estabilidade?',
        '• Controle de movimento',
        '• Músculos trabalhando juntos',
        '• Equilíbrio dinâmico',
        '✅ Como construir:',
        '• Fortaleça glúteos e quadríceps',
        '• Pratique movimentos controlados',
        '• Desafie o equilíbrio',
        'Você está construindo um joelho estável!',
      ],
    },
  },

  dia27: {
    exercicios: [
      {
        id: 'agach-ponte-circuito-d27',
        nome: 'Agachamento + ponte (circuito)',
        objetivo: 'Integrar movimentos',
        duracao: '5 min',
        instrucoes: [
          '10 agachamentos (40–50 graus).',
          '10 pontes.',
          'Descanse 30 segundos.',
          'Repita 2 vezes.',
        ],
        sensacao: 'ativação em toda a perna e glúteos.',
        evitar: 'perder a forma.',
        dica: 'Circuito desafia resistência.',
        pernas: false,
      },
      {
        id: 'mob-quadril-d27',
        nome: 'Mobilidade quadril',
        objetivo: 'Manter amplitude',
        duracao: '5 min',
        instrucoes: [
          'Em pé, segure em uma parede.',
          'Faça círculos com o joelho.',
          '10 para cada lado.',
          'Repita 2 vezes.',
        ],
        sensacao: 'movimento livre do quadril.',
        evitar: 'movimentos bruscos.',
        dica: 'Mantenha a mobilidade.',
        pernas: true,
      },
      {
        id: 'along-quadriceps-d27',
        nome: 'Alongamento quadríceps',
        objetivo: 'Relaxar musculatura',
        duracao: '5 min',
        instrucoes: [
          'Em pé, segure o pé atrás.',
          'Traga o calcanhar ao glúteo.',
          'Segure 30 segundos por perna.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento na frente da coxa.',
        evitar: 'dor no joelho.',
        dica: 'Relaxe a musculatura.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Fortalecendo a base do movimento',
      conteudo: [
        'A base do movimento é formada por:',
        '✅ Tornozelo móvel',
        '✅ Joelho estável',
        '✅ Quadril forte',
        '✅ Core ativado',
        'Quando a base está forte:',
        '• Movimentos são mais eficientes',
        '• Dor diminui',
        '• Risco de lesões reduz',
        'Você construiu uma base sólida!',
      ],
    },
  },

  dia28: {
    exercicios: [
      {
        id: 'step-lateral-d28',
        nome: 'Step lateral',
        objetivo: 'Desafiar glúteo médio',
        duracao: '5 min',
        instrucoes: [
          'Use um degrau baixo.',
          'Suba lateralmente.',
          'Desça com controle.',
          '10 repetições por perna.',
        ],
        sensacao: 'ativação na lateral do quadril.',
        evitar: 'perder o equilíbrio.',
        dica: 'Movimento lateral é desafiador.',
        pernas: true,
      },
      {
        id: 'agach-leve-d28',
        nome: 'Agachamento leve',
        objetivo: 'Manter técnica',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 40 graus.',
          'Suba devagar.',
          '12 repetições.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'Mantenha a técnica perfeita.',
        pernas: false,
      },
      {
        id: 'mob-geral-d28',
        nome: 'Mobilidade geral',
        objetivo: 'Mobilizar todo o corpo',
        duracao: '5 min',
        instrucoes: [
          'Rotação de tornozelo.',
          'Mobilidade de joelho.',
          'Mobilidade de quadril.',
          'Mobilidade de coluna.',
        ],
        sensacao: 'corpo solto.',
        evitar: 'movimentos bruscos.',
        dica: 'Mantenha o corpo móvel.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Controle e equilíbrio',
      conteudo: [
        'Controle e equilíbrio são essenciais:',
        '✅ Controle:',
        '• Movimentos lentos e precisos',
        '• Sem compensações',
        '• Técnica correta',
        '✅ Equilíbrio:',
        '• Estabilidade em uma perna',
        '• Propriocepção',
        '• Confiança',
        'Você desenvolveu ambos!',
      ],
    },
  },

  dia29: {
    exercicios: [
      {
        id: 'agach-funcional-medio-d29',
        nome: 'Agachamento funcional leve/médio',
        objetivo: 'Consolidar movimento',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 40–50 graus.',
          'Mantenha joelhos alinhados.',
          'Suba devagar.',
          '12 repetições.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'Você dominou o movimento!',
        pernas: false,
      },
      {
        id: 'ponte-gluteo-d29',
        nome: 'Ponte com foco em glúteo',
        objetivo: 'Maximizar ativação',
        duracao: '5 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve o quadril.',
          'Aperte os glúteos com força.',
          'Segure 5 segundos.',
          '12 repetições.',
        ],
        sensacao: 'queimação nos glúteos.',
        evitar: 'dor lombar.',
        dica: 'Finalize forte!',
        pernas: false,
      },
      {
        id: 'along-global-d29',
        nome: 'Alongamento global',
        objetivo: 'Relaxar todo o corpo',
        duracao: '5 min',
        instrucoes: [
          'Alongamento posterior (30s cada).',
          'Alongamento de quadríceps (30s cada).',
          'Alongamento de glúteo (30s cada).',
          'Alongamento de panturrilha (30s cada).',
        ],
        sensacao: 'relaxamento completo.',
        evitar: 'forçar demais.',
        dica: 'Relaxe e celebre sua jornada.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Consolidando resultados',
      conteudo: [
        'Você está quase lá! Veja o que conquistou:',
        '✅ Joelho mais forte',
        '✅ Menos dor',
        '✅ Mais confiança',
        '✅ Movimentos seguros',
        '✅ Conhecimento sobre seu corpo',
        'Amanhã é o último dia - vamos finalizar com chave de ouro!',
      ],
    },
  },

  dia30: {
    exercicios: [
      {
        id: 'mob-global-d30',
        nome: 'Mobilidade global',
        objetivo: 'Preparar o corpo',
        duracao: '5 min',
        instrucoes: [
          'Rotação de tornozelo (10 vezes cada).',
          'Mobilidade de joelho (10 vezes).',
          'Mobilidade de quadril (10 círculos cada).',
          'Mobilidade de coluna (10 rotações).',
        ],
        sensacao: 'corpo aquecido e solto.',
        evitar: 'movimentos bruscos.',
        dica: 'Celebre cada movimento!',
        pernas: false,
      },
      {
        id: 'agach-leve-d30',
        nome: 'Agachamento leve',
        objetivo: 'Finalizar com técnica perfeita',
        duracao: '5 min',
        instrucoes: [
          'Em pé, pés na largura dos ombros.',
          'Desça 40 graus.',
          'Mantenha joelhos alinhados.',
          'Suba devagar.',
          '12 repetições.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'joelhos caindo para dentro.',
        dica: 'Você dominou o movimento!',
        pernas: false,
      },
      {
        id: 'along-completo-d30',
        nome: 'Alongamento completo',
        objetivo: 'Finalizar com gratidão',
        duracao: '5 min',
        instrucoes: [
          'Alongamento posterior (30s cada).',
          'Alongamento de quadríceps (30s cada).',
          'Alongamento de glúteo (30s cada).',
          'Alongamento de panturrilha (30s cada).',
          'Respire profundamente e agradeça ao seu corpo.',
        ],
        sensacao: 'relaxamento e gratidão.',
        evitar: 'forçar demais.',
        dica: 'Você completou 30 dias! Parabéns! 🎉',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Como manter seu joelho saudável para sempre',
      conteudo: [
        'Parabéns por completar os 30 dias! 🎉🎉🎉',
        'Para manter seu joelho saudável:',
        '✅ Continue praticando 3x por semana',
        '✅ Mantenha-se ativo (caminhe, nade, pedale)',
        '✅ Fortaleça glúteos e quadríceps regularmente',
        '✅ Alongue-se diariamente',
        '✅ Ouça seu corpo',
        '✅ Mantenha peso saudável',
        '❌ Não pare de se movimentar',
        'Você transformou seu joelho - agora mantenha os resultados!',
        'Parabéns pela dedicação! 💙',
      ],
    },
  },
};
