export const dadosTrilhaCorridaIniciante = {
  nome: 'Corrida Iniciante',
  descricao: 'Programa de 30 dias para preparar seu joelho para correr com segurança, começando do zero',
  totalDias: 30,
  fases: [
    {
      numero: 1,
      nome: 'Base e Mobilidade',
      descricao: 'Preparação inicial com mobilidade e caminhada progressiva',
      dias: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      numero: 2,
      nome: 'Introdução ao Trote',
      descricao: 'Primeiros intervalos de trote combinados com caminhada',
      dias: [8, 9, 10, 11, 12, 13, 14],
    },
    {
      numero: 3,
      nome: 'Corrida Progressiva',
      descricao: 'Aumento gradual do tempo de corrida contínua',
      dias: [15, 16, 17, 18, 19, 20, 21],
    },
    {
      numero: 4,
      nome: 'Corrida Contínua',
      descricao: 'Consolidação da corrida contínua e resistência',
      dias: [22, 23, 24, 25, 26, 27, 28, 29, 30],
    },
  ],
  dias: {
    // FASE 1 - Dias 1 a 7
    1: {
      titulo: 'Dia 1 — Corrida Iniciante',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Prepara o tornozelo para absorver impacto',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Coloque um pé à frente, joelho levemente flexionado',
            'Empurre o joelho para frente, mantendo o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha e mobilidade no tornozelo.',
          evitar: 'Não tire o calcanhar do chão. Não force além do confortável.',
          dica: 'Boa mobilidade de tornozelo reduz o impacto no joelho durante a corrida.',
        },
        {
          titulo: 'Ponte',
          subtitulo: 'Fortalece glúteos para proteger o joelho',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados e pés apoiados',
            'Eleve o quadril, formando uma linha reta dos ombros aos joelhos',
            'Contraia os glúteos no topo',
            'Segure por 3 segundos e desça lentamente',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente, não a lombar.',
          evitar: 'Não arqueie demais as costas. Mantenha o core ativado.',
          dica: 'Glúteos fortes são essenciais para correr sem sobrecarregar o joelho.',
        },
        {
          titulo: 'Caminhada 5 minutos',
          subtitulo: 'Inicia condicionamento cardiovascular',
          duracao: '5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe em ritmo confortável por 5 minutos',
            'Mantenha postura ereta',
            'Balance os braços naturalmente',
            'Respire de forma natural e ritmada',
            'Foque em passos controlados',
          ],
          sensacaoCorreta: 'Você deve sentir aquecimento leve, sem fadiga excessiva.',
          evitar: 'Não caminhe muito rápido. Mantenha ritmo sustentável.',
          dica: 'A caminhada é a base para construir resistência para a corrida.',
        },
      ],
      aula: {
        titulo: 'Por que mobilidade é o início',
        conteudo: `Antes de começar a correr, é fundamental preparar seu corpo com mobilidade adequada. O tornozelo, em particular, precisa de boa amplitude de movimento para absorver o impacto da corrida de forma eficiente.\n\nQuando o tornozelo tem mobilidade limitada, o joelho compensa, aumentando o risco de lesões. Por isso, começamos com exercícios de mobilidade antes de introduzir a corrida. Esta base sólida protegerá seu joelho durante toda a jornada.`,
      },
    },
    2: {
      titulo: 'Dia 2 — Corrida Iniciante',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mini-agachamento',
          subtitulo: 'Fortalece quadríceps e glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça apenas 30 graus (mini agachamento)',
            'Mantenha os joelhos alinhados com os pés',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não desça muito se sentir dor. Não deixe os joelhos ultrapassarem os pés.',
          dica: 'Força nas pernas é essencial para absorver o impacto da corrida.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece musculatura da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando intensamente.',
          evitar: 'Não use impulso. Mantenha o movimento controlado.',
          dica: 'Panturrilha forte é fundamental para a propulsão na corrida.',
        },
        {
          titulo: 'Caminhada 8 minutos',
          subtitulo: 'Aumenta resistência cardiovascular',
          duracao: '8 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe em ritmo confortável por 8 minutos',
            'Mantenha postura ereta',
            'Balance os braços naturalmente',
            'Respire de forma natural',
            'Mantenha ritmo constante',
          ],
          sensacaoCorreta: 'Você deve sentir aquecimento moderado, ainda confortável.',
          evitar: 'Não acelere demais. Mantenha ritmo sustentável.',
          dica: 'Aumente o tempo gradualmente para construir resistência.',
        },
      ],
      aula: {
        titulo: 'O pé na corrida',
        conteudo: `O pé é o primeiro ponto de contato com o solo durante a corrida, e sua função é crucial. Um pé forte e estável distribui melhor o impacto, protegendo o joelho.\n\nA panturrilha trabalha como uma mola, absorvendo e devolvendo energia a cada passada. Fortalecer essa musculatura desde o início prepara seu corpo para os desafios da corrida e reduz significativamente o risco de lesões no joelho.`,
      },
    },
    3: {
      titulo: 'Dia 3 — Corrida Iniciante',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade de Quadril',
          subtitulo: 'Melhora amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente em 90 graus',
            'Empurre o quadril para frente suavemente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas. Mantenha o movimento controlado.',
          dica: 'Quadril móvel permite melhor mecânica de corrida.',
        },
        {
          titulo: 'Abdução Lateral',
          subtitulo: 'Fortalece glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não rode o quadril para trás. Mantenha o movimento controlado.',
          dica: 'Glúteo médio forte evita que o joelho "entre" durante a corrida.',
        },
        {
          titulo: 'Caminhada 10 minutos',
          subtitulo: 'Aumenta resistência progressivamente',
          duracao: '10 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe em ritmo confortável por 10 minutos',
            'Mantenha postura ereta',
            'Balance os braços naturalmente',
            'Respire de forma ritmada',
            'Mantenha ritmo constante',
          ],
          sensacaoCorreta: 'Você deve sentir aquecimento moderado, ainda confortável.',
          evitar: 'Não acelere demais. Foque na consistência.',
          dica: 'Cada minuto a mais fortalece sua base cardiovascular.',
        },
      ],
      aula: {
        titulo: 'Evitando joelho entrando',
        conteudo: `Um dos erros mais comuns na corrida é o joelho "entrando" (valgo dinâmico), o que aumenta significativamente o estresse na articulação. Isso acontece quando o glúteo médio está fraco.\n\nFortalecer o glúteo médio desde o início cria uma base de estabilidade lateral que mantém o joelho alinhado durante a corrida. Esse alinhamento correto é fundamental para correr sem dor e sem lesões.`,
      },
    },
    4: {
      titulo: 'Dia 4 — Corrida Iniciante',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade Torácica',
          subtitulo: 'Melhora postura para corrida',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com as mãos no chão',
            'Coloque uma mão atrás da cabeça',
            'Rode o tronco, levando o cotovelo para cima',
            'Segure por 2 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento e rotação na parte superior das costas.',
          evitar: 'Não force a rotação. Mantenha o movimento suave.',
          dica: 'Boa mobilidade torácica melhora a mecânica respiratória na corrida.',
        },
        {
          titulo: 'Ponte Unilateral Leve',
          subtitulo: 'Fortalece glúteos de forma unilateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Segure por 3 segundos no topo',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando intensamente.',
          evitar: 'Não torça o quadril. Mantenha o core ativado.',
          dica: 'Força unilateral é essencial para a corrida, que é um movimento alternado.',
        },
        {
          titulo: 'Caminhada 12 minutos',
          subtitulo: 'Continua construindo resistência',
          duracao: '12 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe em ritmo confortável por 12 minutos',
            'Mantenha postura ereta',
            'Balance os braços naturalmente',
            'Respire de forma ritmada',
            'Mantenha ritmo constante',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo confortavelmente.',
          evitar: 'Não acelere demais. Foque na consistência.',
          dica: 'A resistência é construída gradualmente, dia após dia.',
        },
      ],
      aula: {
        titulo: 'Postura da corrida',
        conteudo: `A postura correta na corrida é fundamental para eficiência e prevenção de lesões. Mantenha o tronco ereto, ombros relaxados, olhar para frente e braços balançando naturalmente.\n\nUma boa postura permite respiração eficiente e distribui melhor o impacto pelo corpo. A mobilidade torácica que você está trabalhando ajuda a manter essa postura correta mesmo quando começar a cansar durante a corrida.`,
      },
    },
    5: {
      titulo: 'Dia 5 — Corrida Iniciante',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha e mobilidade no tornozelo.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Continue trabalhando mobilidade para preparar para o impacto.',
        },
        {
          titulo: 'Panturrilha com Pausa',
          subtitulo: 'Aumenta força da panturrilha',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Pause por 3 segundos no topo',
            'Desça lentamente',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando intensamente durante a pausa.',
          evitar: 'Não use impulso. Mantenha controle total.',
          dica: 'A pausa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Caminhada 15 minutos',
          subtitulo: 'Aumenta resistência cardiovascular',
          duracao: '15 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe em ritmo confortável por 15 minutos',
            'Mantenha postura ereta',
            'Balance os braços naturalmente',
            'Respire de forma ritmada',
            'Mantenha ritmo constante',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo sem esforço excessivo.',
          evitar: 'Não acelere demais. Foque na consistência.',
          dica: '15 minutos é uma marca importante — você está construindo resistência real.',
        },
      ],
      aula: {
        titulo: 'Impacto controlado',
        conteudo: `A corrida gera impacto de 2-3 vezes o peso corporal a cada passada. Seu corpo precisa estar preparado para absorver e distribuir esse impacto de forma eficiente.\n\nOs exercícios de fortalecimento que você está fazendo preparam músculos e articulações para lidar com esse impacto. A progressão gradual permite que seu corpo se adapte sem sobrecarregar o joelho.`,
      },
    },
    6: {
      titulo: 'Dia 6 — Corrida Iniciante',
      fase: 1,
      exercicios: [
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Fortalece membros inferiores',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Mantenha os joelhos alinhados com os pés',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando harmoniosamente.',
          evitar: 'Não desça além do confortável. Não deixe os joelhos "entrarem".',
          dica: 'Agachamento fortalece todos os músculos necessários para correr.',
        },
        {
          titulo: 'Panturrilha Unilateral',
          subtitulo: 'Fortalece cada perna individualmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta de um pé',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando intensamente.',
          evitar: 'Não use impulso. Mantenha equilíbrio.',
          dica: 'Força unilateral é essencial para a corrida.',
        },
        {
          titulo: 'Caminhada 15 minutos',
          subtitulo: 'Mantém resistência cardiovascular',
          duracao: '15 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe em ritmo confortável por 15 minutos',
            'Mantenha postura ereta',
            'Balance os braços naturalmente',
            'Respire de forma ritmada',
            'Mantenha ritmo constante',
          ],
          sensacaoCorreta: 'Você deve sentir confiança na sua resistência.',
          evitar: 'Não acelere demais. Foque na consistência.',
          dica: 'Você está pronto para começar a correr na próxima semana!',
        },
      ],
      aula: {
        titulo: 'Quando posso correr',
        conteudo: `Você está pronto para começar a correr quando consegue caminhar 15-20 minutos confortavelmente, tem boa mobilidade de tornozelo e quadril, e força básica nas pernas.\n\nNa próxima semana, você começará a introduzir intervalos curtos de trote. A progressão será gradual e segura, sempre respeitando os limites do seu corpo. Você construiu uma base sólida esta semana!`,
      },
    },
    7: {
      titulo: 'Dia 7 — Corrida Iniciante',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade completa prepara o corpo para a corrida.',
        },
        {
          titulo: 'Ponte com Pausa',
          subtitulo: 'Fortalece glúteos intensamente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril',
            'Pause por 5 segundos no topo',
            'Desça lentamente',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são a base para correr sem dor.',
        },
        {
          titulo: 'Caminhada 20 minutos',
          subtitulo: 'Consolida resistência da semana',
          duracao: '20 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe em ritmo confortável por 20 minutos',
            'Mantenha postura ereta',
            'Balance os braços naturalmente',
            'Respire de forma ritmada',
            'Celebre sua conquista da semana',
          ],
          sensacaoCorreta: 'Você deve sentir confiança e orgulho da sua evolução.',
          evitar: 'Não acelere demais. Aproveite a caminhada.',
          dica: 'Você completou a primeira semana! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Semana 1 — Base construída',
        conteudo: `Parabéns por completar a primeira semana! Você construiu uma base sólida de mobilidade, força e resistência cardiovascular. Seu corpo agora está preparado para começar a correr.\n\nNa próxima semana, você começará a introduzir intervalos curtos de trote. Lembre-se: a progressão é gradual e segura. Você está no caminho certo para se tornar um corredor!`,
      },
    },

    // FASE 2 - Dias 8 a 14
    8: {
      titulo: 'Dia 8 — Corrida Iniciante',
      fase: 2,
      exercicios: [
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Prepara para o impacto do trote',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha e mobilidade no tornozelo.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade absorve melhor o impacto do trote.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece para o primeiro trote',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando intensamente.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte é essencial para o trote.',
        },
        {
          titulo: 'Caminhada 2 min + Trote 30s (x4)',
          subtitulo: 'Primeiro contato com o trote',
          duracao: '10 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 2 minutos em ritmo confortável',
            'Trote leve por 30 segundos',
            'Repita este ciclo 4 vezes',
            'Mantenha o trote muito leve',
            'Foque na técnica, não na velocidade',
          ],
          sensacaoCorreta: 'Você deve sentir que o trote é confortável e controlado.',
          evitar: 'Não corra rápido. Mantenha o trote muito leve.',
          dica: 'Este é seu primeiro trote — foque em sentir o movimento.',
        },
      ],
      aula: {
        titulo: 'Primeiro impacto',
        conteudo: `Parabéns pelo seu primeiro trote! O impacto da corrida é diferente da caminhada, e seu corpo precisa se adaptar gradualmente. Os intervalos curtos permitem que você experimente o movimento sem sobrecarregar o joelho.\n\nÉ normal sentir os músculos trabalhando mais intensamente. Isso é sinal de que seu corpo está se adaptando. Continue com a progressão gradual e seu joelho se fortalecerá para suportar corridas mais longas.`,
      },
    },
    9: {
      titulo: 'Dia 9 — Corrida Iniciante',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Fortalece para absorver impacto',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando.',
          evitar: 'Não desça além do confortável.',
          dica: 'Pernas fortes absorvem melhor o impacto da corrida.',
        },
        {
          titulo: 'Ponte',
          subtitulo: 'Mantém força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril',
            'Contraia os glúteos no topo',
            'Segure por 3 segundos',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes protegem o joelho durante a corrida.',
        },
        {
          titulo: 'Caminhada 2 min + Trote 45s (x4)',
          subtitulo: 'Aumenta tempo de trote',
          duracao: '11 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 2 minutos em ritmo confortável',
            'Trote leve por 45 segundos',
            'Repita este ciclo 4 vezes',
            'Mantenha o trote leve e controlado',
            'Foque na cadência (passos rápidos e curtos)',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o trote confortavelmente.',
          evitar: 'Não corra rápido. Foque em passos curtos e rápidos.',
          dica: 'Cadência alta (passos rápidos) reduz o impacto no joelho.',
        },
      ],
      aula: {
        titulo: 'Cadência',
        conteudo: `Cadência é o número de passos por minuto. Uma cadência ideal para iniciantes é de 160-180 passos por minuto. Passos mais curtos e rápidos reduzem o impacto no joelho.\n\nEm vez de dar passadas longas, foque em passos curtos e rápidos. Isso pode parecer estranho no início, mas é muito mais eficiente e seguro para o joelho. Pratique essa técnica desde o início.`,
      },
    },
    10: {
      titulo: 'Dia 10 — Corrida Iniciante',
      fase: 2,
      exercicios: [
        {
          titulo: 'Mobilidade de Quadril',
          subtitulo: 'Melhora amplitude para corrida',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor mecânica de corrida.',
        },
        {
          titulo: 'Abdução',
          subtitulo: 'Fortalece glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não rode o quadril.',
          dica: 'Glúteo médio forte mantém o joelho alinhado na corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Trote 45s (x6)',
          subtitulo: 'Aumenta frequência de trote',
          duracao: '10.5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Trote leve por 45 segundos',
            'Repita este ciclo 6 vezes',
            'Mantenha o trote leve',
            'Foque em passos curtos',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo em todos os intervalos.',
          evitar: 'Não acelere nos últimos intervalos. Mantenha consistência.',
          dica: 'Mais intervalos preparam seu corpo para corrida contínua.',
        },
      ],
      aula: {
        titulo: 'Passo curto',
        conteudo: `Passos curtos são a chave para correr sem lesões. Quando você dá passadas longas, o pé aterrissa muito à frente do corpo, aumentando o impacto no joelho.\n\nPassos curtos permitem que o pé aterrisse mais próximo do centro de gravidade, reduzindo o impacto. Combine isso com cadência alta (passos rápidos) e você terá uma técnica eficiente e segura para o joelho.`,
      },
    },
    11: {
      titulo: 'Dia 11 — Corrida Iniciante',
      fase: 2,
      exercicios: [
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Continue trabalhando mobilidade regularmente.',
        },
        {
          titulo: 'Panturrilha Unilateral',
          subtitulo: 'Fortalece cada perna individualmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta de um pé',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando intensamente.',
          evitar: 'Não use impulso.',
          dica: 'Força unilateral é essencial para a corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Trote 1 min (x5)',
          subtitulo: 'Iguala tempo de caminhada e trote',
          duracao: '10 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Trote leve por 1 minuto',
            'Repita este ciclo 5 vezes',
            'Mantenha o trote leve e controlado',
            'Foque na técnica',
          ],
          sensacaoCorreta: 'Você deve sentir que 1 minuto de trote é confortável.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você está progredindo muito bem!',
        },
      ],
      aula: {
        titulo: 'Técnica eficiente',
        conteudo: `Uma técnica eficiente de corrida inclui: postura ereta, ombros relaxados, braços balançando naturalmente, passos curtos e rápidos, e aterrissagem suave.\n\nFoque nesses elementos durante seus intervalos de trote. Boa técnica não só previne lesões, mas também torna a corrida mais eficiente e menos cansativa. Pratique conscientemente até que se torne natural.`,
      },
    },
    12: {
      titulo: 'Dia 12 — Corrida Iniciante',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento com Pausa',
          subtitulo: 'Aumenta força das pernas',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Pause por 3 segundos',
            'Suba empurrando pelos calcanhares',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando durante a pausa.',
          evitar: 'Não desça além do confortável.',
          dica: 'Pausa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Ponte Unilateral',
          subtitulo: 'Fortalece glúteos de forma avançada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Segure por 3 segundos no topo',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito.',
          evitar: 'Não torça o quadril.',
          dica: 'Força unilateral é essencial para a corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Trote 1 min (x6)',
          subtitulo: 'Aumenta volume de trote',
          duracao: '12 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Trote leve por 1 minuto',
            'Repita este ciclo 6 vezes',
            'Mantenha o trote leve',
            'Foque na consistência',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo em todos os intervalos.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você está construindo resistência real para a corrida.',
        },
      ],
      aula: {
        titulo: 'Fortalecer para não doer',
        conteudo: `A melhor forma de prevenir dor no joelho durante a corrida é fortalecer os músculos ao redor da articulação. Quadríceps, glúteos e panturrilha trabalham juntos para absorver o impacto.\n\nQuando esses músculos são fortes, eles protegem o joelho, distribuindo melhor as forças. Continue com os exercícios de fortalecimento regularmente — eles são tão importantes quanto a corrida em si.`,
      },
    },
    13: {
      titulo: 'Dia 13 — Corrida Iniciante',
      fase: 2,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade completa prepara o corpo para a corrida.',
        },
        {
          titulo: 'Glúteo Médio',
          subtitulo: 'Fortalece estabilizador lateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Segure por 3 segundos no topo',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Glúteo médio forte mantém o joelho firme na corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Trote 90s (x4)',
          subtitulo: 'Aumenta tempo de trote',
          duracao: '10 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Trote leve por 90 segundos (1min30s)',
            'Repita este ciclo 4 vezes',
            'Mantenha o trote leve',
            'Foque na técnica',
          ],
          sensacaoCorreta: 'Você deve sentir que 90 segundos de trote é desafiador mas confortável.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você está progredindo para intervalos mais longos!',
        },
      ],
      aula: {
        titulo: 'Joelho firme',
        conteudo: `Um joelho firme e estável é resultado de músculos fortes ao redor da articulação, especialmente o glúteo médio. Quando esse músculo é forte, ele mantém o joelho alinhado durante a corrida.\n\nSe o joelho "entra" durante a corrida, isso aumenta significativamente o risco de lesões. Continue fortalecendo o glúteo médio para manter seu joelho firme e protegido.`,
      },
    },
    14: {
      titulo: 'Dia 14 — Corrida Iniciante',
      fase: 2,
      exercicios: [
        {
          titulo: 'Mobilidade Global',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade regular mantém o corpo preparado.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Mantém força da panturrilha',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte é essencial para a corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Trote 90s (x5)',
          subtitulo: 'Consolida progresso da semana',
          duracao: '12.5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Trote leve por 90 segundos',
            'Repita este ciclo 5 vezes',
            'Mantenha o trote leve',
            'Celebre sua evolução',
          ],
          sensacaoCorreta: 'Você deve sentir confiança na sua capacidade de trotar.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você completou a segunda semana! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Semana 2 — Trote estabelecido',
        conteudo: `Parabéns por completar a segunda semana! Você introduziu o trote com sucesso e seu corpo está se adaptando ao impacto da corrida. Você já consegue trotar por 90 segundos confortavelmente.\n\nNa próxima semana, você começará a aumentar o tempo de corrida contínua, reduzindo os intervalos de caminhada. Continue com a progressão gradual e logo você estará correndo continuamente!`,
      },
    },

    // FASE 3 - Dias 15 a 21
    15: {
      titulo: 'Dia 15 — Corrida Iniciante',
      fase: 3,
      exercicios: [
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Continue trabalhando mobilidade regularmente.',
        },
        {
          titulo: 'Agachamento Médio',
          subtitulo: 'Aumenta força das pernas',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando intensamente.',
          evitar: 'Não desça além do confortável.',
          dica: 'Pernas mais fortes suportam corridas mais longas.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 2 min (x4)',
          subtitulo: 'Aumenta tempo de corrida',
          duracao: '12 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 2 minutos',
            'Repita este ciclo 4 vezes',
            'Mantenha a corrida leve',
            'Foque em passos curtos e eficientes',
          ],
          sensacaoCorreta: 'Você deve sentir que 2 minutos de corrida é desafiador mas confortável.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você está correndo por 2 minutos seguidos!',
        },
      ],
      aula: {
        titulo: 'Passada eficiente',
        conteudo: `Uma passada eficiente é aquela que minimiza o desperdício de energia e o impacto no joelho. Isso inclui: aterrissagem suave (não bater o pé no chão), passos curtos e rápidos, e empurrar com o pé de trás.\n\nEvite dar passadas longas ou aterrissagens pesadas. Foque em uma corrida leve e fluida, como se estivesse deslizando sobre o chão. Essa técnica protege o joelho e torna a corrida mais eficiente.`,
      },
    },
    16: {
      titulo: 'Dia 16 — Corrida Iniciante',
      fase: 3,
      exercicios: [
        {
          titulo: 'Mobilidade de Quadril',
          subtitulo: 'Melhora amplitude para corrida',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor mecânica de corrida.',
        },
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Maximiza força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 5 segundos no topo',
            'Desça muito lentamente (5 segundos)',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para correr sem dor.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 2 min (x5)',
          subtitulo: 'Aumenta volume de corrida',
          duracao: '15 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 2 minutos',
            'Repita este ciclo 5 vezes',
            'Mantenha a corrida leve',
            'Foque em aterrissagem suave',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo em todos os intervalos.',
          evitar: 'Não acelere. Foque em aterrissagem suave.',
          dica: 'Aterrissagem suave protege o joelho.',
        },
      ],
      aula: {
        titulo: 'Aterrissagem suave',
        conteudo: `A forma como seu pé aterrissa no chão durante a corrida afeta diretamente o impacto no joelho. Uma aterrissagem suave e silenciosa indica boa técnica.\n\nSe você ouve seus pés batendo forte no chão, está aterrissando com muito impacto. Foque em aterrissagens suaves, como se estivesse correndo descalço em uma superfície delicada. Isso reduz significativamente o estresse no joelho.`,
      },
    },
    17: {
      titulo: 'Dia 17 — Corrida Iniciante',
      fase: 3,
      exercicios: [
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Continue trabalhando mobilidade regularmente.',
        },
        {
          titulo: 'Glúteo Médio Forte',
          subtitulo: 'Aumenta força lateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Pause por 4 segundos no topo',
            'Desça muito lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando muito intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Glúteo médio forte mantém o joelho estável na corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 3 min (x4)',
          subtitulo: 'Aumenta tempo de corrida',
          duracao: '16 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 3 minutos',
            'Repita este ciclo 4 vezes',
            'Mantenha a corrida leve',
            'Foque na técnica',
          ],
          sensacaoCorreta: 'Você deve sentir que 3 minutos de corrida é desafiador mas confortável.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você está correndo por 3 minutos seguidos!',
        },
      ],
      aula: {
        titulo: 'Escada e corrida',
        conteudo: `Subir escadas é um excelente complemento para a corrida. Fortalece os mesmos músculos usados na corrida, especialmente glúteos e quadríceps, mas com menos impacto.\n\nSe você consegue subir escadas sem dor, é um bom sinal de que seu joelho está se fortalecendo para a corrida. Continue com os exercícios de fortalecimento para manter essa progressão.`,
      },
    },
    18: {
      titulo: 'Dia 18 — Corrida Iniciante',
      fase: 3,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade completa prepara o corpo para a corrida.',
        },
        {
          titulo: 'Panturrilha Forte',
          subtitulo: 'Aumenta força da panturrilha',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Pause por 3 segundos no topo',
            'Desça muito lentamente (4 segundos)',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando muito intensamente.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte é essencial para a propulsão na corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 3 min (x5)',
          subtitulo: 'Aumenta volume de corrida',
          duracao: '20 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 3 minutos',
            'Repita este ciclo 5 vezes',
            'Mantenha a corrida leve',
            'Foque na consistência',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo em todos os intervalos.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você está construindo resistência real para a corrida.',
        },
      ],
      aula: {
        titulo: 'Panturrilha na corrida',
        conteudo: `A panturrilha é um dos músculos mais importantes na corrida. Ela funciona como uma mola, absorvendo o impacto da aterrissagem e devolvendo energia para a propulsão.\n\nUma panturrilha forte permite corrida mais eficiente e reduz o estresse no joelho. Continue fortalecendo esse músculo regularmente — ele é fundamental para correr sem dor.`,
      },
    },
    19: {
      titulo: 'Dia 19 — Corrida Iniciante',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento Confortável',
          subtitulo: 'Mantém força das pernas',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até onde se sentir confortável',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e força.',
          evitar: 'Não desça além do confortável.',
          dica: 'Pernas fortes suportam corridas mais longas.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Mantém força da panturrilha',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Continue fortalecendo a panturrilha regularmente.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 4 min (x4)',
          subtitulo: 'Aumenta tempo de corrida',
          duracao: '20 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 4 minutos',
            'Repita este ciclo 4 vezes',
            'Mantenha a corrida leve',
            'Foque na respiração',
          ],
          sensacaoCorreta: 'Você deve sentir que 4 minutos de corrida é desafiador mas confortável.',
          evitar: 'Não acelere. Foque em respiração ritmada.',
          dica: 'Você está correndo por 4 minutos seguidos!',
        },
      ],
      aula: {
        titulo: 'Respiração',
        conteudo: `A respiração correta é fundamental para correr confortavelmente. Respire de forma natural e ritmada, sincronizando com seus passos. Uma técnica comum é inspirar por 3 passos e expirar por 2 passos.\n\nNão prenda a respiração ou respire muito superficialmente. Se você não consegue manter uma conversa durante a corrida, está correndo rápido demais. Reduza o ritmo e foque em respiração confortável.`,
      },
    },
    20: {
      titulo: 'Dia 20 — Corrida Iniciante',
      fase: 3,
      exercicios: [
        {
          titulo: 'Mobilidade de Quadril',
          subtitulo: 'Mantém amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor mecânica de corrida.',
        },
        {
          titulo: 'Ponte Unilateral Avançada',
          subtitulo: 'Maximiza força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Pause por 5 segundos no topo',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito intensamente.',
          evitar: 'Não torça o quadril.',
          dica: 'Força unilateral é essencial para a corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 4 min (x5)',
          subtitulo: 'Aumenta volume de corrida',
          duracao: '25 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 4 minutos',
            'Repita este ciclo 5 vezes',
            'Mantenha a corrida leve',
            'Foque em cadência ideal (passos rápidos)',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo em todos os intervalos.',
          evitar: 'Não acelere. Foque em cadência alta.',
          dica: 'Cadência ideal (160-180 passos/min) reduz impacto no joelho.',
        },
      ],
      aula: {
        titulo: 'Cadência ideal',
        conteudo: `A cadência ideal para a maioria dos corredores é de 160-180 passos por minuto. Essa cadência reduz o impacto no joelho e torna a corrida mais eficiente.\n\nPara verificar sua cadência, conte quantos passos você dá em 30 segundos e multiplique por 2. Se estiver abaixo de 160, foque em passos mais curtos e rápidos. Com o tempo, essa cadência se tornará natural.`,
      },
    },
    21: {
      titulo: 'Dia 21 — Corrida Iniciante',
      fase: 3,
      exercicios: [
        {
          titulo: 'Mobilidade Global',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade regular mantém o corpo preparado.',
        },
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Mantém força das pernas',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e força.',
          evitar: 'Não desça além do confortável.',
          dica: 'Continue fortalecendo as pernas regularmente.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 5 min (x4)',
          subtitulo: 'Consolida progresso da semana',
          duracao: '24 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 5 minutos',
            'Repita este ciclo 4 vezes',
            'Mantenha a corrida leve',
            'Celebre sua evolução',
          ],
          sensacaoCorreta: 'Você deve sentir confiança na sua capacidade de correr.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você completou a terceira semana! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Semana 3 — Corrida estabelecida',
        conteudo: `Parabéns por completar a terceira semana! Você agora consegue correr por 5 minutos seguidos confortavelmente. Seu corpo se adaptou ao impacto da corrida e você desenvolveu resistência real.\n\nNa última semana, você aumentará ainda mais o tempo de corrida contínua, reduzindo os intervalos de caminhada até conseguir correr continuamente. Você está quase lá!`,
      },
    },

    // FASE 4 - Dias 22 a 30
    22: {
      titulo: 'Dia 22 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade prepara o corpo para a corrida.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Mantém força da panturrilha',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Continue fortalecendo a panturrilha.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 6 min (x4)',
          subtitulo: 'Aumenta tempo de corrida',
          duracao: '28 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 6 minutos',
            'Repita este ciclo 4 vezes',
            'Mantenha a corrida relaxada',
            'Foque em correr de forma relaxada',
          ],
          sensacaoCorreta: 'Você deve sentir que 6 minutos de corrida é confortável.',
          evitar: 'Não acelere. Mantenha corrida relaxada.',
          dica: 'Corrida relaxada é mais eficiente e menos cansativa.',
        },
      ],
      aula: {
        titulo: 'Corrida relaxada',
        conteudo: `Uma corrida relaxada é aquela em que você mantém ombros soltos, braços balançando naturalmente, mandíbula relaxada e respiração confortável. Tensão desnecessária desperdiça energia.\n\nFoque em manter o corpo relaxado durante a corrida. Se perceber tensão nos ombros ou mandíbula, relaxe conscientemente. Corrida relaxada é mais eficiente e permite correr por mais tempo sem fadiga.`,
      },
    },
    23: {
      titulo: 'Dia 23 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade prepara o corpo para a corrida.',
        },
        {
          titulo: 'Abdução com Banda',
          subtitulo: 'Fortalece glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica acima dos joelhos',
            'Fique em pé com pés afastados',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Glúteo médio forte mantém o joelho estável na corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 7 min (x4)',
          subtitulo: 'Aumenta tempo de corrida',
          duracao: '32 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 7 minutos',
            'Repita este ciclo 4 vezes',
            'Mantenha a corrida leve',
            'Foque em postura ereta',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter boa postura durante toda a corrida.',
          evitar: 'Não deixe a postura se deteriorar quando cansar.',
          dica: 'Boa postura mantém eficiência mesmo quando cansado.',
        },
      ],
      aula: {
        titulo: 'Postura',
        conteudo: `Manter boa postura durante toda a corrida é fundamental para eficiência e prevenção de lesões. Quando você cansa, a tendência é curvar as costas e deixar os ombros caírem.\n\nFoque conscientemente em manter postura ereta, especialmente nos últimos minutos de corrida. Imagine um fio puxando o topo da sua cabeça para cima. Boa postura permite respiração eficiente e distribui melhor o impacto.`,
      },
    },
    24: {
      titulo: 'Dia 24 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade prepara o corpo para a corrida.',
        },
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Mantém força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 5 segundos no topo',
            'Desça muito lentamente',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para correr sem dor.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 8 min (x3)',
          subtitulo: 'Aumenta tempo de corrida',
          duracao: '27 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 8 minutos',
            'Repita este ciclo 3 vezes',
            'Mantenha a corrida leve',
            'Foque em técnicas de impacto suave',
          ],
          sensacaoCorreta: 'Você deve sentir que 8 minutos de corrida é desafiador mas confortável.',
          evitar: 'Não acelere. Foque em aterrissagem suave.',
          dica: 'Você está correndo por 8 minutos seguidos!',
        },
      ],
      aula: {
        titulo: 'Técnicas de impacto',
        conteudo: `Reduzir o impacto no joelho durante a corrida envolve várias técnicas: aterrissagem suave (não bater o pé), passos curtos e rápidos, aterrissagem com o meio do pé (não calcanhar), e manter joelhos levemente flexionados.\n\nPratique essas técnicas conscientemente durante a corrida. Com o tempo, elas se tornarão automáticas e você correrá de forma mais eficiente e segura para o joelho.`,
      },
    },
    25: {
      titulo: 'Dia 25 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade prepara o corpo para a corrida.',
        },
        {
          titulo: 'Agachamento Médio',
          subtitulo: 'Mantém força das pernas',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando.',
          evitar: 'Não desça além do confortável.',
          dica: 'Pernas fortes suportam corridas mais longas.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 9 min (x3)',
          subtitulo: 'Aumenta tempo de corrida',
          duracao: '30 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 9 minutos',
            'Repita este ciclo 3 vezes',
            'Mantenha a corrida leve',
            'Foque em evitar canelite (dor na canela)',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo confortavelmente.',
          evitar: 'Não acelere. Se sentir dor na canela, reduza o ritmo.',
          dica: 'Canelite é comum em iniciantes — previna com boa técnica.',
        },
      ],
      aula: {
        titulo: 'Evitando canelite',
        conteudo: `Canelite (dor na parte da frente da canela) é comum em corredores iniciantes. É causada por sobrecarga dos músculos da canela, geralmente devido a progressão muito rápida ou técnica inadequada.\n\nPara prevenir: progrida gradualmente, fortaleça a panturrilha, use calçado adequado, evite superfícies muito duras, e foque em aterrissagem suave. Se sentir dor na canela, reduza o volume de corrida e foque em fortalecimento.`,
      },
    },
    26: {
      titulo: 'Dia 26 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade prepara o corpo para a corrida.',
        },
        {
          titulo: 'Panturrilha Unilateral',
          subtitulo: 'Mantém força da panturrilha',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta de um pé',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando intensamente.',
          evitar: 'Não use impulso.',
          dica: 'Força unilateral é essencial para a corrida.',
        },
        {
          titulo: 'Caminhada 1 min + Corrida 10 min (x3)',
          subtitulo: 'Aumenta tempo de corrida',
          duracao: '33 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Caminhe 1 minuto em ritmo confortável',
            'Corra leve por 10 minutos',
            'Repita este ciclo 3 vezes',
            'Mantenha a corrida leve',
            'Lembre-se: velocidade não importa',
          ],
          sensacaoCorreta: 'Você deve sentir que 10 minutos de corrida é confortável.',
          evitar: 'Não acelere. Foque em manter ritmo sustentável.',
          dica: 'Você está correndo por 10 minutos seguidos!',
        },
      ],
      aula: {
        titulo: 'Velocidade não importa',
        conteudo: `Nesta fase inicial, velocidade não importa. O objetivo é construir resistência e adaptar o corpo ao impacto da corrida. Correr devagar é perfeitamente aceitável — e recomendado.\n\nMuitos iniciantes cometem o erro de correr rápido demais, o que aumenta o risco de lesões e torna a corrida menos sustentável. Foque em correr de forma confortável, em um ritmo que você consegue manter por todo o tempo. Velocidade virá naturalmente com o tempo.`,
      },
    },
    27: {
      titulo: 'Dia 27 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade prepara o corpo para a corrida.',
        },
        {
          titulo: 'Glúteo Médio Avançado',
          subtitulo: 'Maximiza força lateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Pause por 5 segundos no topo',
            'Desça muito lentamente (5 segundos)',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando muito intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Glúteo médio forte mantém o joelho estável na corrida.',
        },
        {
          titulo: 'Corrida Contínua 12-15 minutos',
          subtitulo: 'Primeira corrida contínua',
          duracao: '12-15 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Corra continuamente por 12-15 minutos',
            'Sem intervalos de caminhada',
            'Mantenha ritmo confortável',
            'Foque em ajustes de ritmo conforme necessário',
            'Celebre esta conquista!',
          ],
          sensacaoCorreta: 'Você deve sentir orgulho de correr continuamente pela primeira vez.',
          evitar: 'Não acelere. Mantenha ritmo sustentável.',
          dica: 'Você está correndo continuamente! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Ajustes de ritmo',
        conteudo: `Durante uma corrida contínua, é normal precisar ajustar o ritmo. Se sentir que está cansando muito, reduza o ritmo. Se sentir que está muito confortável, pode acelerar levemente.\n\nO objetivo é encontrar um ritmo sustentável que você consiga manter por todo o tempo. Com a experiência, você aprenderá a sentir qual é o ritmo ideal para você. Não tenha medo de ajustar o ritmo durante a corrida.`,
      },
    },
    28: {
      titulo: 'Dia 28 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade prepara o corpo para a corrida.',
        },
        {
          titulo: 'Ponte Unilateral',
          subtitulo: 'Mantém força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Segure por 4 segundos no topo',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito.',
          evitar: 'Não torça o quadril.',
          dica: 'Força unilateral é essencial para a corrida.',
        },
        {
          titulo: 'Corrida Contínua 15-20 minutos',
          subtitulo: 'Aumenta resistência',
          duracao: '15-20 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Corra continuamente por 15-20 minutos',
            'Sem intervalos de caminhada',
            'Mantenha ritmo confortável',
            'Foque em construir resistência',
            'Aproveite a corrida',
          ],
          sensacaoCorreta: 'Você deve sentir que consegue manter o ritmo confortavelmente.',
          evitar: 'Não acelere. Foque em consistência.',
          dica: 'Você está construindo resistência real para a corrida.',
        },
      ],
      aula: {
        titulo: 'Resistência',
        conteudo: `Resistência é a capacidade de manter um esforço por um período prolongado. Você está construindo resistência cardiovascular e muscular para a corrida.\n\nResistência é construída gradualmente, através de corridas regulares e progressão consistente. Continue correndo regularmente após este programa e sua resistência continuará melhorando. Você está no caminho certo!`,
      },
    },
    29: {
      titulo: 'Dia 29 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade prepara o corpo para a corrida.',
        },
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Mantém força das pernas',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e força.',
          evitar: 'Não desça além do confortável.',
          dica: 'Continue fortalecendo as pernas regularmente.',
        },
        {
          titulo: 'Corrida Contínua 20-25 minutos',
          subtitulo: 'Aumenta resistência',
          duracao: '20-25 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Corra continuamente por 20-25 minutos',
            'Sem intervalos de caminhada',
            'Mantenha ritmo confortável',
            'Foque em aproveitar a corrida',
            'Você é um corredor!',
          ],
          sensacaoCorreta: 'Você deve sentir orgulho e confiança na sua capacidade de correr.',
          evitar: 'Não acelere. Aproveite a experiência.',
          dica: 'Você é oficialmente um corredor!',
        },
      ],
      aula: {
        titulo: 'Você é um corredor',
        conteudo: `Parabéns! Você agora é um corredor. Você construiu a base de mobilidade, força e resistência necessária para correr de forma segura e sustentável.\n\nSer um corredor não significa correr rápido ou longas distâncias — significa ter a capacidade e o hábito de correr regularmente. Você conquistou isso através de dedicação e progressão consistente. Continue correndo e você continuará melhorando!`,
      },
    },
    30: {
      titulo: 'Dia 30 — Corrida Iniciante',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara o corpo para corrida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Rotação de tronco (10 cada lado)',
            'Movimente-se de forma fluida e celebre sua conquista',
          ],
          sensacaoCorreta: 'Você deve sentir todas as articulações soltas, móveis e saudáveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Continue fazendo mobilidade antes de cada corrida.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Mantém força da panturrilha',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15-20 repetições com orgulho',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha forte e preparada.',
          evitar: 'Não use impulso.',
          dica: 'Continue fortalecendo a panturrilha 2-3x por semana.',
        },
        {
          titulo: 'Corrida Contínua 25-30 minutos',
          subtitulo: 'Corrida final de celebração',
          duracao: '25-30 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Corra continuamente por 25-30 minutos',
            'Sem intervalos de caminhada',
            'Mantenha ritmo confortável',
            'Aproveite cada minuto',
            'Celebre sua conquista incrível!',
          ],
          sensacaoCorreta: 'Você deve sentir orgulho, satisfação e confiança.',
          evitar: 'Não pare de correr — mantenha o hábito!',
          dica: 'Você completou o programa! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Mantendo corrida sem dor',
        conteudo: `Parabéns por completar os 30 dias! Você transformou seu corpo e desenvolveu a capacidade de correr 25-30 minutos continuamente. Mas o trabalho não termina aqui.\n\nPara manter a corrida sem dor: continue correndo 2-3 vezes por semana, mantenha exercícios de fortalecimento 2x por semana, faça mobilidade antes de cada corrida, aumente volume gradualmente (não mais que 10% por semana), e ouça seu corpo. Você conquistou algo incrível — agora mantenha esse hábito saudável para sempre!`,
      },
    },
  },
};
