export const dadosTrilhaVoltaTreinos = {
  nome: 'Volta aos Treinos',
  descricao: 'Programa de 28 dias para retornar à musculação, funcional ou treinos esportivos com segurança — reforço muscular, mobilidade e confiança',
  totalDias: 28,
  fases: [
    {
      numero: 1,
      nome: 'Base e Mobilidade',
      descricao: 'Preparação inicial com mobilidade e ativação muscular',
      dias: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      numero: 2,
      nome: 'Fortalecimento Progressivo',
      descricao: 'Construção de força com exercícios controlados',
      dias: [8, 9, 10, 11, 12, 13, 14],
    },
    {
      numero: 3,
      nome: 'Preparação para Carga',
      descricao: 'Movimentos funcionais e preparação para treinos',
      dias: [15, 16, 17, 18, 19, 20, 21],
    },
    {
      numero: 4,
      nome: 'Retorno aos Treinos',
      descricao: 'Consolidação e retorno seguro às atividades',
      dias: [22, 23, 24, 25, 26, 27, 28],
    },
  ],
  dias: {
    // FASE 1 - Dias 1 a 7
    1: {
      titulo: 'Dia 1 — Volta aos Treinos',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade do Joelho',
          subtitulo: 'Prepara a articulação para movimentos',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira com as costas retas',
            'Flexione e estenda o joelho suavemente',
            'Faça movimentos lentos e controlados',
            'Repita 15-20 vezes de cada lado',
            'Respire naturalmente durante o movimento',
          ],
          sensacaoCorreta: 'Você deve sentir o joelho se movendo livremente, sem dor aguda.',
          evitar: 'Não force o movimento além do confortável. Não faça movimentos bruscos.',
          dica: 'Mobilidade é essencial antes de retornar aos treinos — prepare a articulação.',
        },
        {
          titulo: 'Ponte',
          subtitulo: 'Ativa glúteos e protege o joelho',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados e pés apoiados',
            'Eleve o quadril, formando uma linha reta',
            'Contraia os glúteos no topo',
            'Segure por 2-3 segundos e desça lentamente',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente.',
          evitar: 'Não arqueie demais as costas. Mantenha o core ativado.',
          dica: 'Glúteos fortes são fundamentais para proteger o joelho durante treinos.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Relaxa cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente com o calcanhar no chão',
            'Incline o tronco para frente suavemente',
            'Mantenha por 25-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir um alongamento suave na parte de trás da coxa.',
          evitar: 'Não force o alongamento ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho durante treinos.',
        },
      ],
      aula: {
        titulo: 'Importância do início gradual',
        conteudo: `Retornar aos treinos após dor no joelho exige paciência e progressão gradual. Começar muito rápido ou com carga excessiva pode agravar a lesão e prolongar a recuperação.\n\nEste programa foi criado para preparar seu joelho de forma segura, fortalecendo músculos protetores, melhorando mobilidade e construindo confiança. Respeite cada fase — seu joelho agradecerá.`,
      },
    },
    2: {
      titulo: 'Dia 2 — Volta aos Treinos',
      fase: 1,
      exercicios: [
        {
          titulo: 'Agachamento com Cadeira',
          subtitulo: 'Reensina padrão de movimento seguro',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma cadeira',
            'Desça lentamente como se fosse sentar',
            'Toque levemente o assento e volte',
            'Mantenha os joelhos alinhados com os pés',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando.',
          evitar: 'Não deixe os joelhos ultrapassarem muito os pés. Não caia na cadeira.',
          dica: 'A cadeira oferece segurança para reaprender o movimento correto.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Melhora dorsiflexão e mecânica do joelho',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Coloque um pé à frente, joelho levemente flexionado',
            'Empurre o joelho para frente, mantendo o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento suave na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela durante treinos.',
        },
        {
          titulo: 'Extensão de Joelho Sentado',
          subtitulo: 'Ativa quadríceps de forma controlada',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira com as costas retas',
            'Estenda uma perna à frente até ficar reta',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da coxa trabalhando.',
          evitar: 'Não use impulso. Mantenha o movimento controlado.',
          dica: 'Quadríceps forte é essencial para retornar aos treinos com segurança.',
        },
      ],
      aula: {
        titulo: 'Reaprendendo a dobrar o joelho',
        conteudo: `Após dor no joelho, é comum desenvolver compensações e padrões de movimento incorretos. Reaprender a dobrar o joelho corretamente é fundamental para evitar recidivas.\n\nFoque em manter o joelho alinhado com o segundo dedo do pé, distribuir o peso pelos calcanhares e usar o quadril para gerar força. Esses detalhes fazem toda a diferença.`,
      },
    },
    3: {
      titulo: 'Dia 3 — Volta aos Treinos',
      fase: 1,
      exercicios: [
        {
          titulo: 'Abdução Lateral',
          subtitulo: 'Fortalece glúteo médio e estabiliza joelho',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede ou cadeira',
            'Eleve uma perna lateralmente, mantendo-a reta',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não incline o tronco. Mantenha o movimento controlado.',
          dica: 'Glúteo médio forte previne que o joelho "entre" durante treinos.',
        },
        {
          titulo: 'Elevação de Perna Estendida',
          subtitulo: 'Fortalece quadríceps sem sobrecarregar patela',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com uma perna flexionada',
            'Mantenha a outra perna estendida',
            'Eleve a perna estendida até a altura do joelho oposto',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando.',
          evitar: 'Não arqueie as costas.',
          dica: 'Este exercício fortalece o quadríceps de forma muito segura.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Mantém flexibilidade da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo suavemente',
            'Mantenha por 25-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Glúteos como protetores',
        conteudo: `Os glúteos são os músculos mais importantes para proteger o joelho durante treinos. Quando os glúteos estão fracos, o joelho tende a desalinhar, aumentando o risco de lesão.\n\nFortalecer os glúteos cria uma base sólida de estabilidade que protege o joelho em todos os movimentos — agachamentos, saltos, corridas. Priorize sempre a ativação dos glúteos.`,
      },
    },
    4: {
      titulo: 'Dia 4 — Volta aos Treinos',
      fase: 1,
      exercicios: [
        {
          titulo: 'Step Baixo',
          subtitulo: 'Inicia movimento funcional controlado',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo (10-12 cm) ou livros empilhados',
            'Apoie-se em uma parede se necessário',
            'Suba com um pé, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado com o pé',
            'Desça lentamente com controle',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Step prepara o joelho para movimentos de treino como agachamento e avanço.',
        },
        {
          titulo: 'Ponte Unilateral Leve',
          subtitulo: 'Fortalece glúteos de forma unilateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente (ou mantenha levemente apoiada)',
            'Eleve o quadril usando principalmente uma perna',
            'Segure por 3 segundos no topo',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando.',
          evitar: 'Não torça o quadril. Mantenha o core ativado.',
          dica: 'Força unilateral é essencial para treinos funcionais.',
        },
        {
          titulo: 'Alongamento Posterior Profundo',
          subtitulo: 'Alongamento intenso da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente, tentando alcançar o pé',
            'Mantenha por 30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento intenso na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor aguda.',
          dica: 'Flexibilidade posterior é essencial para treinos sem dor.',
        },
      ],
      aula: {
        titulo: 'Subida de carga inteligente',
        conteudo: `Aumentar a carga nos treinos deve ser feito de forma inteligente e gradual. A regra geral é aumentar no máximo 10% por semana — seja em peso, repetições ou intensidade.\n\nPriorize sempre a técnica perfeita antes de aumentar a carga. Um movimento bem executado com carga menor é muito mais eficaz e seguro que um movimento compensado com carga maior.`,
      },
    },
    5: {
      titulo: 'Dia 5 — Volta aos Treinos',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mini-agachamento na Parede',
          subtitulo: 'Fortalece com suporte e controle',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Encoste as costas na parede',
            'Deslize para baixo até 30 graus (mini agachamento)',
            'Segure a posição por 10-12 segundos',
            'Descanse 10 segundos',
            'Faça 8-10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Isometria fortalece sem movimento, protegendo a patela.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Melhora amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos lentos com o joelho elevado',
            'Faça 12 círculos para cada lado',
            'Depois faça 12 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir o quadril se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Quadril móvel permite melhor distribuição de carga no joelho.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece musculatura da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte melhora a mecânica do joelho durante treinos.',
        },
      ],
      aula: {
        titulo: 'O básico bem feito',
        conteudo: `Treinos eficazes não precisam ser complexos. O básico bem feito — agachamentos, pontes, steps — é suficiente para construir força e preparar o joelho para treinos mais intensos.\n\nFoque em executar cada movimento com técnica perfeita, controle total e alinhamento correto. Essa base sólida permitirá progressões seguras e eficazes.`,
      },
    },
    6: {
      titulo: 'Dia 6 — Volta aos Treinos',
      fase: 1,
      exercicios: [
        {
          titulo: 'Marcha Estacionária',
          subtitulo: 'Ativa musculatura sem impacto',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma cadeira se necessário',
            'Eleve um joelho de cada vez, como se estivesse marchando',
            'Mantenha o movimento controlado',
            'Faça 30-40 repetições (15-20 cada perna)',
          ],
          sensacaoCorreta: 'Você deve sentir os músculos das pernas trabalhando sem impacto.',
          evitar: 'Não eleve o joelho muito alto se sentir dor. Não faça movimentos bruscos.',
          dica: 'Movimento sem impacto prepara o joelho para treinos mais intensos.',
        },
        {
          titulo: 'Ponte com Pausa',
          subtitulo: 'Aumenta tempo sob tensão dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril',
            'Pause por 4-5 segundos no topo, contraindo os glúteos',
            'Desça lentamente',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente durante a pausa.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Pausa aumenta a intensidade do exercício de forma segura.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos com os tornozelos',
            'Faça 12 círculos para cada lado',
            'Depois faça 12 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir os tornozelos se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela durante treinos.',
        },
      ],
      aula: {
        titulo: 'Preparação para treinar',
        conteudo: `Preparar o corpo antes de treinar é essencial para prevenir lesões. Um aquecimento adequado aumenta a temperatura muscular, melhora a mobilidade articular e ativa o sistema nervoso.\n\nDedique 5-10 minutos ao aquecimento antes de cada treino. Inclua mobilidade articular, ativação muscular e movimentos específicos do treino que você fará.`,
      },
    },
    7: {
      titulo: 'Dia 7 — Volta aos Treinos',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Faça círculos com os tornozelos (12 cada lado)',
            'Flexione e estenda os joelhos suavemente (12 vezes)',
            'Faça círculos com os quadris sentado (12 cada lado)',
            'Movimente-se de forma fluida e controlada',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações aquecendo e ficando mais soltas.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade global prepara o corpo para treinos funcionais.',
        },
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Consolida técnica de agachamento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus com apoio se necessário',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Técnica correta é mais importante que amplitude.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura trabalhada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue posterior sentado (25-30s)',
            'Alongue quadríceps em pé (25-30s cada lado)',
            'Alongue quadril sentado (25-30s cada lado)',
            'Respire profundamente durante os alongamentos',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação e previne rigidez.',
        },
      ],
      aula: {
        titulo: 'Semana 1 — Sua evolução',
        conteudo: `Parabéns por completar a primeira semana! Você trabalhou mobilidade, ativação muscular e controle inicial de movimento. Seu joelho já está mais preparado para os desafios das próximas semanas.\n\nNa próxima fase, vamos aumentar gradualmente a intensidade, focando em fortalecimento mais específico. Continue prestando atenção ao alinhamento do joelho e ao controle dos movimentos — esses detalhes fazem toda a diferença.`,
      },
    },

    // FASE 2 - Dias 8 a 14
    8: {
      titulo: 'Dia 8 — Volta aos Treinos',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento Parcial',
          subtitulo: 'Aumenta amplitude gradualmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus (se sem dor)',
            'Mantenha os joelhos alinhados com os pés',
            'Suba empurrando pelos calcanhares',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando com controle.',
          evitar: 'Não desça além do ponto de dor. Não deixe os joelhos "entrarem".',
          dica: 'Aumente amplitude apenas se estiver sem dor.',
        },
        {
          titulo: 'Abdução com Faixa',
          subtitulo: 'Fortalece glúteo médio com resistência',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica leve acima dos joelhos',
            'Fique em pé com pés afastados e apoio',
            'Dê passos laterais pequenos contra a resistência',
            'Mantenha tensão constante',
            'Faça 12-15 passos de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando contra a resistência.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Glúteo médio forte previne valgo dinâmico durante treinos.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente',
            'Mantenha por 25-30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Fortalecer antes de intensificar',
        conteudo: `Antes de aumentar a intensidade dos treinos, é essencial construir uma base sólida de força. Músculos fortes protegem as articulações e permitem progressões seguras.\n\nNão tenha pressa em voltar aos treinos intensos. Dedique tempo para fortalecer quadríceps, glúteos e estabilizadores. Essa base sólida permitirá treinos mais intensos sem dor no futuro.`,
      },
    },
    9: {
      titulo: 'Dia 9 — Volta aos Treinos',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Baixo Controlado',
          subtitulo: 'Aperfeiçoa controle de movimento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo (10-12 cm)',
            'Suba lentamente (3 segundos) com apoio se necessário',
            'Pause por 2 segundos no topo',
            'Desça lentamente (3 segundos)',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir controle total durante todo o movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento lento aumenta o controle neuromuscular.',
        },
        {
          titulo: 'Ponte Unilateral',
          subtitulo: 'Fortalece glúteos de forma avançada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando principalmente uma perna',
            'Segure por 3-4 segundos no topo',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito.',
          evitar: 'Não torça o quadril.',
          dica: 'Força unilateral é essencial para treinos funcionais.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Empurre o joelho para frente mantendo o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
      ],
      aula: {
        titulo: 'Estabilizando o joelho',
        conteudo: `Estabilidade do joelho vem de músculos fortes e controle neuromuscular. Quando o joelho está estável, ele se move de forma coordenada e eficiente, reduzindo o risco de lesão.\n\nExercícios que desafiam o equilíbrio e o controle melhoram a estabilidade do joelho. Continue praticando movimentos controlados e você verá melhorias significativas.`,
      },
    },
    10: {
      titulo: 'Dia 10 — Volta aos Treinos',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento com Pausa',
          subtitulo: 'Aumenta tempo sob tensão',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus',
            'Pause por 3-4 segundos no fundo',
            'Suba empurrando pelos calcanhares',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando intensamente durante a pausa.',
          evitar: 'Não desça além do confortável.',
          dica: 'Pausa aumenta a intensidade do exercício de forma segura.',
        },
        {
          titulo: 'Extensão com Faixa Leve',
          subtitulo: 'Fortalece quadríceps com resistência',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com uma faixa elástica leve no tornozelo',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando contra a resistência.',
          evitar: 'Não use impulso.',
          dica: 'Resistência progressiva fortalece o quadríceps de forma eficaz.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Mantém flexibilidade da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo suavemente',
            'Mantenha por 25-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Distribuindo força',
        conteudo: `Distribuir a força corretamente durante movimentos é essencial para proteger o joelho. Use o quadril para gerar força, o quadríceps para controlar o movimento e os glúteos para estabilizar.\n\nQuando você distribui a força entre múltiplos grupos musculares, nenhuma estrutura é sobrecarregada. Isso permite treinos mais intensos sem dor ou lesão.`,
      },
    },
    11: {
      titulo: 'Dia 11 — Volta aos Treinos',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Lateral',
          subtitulo: 'Fortalece glúteo médio lateralmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo',
            'Suba lateralmente com apoio, mantendo o joelho alinhado',
            'Desça lentamente',
            'Foque no controle lateral',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Força lateral protege o joelho durante movimentos multidirecionais.',
        },
        {
          titulo: 'Elevação Lateral Lenta',
          subtitulo: 'Aumenta tempo sob tensão do glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente muito lentamente (4 segundos)',
            'Pause por 2 segundos no topo',
            'Desça muito lentamente (4 segundos)',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Movimento lento aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Mantém amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos lentos com o joelho elevado',
            'Faça 12 círculos para cada lado',
            'Depois faça 12 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir o quadril se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Carregar o quadril',
        conteudo: `Aprender a "carregar o quadril" — usar o quadril para gerar força — é fundamental para proteger o joelho durante treinos. Quando você usa o quadril, os glúteos assumem grande parte da carga.\n\nPratique empurrar pelos calcanhares e contrair os glúteos durante movimentos. Essa técnica reduz significativamente a pressão no joelho e permite treinos mais intensos.`,
      },
    },
    12: {
      titulo: 'Dia 12 — Volta aos Treinos',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento com Isometria',
          subtitulo: 'Fortalece em posição estática',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus',
            'Segure a posição por 12-15 segundos',
            'Descanse 10 segundos',
            'Faça 6-8 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Isometria fortalece sem movimento, protegendo a patela.',
        },
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Maximiza força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 5 segundos no topo',
            'Desça muito lentamente (4-5 segundos)',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para treinos sem dor.',
        },
        {
          titulo: 'Posterior Profundo',
          subtitulo: 'Alongamento intenso da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente, tentando alcançar o pé',
            'Mantenha por 30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento intenso na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor aguda.',
          dica: 'Flexibilidade posterior é essencial para treinos sem dor.',
        },
      ],
      aula: {
        titulo: 'Progredir com segurança',
        conteudo: `Progressão segura significa aumentar gradualmente a dificuldade dos exercícios sem causar dor ou lesão. Aumente um fator por vez — amplitude, repetições, carga ou velocidade.\n\nSe você aumentar tudo ao mesmo tempo, o risco de lesão aumenta significativamente. Seja paciente e progressivo — os resultados virão de forma sustentável.`,
      },
    },
    13: {
      titulo: 'Dia 13 — Volta aos Treinos',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Médio',
          subtitulo: 'Aumenta altura com controle',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio (15-18 cm) com apoio se necessário',
            'Suba com controle, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Altura maior prepara para treinos funcionais.',
        },
        {
          titulo: 'Abdução com Pausa',
          subtitulo: 'Aumenta tempo sob tensão do glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Pause por 4-5 segundos no topo',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Pausa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece musculatura da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 3 segundos no topo',
            'Desça lentamente',
            'Faça 18-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Estabilidade lateral',
        conteudo: `Estabilidade lateral é essencial para treinos que envolvem mudanças de direção, saltos laterais ou movimentos multidirecionais. O glúteo médio é o principal responsável por essa estabilidade.\n\nFortalecer o glúteo médio permite que você execute movimentos laterais com segurança, sem que o joelho "entre" ou desalinhe. Isso é fundamental para treinos funcionais e esportivos.`,
      },
    },
    14: {
      titulo: 'Dia 14 — Volta aos Treinos',
      fase: 2,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Faça círculos com os tornozelos (12 cada lado)',
            'Flexione e estenda os joelhos suavemente (12 vezes)',
            'Faça círculos com os quadris (12 cada lado)',
            'Movimente-se de forma fluida e controlada',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações aquecendo e ficando mais soltas.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade global prepara o corpo para treinos funcionais.',
        },
        {
          titulo: 'Agachamento Leve Contínuo',
          subtitulo: 'Aumenta resistência muscular',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Faça agachamentos leves (30-40 graus) continuamente',
            'Mantenha ritmo controlado',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir resistência muscular, mas com controle.',
          evitar: 'Não desça além do confortável.',
          dica: 'Movimento contínuo treina resistência para treinos.',
        },
        {
          titulo: 'Alongamento Geral',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (25-30s cada lado)',
            'Alongue posterior (25-30s)',
            'Alongue quadril (25-30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Semana 2 — Sua evolução',
        conteudo: `Parabéns por completar a segunda semana! Você trabalhou fortalecimento específico do quadríceps, glúteos e estabilizadores. Seu joelho agora está significativamente mais forte e estável.\n\nNa próxima fase, vamos focar em preparação para carga e movimentos funcionais. Você aprenderá a aplicar a força que desenvolveu em movimentos de treino. Continue com dedicação!`,
      },
    },

    // FASE 3 - Dias 15 a 21
    15: {
      titulo: 'Dia 15 — Volta aos Treinos',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento 40-60°',
          subtitulo: 'Aumenta amplitude com segurança',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-60 graus (se sem dor)',
            'Mantenha os joelhos alinhados com os pés',
            'Suba empurrando pelos calcanhares',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando com controle.',
          evitar: 'Não desça além do ponto de dor. Não deixe os joelhos "entrarem".',
          dica: 'Amplitude maior prepara para agachamentos de treino.',
        },
        {
          titulo: 'Ponte com Pausa Longa',
          subtitulo: 'Maximiza tempo sob tensão',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 6-8 segundos no topo',
            'Desça muito lentamente (5 segundos)',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para treinos sem dor.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Mantém amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos lentos com o joelho elevado',
            'Faça 15 círculos para cada lado',
            'Depois faça 15 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir o quadril se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Agachamento seguro',
        conteudo: `Agachar com segurança significa manter o joelho alinhado, usar o quadril para gerar força e controlar o movimento em todas as fases. Não existe uma profundidade "certa" — a profundidade ideal é aquela que você consegue executar sem dor e com técnica perfeita.\n\nFoque em qualidade de movimento, não em amplitude máxima. Um agachamento parcial bem executado é muito mais eficaz e seguro que um agachamento profundo compensado.`,
      },
    },
    16: {
      titulo: 'Dia 16 — Volta aos Treinos',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Alternado',
          subtitulo: 'Simula movimento real de treino',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio com apoio se necessário',
            'Suba alternando as pernas',
            'Mantenha ritmo controlado',
            'Foque no alinhamento do joelho',
            'Faça 10-12 repetições (5-6 cada perna)',
          ],
          sensacaoCorreta: 'Você deve sentir controle e fluidez no movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento alternado prepara para treinos funcionais.',
        },
        {
          titulo: 'Extensão Média',
          subtitulo: 'Fortalece quadríceps com carga progressiva',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com uma faixa elástica média no tornozelo',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando contra a resistência.',
          evitar: 'Não use impulso.',
          dica: 'Resistência progressiva fortalece de forma eficaz.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente',
            'Mantenha por 25-30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Controle na descida',
        conteudo: `Controlar a fase excêntrica (descida) dos movimentos é essencial para proteger o joelho. A descida controlada fortalece o quadríceps e melhora o controle neuromuscular.\n\nPratique descer lentamente em todos os exercícios — agachamentos, steps, avanços. Essa técnica reduz significativamente o estresse no joelho e permite treinos mais intensos sem dor.`,
      },
    },
    17: {
      titulo: 'Dia 17 — Volta aos Treinos',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento com Pausa',
          subtitulo: 'Aumenta controle e força',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 50-60 graus',
            'Pause por 4-5 segundos no fundo',
            'Suba empurrando pelos calcanhares',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando intensamente durante a pausa.',
          evitar: 'Não desça além do confortável.',
          dica: 'Pausa aumenta a intensidade do exercício de forma segura.',
        },
        {
          titulo: 'Abdução com Banda Forte',
          subtitulo: 'Maximiza força do glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica média/forte acima dos joelhos',
            'Fique em pé com pés afastados e apoio',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante',
            'Faça 15-20 passos de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Glúteo médio forte previne valgo dinâmico durante treinos.',
        },
        {
          titulo: 'Mobilidade Tornozelo Avançada',
          subtitulo: 'Maximiza amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma parede',
            'Coloque um pé à frente',
            'Empurre o joelho em direção à parede',
            'Mantenha o calcanhar no chão',
            'Segure por 8-10 segundos',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento intenso na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
      ],
      aula: {
        titulo: 'Evitando valgo',
        conteudo: `Valgo dinâmico (joelho "entrando") é um dos principais fatores de risco para lesões no joelho durante treinos. Ocorre quando o glúteo médio está fraco ou não é ativado corretamente.\n\nPara evitar valgo, fortaleça o glúteo médio, pratique conscientemente manter o joelho alinhado e use pistas visuais (espelho) durante treinos. Essa correção protege significativamente o joelho.`,
      },
    },
    18: {
      titulo: 'Dia 18 — Volta aos Treinos',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento Funcional',
          subtitulo: 'Simula movimento de treino',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça como se fosse pegar um objeto',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Este movimento é essencial para treinos funcionais.',
        },
        {
          titulo: 'Ponte Unilateral Avançada',
          subtitulo: 'Maximiza força unilateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril alto usando uma perna',
            'Pause por 4-5 segundos no topo',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito.',
          evitar: 'Não torça o quadril.',
          dica: 'Força unilateral é essencial para treinos funcionais.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Mantém flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo suavemente',
            'Mantenha por 30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Preparando para carga',
        conteudo: `Preparar o joelho para carga significa construir força, controle e confiança suficientes para suportar pesos externos. Não tenha pressa — comece com cargas leves e aumente gradualmente.\n\nQuando você retornar aos treinos com carga, comece com 50-60% do peso que você usava antes. Foque em técnica perfeita e aumente gradualmente. Seu joelho agradecerá.`,
      },
    },
    19: {
      titulo: 'Dia 19 — Volta aos Treinos',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Alto',
          subtitulo: 'Prepara para movimentos intensos',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau alto (20-25 cm) com apoio se necessário',
            'Suba com controle, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado',
            'Desça lentamente',
            'Faça 8-10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando intensamente.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Altura maior prepara para treinos intensos.',
        },
        {
          titulo: 'Mobilidade Seletiva',
          subtitulo: 'Trabalha mobilidade específica',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 repetições cada lado)',
            'Mobilidade de joelho (10 repetições)',
            'Mobilidade de quadril (10 círculos cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade específica prepara para treinos.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece musculatura da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 3 segundos no topo',
            'Desça lentamente',
            'Faça 20-25 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Estabilidade durante treinos',
        conteudo: `Manter estabilidade durante treinos intensos é essencial para prevenir lesões. Estabilidade vem de músculos fortes, controle neuromuscular e consciência corporal.\n\nDurante treinos, preste atenção ao alinhamento do joelho, mantenha o core ativado e use o quadril para gerar força. Esses detalhes mantêm o joelho estável mesmo em treinos intensos.`,
      },
    },
    20: {
      titulo: 'Dia 20 — Volta aos Treinos',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento Lento',
          subtitulo: 'Maximiza controle neuromuscular',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça muito lentamente (5 segundos) até 50-60 graus',
            'Pause por 2 segundos',
            'Suba lentamente (4 segundos)',
            'Faça 8-10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle total durante todo o movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Movimento lento aumenta o controle neuromuscular.',
        },
        {
          titulo: 'Abdução Pausa Longa',
          subtitulo: 'Maximiza tempo sob tensão',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Pause por 6-8 segundos no topo',
            'Desça muito lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando muito intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Pausa longa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (30s cada lado)',
            'Alongue posterior (30s)',
            'Alongue quadril (30s cada lado)',
            'Alongue panturrilha (30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Carregar melhor',
        conteudo: `"Carregar melhor" significa distribuir a carga de forma eficiente entre múltiplos grupos musculares. Use o quadril para gerar força, o quadríceps para controlar o movimento e os glúteos para estabilizar.\n\nQuando você carrega melhor, nenhuma estrutura é sobrecarregada. Isso permite treinos mais intensos sem dor ou lesão. Pratique essa distribuição conscientemente.`,
      },
    },
    21: {
      titulo: 'Dia 21 — Volta aos Treinos',
      fase: 3,
      exercicios: [
        {
          titulo: 'Circuito Leve (Agachamento + Step + Ponte)',
          subtitulo: 'Integra movimentos funcionais',
          duracao: '6-8 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Faça 10 agachamentos leves',
            'Faça 8 steps de cada lado',
            'Faça 12 pontes',
            'Descanse 1 minuto',
            'Repita o circuito 2-3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir resistência muscular, mas com controle.',
          evitar: 'Não force além do confortável.',
          dica: 'Circuito prepara para treinos funcionais.',
        },
        {
          titulo: 'Mobilidade Ativa',
          subtitulo: 'Movimenta todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (12 repetições cada lado)',
            'Mobilidade de joelho (12 repetições)',
            'Mobilidade de quadril (12 círculos cada lado)',
            'Movimente-se de forma fluida e controlada',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade ativa prepara para treinos.',
        },
        {
          titulo: 'Alongamento Geral',
          subtitulo: 'Celebração e relaxamento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (30s cada lado)',
            'Alongue posterior (30s)',
            'Alongue quadril (30s cada lado)',
            'Respire profundamente e celebre sua conquista',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e satisfação.',
          evitar: 'Não pare de se cuidar — mantenha os hábitos!',
          dica: 'Você completou a Fase 3! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Semana 3 — Sua evolução',
        conteudo: `Parabéns por completar a terceira semana! Você trabalhou preparação para carga, movimentos funcionais e controle avançado. Seu joelho agora está pronto para retornar aos treinos.\n\nNa próxima e última fase, vamos consolidar tudo que você aprendeu e preparar o retorno definitivo aos treinos. Continue com dedicação — você está quase lá!`,
      },
    },

    // FASE 4 - Dias 22 a 28
    22: {
      titulo: 'Dia 22 — Volta aos Treinos',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Médio',
          subtitulo: 'Consolida amplitude funcional',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 60-70 graus (se sem dor)',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do ponto de dor.',
          dica: 'Amplitude funcional prepara para treinos reais.',
        },
        {
          titulo: 'Step Médio',
          subtitulo: 'Consolida movimento funcional',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio (15-18 cm)',
            'Suba e desça com controle',
            'Mantenha o joelho alinhado',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando com controle.',
          evitar: 'Não use impulso.',
          dica: 'Step prepara para treinos funcionais.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente',
            'Mantenha por 30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Retorno seguro',
        conteudo: `Retornar aos treinos de forma segura significa começar com intensidade moderada e aumentar gradualmente. Não tente retomar imediatamente o nível que você tinha antes — isso aumenta o risco de recidiva.\n\nComece com 60-70% da intensidade anterior e aumente 10% por semana. Preste atenção aos sinais do seu corpo e ajuste conforme necessário. Paciência agora significa treinos sem dor no futuro.`,
      },
    },
    23: {
      titulo: 'Dia 23 — Volta aos Treinos',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Cadenciado',
          subtitulo: 'Maximiza controle excêntrico',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça muito lentamente (5 segundos) até 60 graus',
            'Suba em ritmo normal (2 segundos)',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle total durante a descida.',
          evitar: 'Não desça além do confortável.',
          dica: 'Controle excêntrico protege o joelho durante treinos.',
        },
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Maximiza força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 6-8 segundos no topo',
            'Desça muito lentamente (5 segundos)',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para treinos sem dor.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Mantém amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos lentos com o joelho elevado',
            'Faça 15 círculos para cada lado',
            'Depois faça 15 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir o quadril se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Controle excêntrico',
        conteudo: `Controle excêntrico (fase de descida) é uma das habilidades mais importantes para treinos sem dor. A descida controlada fortalece o quadríceps, melhora o controle neuromuscular e reduz o estresse no joelho.\n\nPratique descer lentamente em todos os exercícios de treino. Essa técnica simples pode fazer a diferença entre treinar com dor ou sem dor.`,
      },
    },
    24: {
      titulo: 'Dia 24 — Volta aos Treinos',
      fase: 4,
      exercicios: [
        {
          titulo: 'Step Alto',
          subtitulo: 'Prepara para movimentos intensos',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau alto (20-25 cm)',
            'Suba com controle, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando intensamente.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Altura maior prepara para treinos intensos.',
        },
        {
          titulo: 'Abdução Forte',
          subtitulo: 'Maximiza força do glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica forte acima dos joelhos',
            'Fique em pé com pés afastados',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante',
            'Faça 20-25 passos de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando muito intensamente.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Glúteo médio forte previne valgo dinâmico.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma parede',
            'Empurre o joelho em direção à parede',
            'Mantenha o calcanhar no chão',
            'Segure por 8-10 segundos',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
      ],
      aula: {
        titulo: 'Ritmo nos treinos',
        conteudo: `Encontrar o ritmo certo nos treinos é essencial para manter consistência sem dor. Não treine todos os dias com alta intensidade — alterne dias intensos com dias leves ou de recuperação.\n\nEscute seu corpo. Se sentir dor ou fadiga excessiva, reduza a intensidade ou tire um dia de descanso. Treinos consistentes e sustentáveis são mais eficazes que treinos intensos esporádicos.`,
      },
    },
    25: {
      titulo: 'Dia 25 — Volta aos Treinos',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Funcional Médio',
          subtitulo: 'Simula movimento de treino real',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 60-70 graus como se fosse pegar um objeto',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Este movimento é essencial para treinos funcionais.',
        },
        {
          titulo: 'Extensão Média',
          subtitulo: 'Consolida força do quadríceps',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com uma faixa elástica média no tornozelo',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 15-20 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando contra a resistência.',
          evitar: 'Não use impulso.',
          dica: 'Quadríceps forte é essencial para treinos sem dor.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Mantém flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo suavemente',
            'Mantenha por 30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Resiliência articular',
        conteudo: `Resiliência articular é a capacidade do joelho de suportar estresse repetido sem lesão. Você constrói resiliência através de fortalecimento progressivo, controle neuromuscular e recuperação adequada.\n\nSeu joelho agora é mais resiliente que no início do programa. Continue fortalecendo, prestando atenção à técnica e respeitando os sinais do seu corpo. Essa resiliência permitirá treinos intensos sem dor.`,
      },
    },
    26: {
      titulo: 'Dia 26 — Volta aos Treinos',
      fase: 4,
      exercicios: [
        {
          titulo: 'Circuito Leve',
          subtitulo: 'Integra movimentos funcionais',
          duracao: '6-8 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Faça 12 agachamentos médios',
            'Faça 10 steps de cada lado',
            'Faça 15 pontes',
            'Descanse 1 minuto',
            'Repita o circuito 2-3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir resistência muscular, mas com controle.',
          evitar: 'Não force além do confortável.',
          dica: 'Circuito prepara para treinos funcionais.',
        },
        {
          titulo: 'Mobilidade Ativa',
          subtitulo: 'Movimenta todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (15 repetições cada lado)',
            'Mobilidade de joelho (15 repetições)',
            'Mobilidade de quadril (15 círculos cada lado)',
            'Movimente-se de forma fluida e controlada',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade ativa prepara para treinos.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece musculatura da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 3 segundos no topo',
            'Desça lentamente',
            'Faça 25-30 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Preparando retorno total',
        conteudo: `Você está nos últimos dias do programa e seu joelho está preparado para retornar aos treinos. Mas lembre-se: retorno total não significa retomar imediatamente o nível anterior.\n\nComece com intensidade moderada e aumente gradualmente. Continue fazendo exercícios de fortalecimento 2-3 vezes por semana como manutenção. Essa abordagem garantirá treinos sem dor a longo prazo.`,
      },
    },
    27: {
      titulo: 'Dia 27 — Volta aos Treinos',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Moderado',
          subtitulo: 'Consolida força e controle',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 70-80 graus (se sem dor)',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do ponto de dor.',
          dica: 'Você está pronto para retornar aos treinos!',
        },
        {
          titulo: 'Ponte Unilateral Avançada',
          subtitulo: 'Maximiza força unilateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril alto usando uma perna',
            'Pause por 5-6 segundos no topo',
            'Faça 12-15 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito.',
          evitar: 'Não torça o quadril.',
          dica: 'Força unilateral é essencial para treinos funcionais.',
        },
        {
          titulo: 'Alongamento Geral',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (30s cada lado)',
            'Alongue posterior (30s)',
            'Alongue quadril (30s cada lado)',
            'Alongue panturrilha (30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Ajustes finais',
        conteudo: `Nos últimos dias do programa, foque em consolidar tudo que você aprendeu. Revise mentalmente os pontos-chave: alinhamento do joelho, uso do quadril, controle excêntrico, ativação dos glúteos.\n\nEsses detalhes técnicos farão toda a diferença quando você retornar aos treinos. Pratique-os conscientemente até se tornarem automáticos. Seu joelho está pronto — agora é hora de aplicar tudo que você aprendeu.`,
      },
    },
    28: {
      titulo: 'Dia 28 — Volta aos Treinos',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Confortável',
          subtitulo: 'Celebra sua evolução',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até a amplitude que você se sente confortável',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 20 repetições com orgulho',
          ],
          sensacaoCorreta: 'Você deve sentir controle, confiança e orgulho da sua evolução.',
          evitar: 'Não desça além do confortável.',
          dica: 'Compare com o Dia 1 — você evoluiu muito!',
        },
        {
          titulo: 'Step Médio ou Alto',
          subtitulo: 'Celebra sua força',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio ou alto (escolha você)',
            'Suba e desça com controle e confiança',
            'Mantenha o joelho alinhado',
            'Faça 15 repetições de cada lado',
            'Celebre cada repetição',
          ],
          sensacaoCorreta: 'Você deve sentir força, controle e satisfação.',
          evitar: 'Não pare de se cuidar — mantenha os hábitos!',
          dica: 'Você está pronto para retornar aos treinos!',
        },
        {
          titulo: 'Alongamento Geral',
          subtitulo: 'Celebração e relaxamento final',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (30s cada lado)',
            'Alongue posterior (30s)',
            'Alongue quadril (30s cada lado)',
            'Alongue panturrilha (30s cada lado)',
            'Respire profundamente e celebre sua conquista',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento, satisfação e orgulho.',
          evitar: 'Não pare de se cuidar — mantenha os hábitos!',
          dica: 'Você completou o programa! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Mantendo treinos sem dor',
        conteudo: `Parabéns por completar os 28 dias! Você fortaleceu seu joelho, melhorou sua mobilidade e recuperou sua capacidade de treinar sem dor. Mas o trabalho não termina aqui.\n\nPara manter esses resultados, continue fazendo exercícios de fortalecimento 2-3 vezes por semana, mantenha boa mobilidade e preste atenção à técnica durante treinos. Se sentir um leve desconforto, volte aos exercícios básicos. Seu joelho agora é mais forte e resiliente — mantenha-o assim! Você conquistou isso com seu esforço e dedicação. Parabéns e bons treinos!`,
      },
    },
  },
};
