// Dados completos da trilha de 21 dias para Dor ao Agachar
import { dadosFase3 } from './dados-fase3';

// Tipos
export interface Exercicio {
  id: string;
  nome: string;
  objetivo: string;
  duracao: string;
  instrucoes: string[];
  sensacao: string;
  evitar: string;
  dica: string;
  pernas: boolean;
}

export interface Aula {
  titulo: string;
  conteudo: string[];
}

export interface DadosDia {
  exercicios: Exercicio[];
  aula: Aula;
}

export const dadosTrilha: Record<string, DadosDia> = {
  // ========== FASE 1 - Dias 1 a 7 ==========
  dia1: {
    exercicios: [
      {
        id: 'mob-tornozelo-d1',
        nome: 'Mobilidade de Tornozelo',
        objetivo: 'Melhora dorsiflexão e reduz compensação no joelho',
        duracao: '4 min',
        instrucoes: [
          'Em pé, coloque um pé à frente do outro.',
          'Mantenha o calcanhar traseiro no chão.',
          'Leve o joelho da frente para frente, sem tirar o calcanhar do chão.',
          'Você deve sentir alongar na panturrilha.',
          'Faça 15 repetições lentas por perna.',
        ],
        sensacao: 'alongamento suave na panturrilha e mobilidade no tornozelo.',
        evitar: 'tirar o calcanhar do chão ou forçar demais.',
        dica: 'Tornozelo móvel = menos compensação no joelho durante o agachamento.',
        pernas: true,
      },
      {
        id: 'iso-quadriceps-d1',
        nome: 'Isometria de Quadríceps',
        objetivo: 'Ativa quadríceps para estabilizar o joelho',
        duracao: '4 min',
        instrucoes: [
          'Sente-se com as costas apoiadas.',
          'Estenda uma perna mantendo-a reta.',
          'Contraia o músculo da frente da coxa por 5 segundos.',
          'Relaxe por 2 segundos.',
          'Faça 12 repetições por perna.',
        ],
        sensacao: 'contração forte na frente da coxa.',
        evitar: 'dor aguda no joelho.',
        dica: 'Imagine empurrar o joelho para baixo contra o chão.',
        pernas: true,
      },
      {
        id: 'along-posterior-d1',
        nome: 'Alongamento Posterior',
        objetivo: 'Reduz tensão nos isquiotibiais',
        duracao: '4 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve uma perna estendida.',
          'Segure atrás da coxa ou use uma toalha.',
          'Mantenha por 30 segundos.',
          'Repita 3 vezes por perna.',
        ],
        sensacao: 'alongamento atrás da coxa.',
        evitar: 'dobrar o joelho ou forçar demais.',
        dica: 'Isquiotibiais encurtados limitam o agachamento seguro.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Por que agachar dói?',
      conteudo: [
        'A dor ao agachar geralmente acontece por três motivos principais:',
        '1. Falta de mobilidade de tornozelo → joelho compensa',
        '2. Fraqueza de glúteos e quadríceps → sobrecarga na patela',
        '3. Padrão de movimento incorreto → joelho cai para dentro',
        'A boa notícia: todos esses problemas podem ser corrigidos com exercícios específicos.',
        'Você está no caminho certo! Vamos trabalhar mobilidade, força e técnica.',
      ],
    },
  },

  dia2: {
    exercicios: [
      {
        id: 'ponte-d2',
        nome: 'Ponte',
        objetivo: 'Ativa glúteos para proteger o joelho',
        duracao: '4 min',
        instrucoes: [
          'Deite-se de costas com joelhos flexionados.',
          'Pés apoiados no chão, afastados na largura do quadril.',
          'Eleve o quadril até formar uma linha reta.',
          'Aperte os glúteos no topo por 3 segundos.',
          'Desça devagar.',
          'Faça 15 repetições.',
        ],
        sensacao: 'ativação forte nos glúteos.',
        evitar: 'dor lombar ou arquear demais as costas.',
        dica: 'Glúteos fortes = joelho protegido no agachamento.',
        pernas: false,
      },
      {
        id: 'elevacao-lateral-d2',
        nome: 'Elevação Lateral da Perna',
        objetivo: 'Fortalece glúteo médio',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de lado.',
          'Eleve a perna de cima 30 graus.',
          'Mantenha o pé apontando para frente.',
          'Segure 2 segundos no topo.',
          'Desça devagar.',
          'Faça 12 repetições por lado.',
        ],
        sensacao: 'queimação na lateral do quadril.',
        evitar: 'rodar o quadril ou elevar demais.',
        dica: 'Glúteo médio fraco = joelho cai para dentro no agachamento.',
        pernas: true,
      },
      {
        id: 'along-quadril-d2',
        nome: 'Alongamento de Quadril',
        objetivo: 'Melhora mobilidade do quadril',
        duracao: '3 min',
        instrucoes: [
          'Em pé, dê um passo grande para frente.',
          'Flexione o joelho da frente.',
          'Mantenha o joelho de trás estendido.',
          'Empurre o quadril para frente suavemente.',
          'Segure 30 segundos por lado.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento na frente do quadril.',
        evitar: 'arquear demais a lombar.',
        dica: 'Quadril móvel permite agachamento mais profundo e seguro.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Glúteo fraco causa dor no agachamento?',
      conteudo: [
        'Sim! Os glúteos têm papel fundamental no agachamento:',
        '• Glúteo máximo: gera força para subir',
        '• Glúteo médio: mantém joelho alinhado (evita que caia para dentro)',
        'Quando os glúteos estão fracos:',
        '→ Joelho cai para dentro (valgo dinâmico)',
        '→ Patela sofre pressão anormal',
        '→ Dor na frente do joelho',
        'Por isso estamos fortalecendo seus glúteos desde o início!',
      ],
    },
  },

  dia3: {
    exercicios: [
      {
        id: 'mini-agach-cadeira-d3',
        nome: 'Mini-agachamento com Cadeira',
        objetivo: 'Inicia padrão de agachamento seguro',
        duracao: '4 min',
        instrucoes: [
          'Fique em pé de frente para uma cadeira.',
          'Pés afastados na largura do quadril.',
          'Desça como se fosse sentar, mas pare antes de tocar.',
          'Desça apenas 20-30 graus.',
          'Suba devagar.',
          'Faça 10 repetições.',
        ],
        sensacao: 'ativação nas pernas, sem dor no joelho.',
        evitar: 'descer muito ou joelho ultrapassar muito a ponta do pé.',
        dica: 'Foco no controle, não na profundidade. Menos é mais no início.',
        pernas: false,
      },
      {
        id: 'mob-tornozelo-d3',
        nome: 'Mobilidade de Tornozelo',
        objetivo: 'Melhora dorsiflexão',
        duracao: '3 min',
        instrucoes: [
          'Em pé, coloque um pé à frente.',
          'Leve o joelho para frente sem tirar o calcanhar do chão.',
          'Faça 15 repetições lentas.',
          'Troque de perna.',
        ],
        sensacao: 'alongamento na panturrilha.',
        evitar: 'tirar o calcanhar do chão.',
        dica: 'Repita este exercício diariamente para melhorar seu agachamento.',
        pernas: true,
      },
      {
        id: 'along-quadriceps-d3',
        nome: 'Alongamento de Quadríceps',
        objetivo: 'Reduz tensão anterior',
        duracao: '3 min',
        instrucoes: [
          'Em pé, segure um pé atrás do corpo.',
          'Traga o calcanhar em direção ao glúteo.',
          'Mantenha joelhos alinhados.',
          'Segure 30 segundos por perna.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento na frente da coxa.',
        evitar: 'arquear a lombar ou perder o equilíbrio.',
        dica: 'Use uma parede para apoio se necessário.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'A importância da mobilidade no agachamento',
      conteudo: [
        'Mobilidade é a capacidade de mover uma articulação em toda sua amplitude.',
        'No agachamento, você precisa de mobilidade em:',
        '• Tornozelo: para o joelho ir para frente sem compensação',
        '• Quadril: para descer profundo sem arredondar as costas',
        '• Coluna torácica: para manter o tronco ereto',
        'Sem mobilidade adequada, seu corpo compensa de formas que causam dor.',
        'Por isso trabalhamos mobilidade todos os dias!',
      ],
    },
  },

  dia4: {
    exercicios: [
      {
        id: 'iso-gluteo-medio-d4',
        nome: 'Isometria de Glúteo Médio',
        objetivo: 'Fortalece estabilizador lateral do quadril',
        duracao: '4 min',
        instrucoes: [
          'Deite-se de lado.',
          'Eleve a perna de cima 30 graus.',
          'Segure a posição por 8 segundos.',
          'Desça devagar.',
          'Faça 8 repetições por lado.',
        ],
        sensacao: 'queimação intensa na lateral do quadril.',
        evitar: 'rodar o quadril ou compensar com o tronco.',
        dica: 'Este músculo é essencial para manter o joelho alinhado.',
        pernas: true,
      },
      {
        id: 'ponte-unilateral-d4',
        nome: 'Ponte Unilateral Leve',
        objetivo: 'Fortalece glúteos de forma avançada',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Estenda uma perna.',
          'Eleve o quadril usando apenas a perna apoiada.',
          'Segure 3 segundos.',
          'Faça 8 repetições por lado.',
        ],
        sensacao: 'ativação forte no glúteo da perna apoiada.',
        evitar: 'dor lombar ou perder o alinhamento.',
        dica: 'Se estiver difícil, volte para a ponte bilateral.',
        pernas: true,
      },
      {
        id: 'along-posterior-d4',
        nome: 'Alongamento Posterior',
        objetivo: 'Reduz tensão nos isquiotibiais',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve uma perna estendida.',
          'Segure atrás da coxa.',
          'Mantenha 30 segundos.',
          'Repita 3 vezes por perna.',
        ],
        sensacao: 'alongamento atrás da coxa.',
        evitar: 'dobrar o joelho.',
        dica: 'Respire profundamente para relaxar a musculatura.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'O que é valgo dinâmico?',
      conteudo: [
        'Valgo dinâmico é quando o joelho "cai para dentro" durante movimentos como agachamento.',
        'Isso acontece por:',
        '• Glúteo médio fraco',
        '• Falta de controle motor',
        '• Mobilidade limitada de tornozelo',
        'O valgo dinâmico aumenta muito a pressão na patela e pode causar dor.',
        'Estamos corrigindo isso fortalecendo glúteos e melhorando seu controle de movimento.',
        'Preste atenção: seus joelhos devem apontar na mesma direção dos pés!',
      ],
    },
  },

  dia5: {
    exercicios: [
      {
        id: 'agach-parede-d5',
        nome: 'Agachamento Assistido na Parede',
        objetivo: 'Fortalece pernas com suporte',
        duracao: '4 min',
        instrucoes: [
          'Encoste as costas na parede.',
          'Pés afastados na largura do quadril.',
          'Desça 30 graus (mini agachamento).',
          'Segure 5 segundos.',
          'Suba devagar.',
          'Faça 10 repetições.',
        ],
        sensacao: 'queimação nas pernas.',
        evitar: 'descer muito ou sentir dor no joelho.',
        dica: 'A parede ajuda a manter o tronco ereto e reduz compensações.',
        pernas: false,
      },
      {
        id: 'mob-tornozelo-elevacao-d5',
        nome: 'Mobilidade de Tornozelo com Elevação',
        objetivo: 'Melhora dorsiflexão avançada',
        duracao: '3 min',
        instrucoes: [
          'Coloque a ponta do pé em um degrau ou livro.',
          'Leve o joelho para frente.',
          'Mantenha o calcanhar no chão.',
          'Faça 12 repetições por perna.',
        ],
        sensacao: 'alongamento profundo na panturrilha.',
        evitar: 'tirar o calcanhar do chão.',
        dica: 'Esta variação aumenta a amplitude de movimento.',
        pernas: true,
      },
      {
        id: 'mob-quadril-d5',
        nome: 'Mobilidade de Quadril',
        objetivo: 'Prepara quadril para agachamento profundo',
        duracao: '3 min',
        instrucoes: [
          'Em pé, segure em algo para equilíbrio.',
          'Eleve um joelho e faça círculos com o quadril.',
          'Faça 10 círculos para cada lado.',
          'Troque de perna.',
        ],
        sensacao: 'mobilidade e soltura no quadril.',
        evitar: 'movimentos bruscos.',
        dica: 'Quadril móvel = agachamento mais profundo e seguro.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Controle vem antes da profundidade',
      conteudo: [
        'Muitas pessoas querem agachar profundo rápido demais.',
        'Mas a profundidade sem controle = lesão.',
        'Priorize sempre:',
        '1. Controle do movimento',
        '2. Alinhamento correto do joelho',
        '3. Ausência de dor',
        '4. Depois, gradualmente, aumente a profundidade',
        'Um agachamento raso bem feito é melhor que um profundo mal feito.',
        'Tenha paciência - você está construindo uma base sólida!',
      ],
    },
  },

  dia6: {
    exercicios: [
      {
        id: 'step-lateral-d6',
        nome: 'Step Lateral Leve',
        objetivo: 'Fortalece glúteo médio em movimento',
        duracao: '4 min',
        instrucoes: [
          'Em pé, dê um passo lateral.',
          'Flexione levemente o joelho da perna que recebe o peso.',
          'Volte para o centro.',
          'Alterne os lados.',
          'Faça 10 repetições para cada lado.',
        ],
        sensacao: 'ativação na lateral do quadril.',
        evitar: 'joelho cair para dentro.',
        dica: 'Mantenha o joelho alinhado com o pé durante todo o movimento.',
        pernas: true,
      },
      {
        id: 'iso-quadriceps-8s-d6',
        nome: 'Isometria de Quadríceps (8s)',
        objetivo: 'Aumenta resistência do quadríceps',
        duracao: '3 min',
        instrucoes: [
          'Sente-se com as costas apoiadas.',
          'Estenda uma perna.',
          'Contraia o quadríceps por 8 segundos.',
          'Relaxe por 3 segundos.',
          'Faça 8 repetições por perna.',
        ],
        sensacao: 'queimação intensa na frente da coxa.',
        evitar: 'prender a respiração.',
        dica: 'Respire normalmente durante a contração.',
        pernas: true,
      },
      {
        id: 'along-posterior-profundo-d6',
        nome: 'Alongamento Posterior Profundo',
        objetivo: 'Aumenta flexibilidade dos isquiotibiais',
        duracao: '3 min',
        instrucoes: [
          'Sentado no chão, pernas estendidas.',
          'Incline o tronco para frente.',
          'Tente alcançar os pés.',
          'Mantenha 40 segundos.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento forte atrás das coxas.',
        evitar: 'arredondar demais as costas.',
        dica: 'Vá até onde conseguir sem dor. A flexibilidade vem com o tempo.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Como o joelho se alinha no agachamento',
      conteudo: [
        'O alinhamento correto do joelho é fundamental para evitar dor.',
        'Regra de ouro: o joelho deve apontar na mesma direção do pé.',
        'Erros comuns:',
        '❌ Joelho cai para dentro (valgo)',
        '❌ Joelho vai muito além da ponta do pé',
        '❌ Pés viram para dentro',
        '✅ Correto:',
        '• Pés afastados na largura do quadril',
        '• Joelho alinhado com o segundo dedo do pé',
        '• Peso distribuído em todo o pé',
        'Pratique na frente do espelho para corrigir seu padrão!',
      ],
    },
  },

  dia7: {
    exercicios: [
      {
        id: 'mob-geral-d7',
        nome: 'Mobilidade Geral',
        objetivo: 'Prepara corpo para movimento',
        duracao: '4 min',
        instrucoes: [
          'Rotação de tornozelo: 10 vezes cada lado.',
          'Círculos de quadril: 10 vezes cada lado.',
          'Flexão e extensão de joelho: 15 vezes.',
          'Rotação de tronco: 10 vezes cada lado.',
        ],
        sensacao: 'corpo mais solto e preparado.',
        evitar: 'movimentos bruscos.',
        dica: 'Faça esta sequência antes de qualquer treino.',
        pernas: false,
      },
      {
        id: 'mini-agach-20-25-d7',
        nome: 'Mini-agachamento 20–25°',
        objetivo: 'Consolida padrão de movimento',
        duracao: '3 min',
        instrucoes: [
          'Pés afastados na largura do quadril.',
          'Desça apenas 20-25 graus.',
          'Mantenha joelhos alinhados.',
          'Suba com controle.',
          'Faça 12 repetições.',
        ],
        sensacao: 'ativação nas pernas sem dor.',
        evitar: 'descer muito ou perder o alinhamento.',
        dica: 'Você está construindo um padrão seguro. Continue assim!',
        pernas: false,
      },
      {
        id: 'along-global-d7',
        nome: 'Alongamento Global',
        objetivo: 'Relaxa todo o corpo',
        duracao: '3 min',
        instrucoes: [
          'Alongamento posterior: 30 segundos cada perna.',
          'Alongamento de quadríceps: 30 segundos cada perna.',
          'Alongamento de quadril: 30 segundos cada lado.',
        ],
        sensacao: 'relaxamento geral.',
        evitar: 'forçar demais.',
        dica: 'Respire profundamente e celebre sua primeira semana!',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Semana 1 — o que melhorou?',
      conteudo: [
        'Parabéns por completar a primeira semana! 🎉',
        'Você já começou a:',
        '✅ Melhorar mobilidade de tornozelo e quadril',
        '✅ Ativar glúteos e quadríceps',
        '✅ Aprender o padrão correto de agachamento',
        '✅ Entender o que causa sua dor',
        'Na próxima semana, vamos:',
        '• Aumentar a profundidade do agachamento',
        '• Fortalecer ainda mais glúteos',
        '• Corrigir padrões de movimento',
        'Continue assim - você está no caminho certo!',
      ],
    },
  },

  // ========== FASE 2 - Dias 8 a 14 ==========
  dia8: {
    exercicios: [
      {
        id: 'agach-banda-d8',
        nome: 'Agachamento com Banda',
        objetivo: 'Corrige valgo dinâmico',
        duracao: '4 min',
        instrucoes: [
          'Coloque uma faixa elástica acima dos joelhos.',
          'Pés afastados na largura do quadril.',
          'Agache 30-40 graus empurrando os joelhos para fora contra a banda.',
          'Suba com controle.',
          'Faça 12 repetições.',
        ],
        sensacao: 'ativação forte nos glúteos.',
        evitar: 'deixar os joelhos caírem para dentro.',
        dica: 'A banda força você a ativar o glúteo médio corretamente.',
        pernas: false,
      },
      {
        id: 'mob-tornozelo-avanco-d8',
        nome: 'Mobilidade de Tornozelo com Avanço',
        objetivo: 'Melhora dorsiflexão dinâmica',
        duracao: '3 min',
        instrucoes: [
          'Em pé, dê um passo grande para frente.',
          'Leve o joelho da frente para frente sem tirar o calcanhar.',
          'Volte e repita.',
          'Faça 15 repetições por perna.',
        ],
        sensacao: 'alongamento na panturrilha.',
        evitar: 'tirar o calcanhar do chão.',
        dica: 'Este exercício simula o movimento do agachamento.',
        pernas: true,
      },
      {
        id: 'ponte-pausa-d8',
        nome: 'Ponte com Pausa',
        objetivo: 'Aumenta resistência dos glúteos',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve o quadril.',
          'Segure no topo por 5 segundos.',
          'Desça devagar.',
          'Faça 12 repetições.',
        ],
        sensacao: 'queimação nos glúteos.',
        evitar: 'dor lombar.',
        dica: 'A pausa aumenta o tempo sob tensão e fortalece mais.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Como manter o joelho alinhado?',
      conteudo: [
        'Manter o joelho alinhado durante o agachamento é essencial para evitar dor.',
        'Dicas práticas:',
        '1. Pense em "empurrar o chão para fora" com os pés',
        '2. Imagine que está abrindo o chão com as pernas',
        '3. Mantenha o peso no meio do pé (não na ponta)',
        '4. Olhe para frente, não para baixo',
        '5. Use uma banda elástica para treinar o padrão correto',
        'Com prática, o movimento correto se torna automático!',
      ],
    },
  },

  dia9: {
    exercicios: [
      {
        id: 'agach-cadeira-d9',
        nome: 'Agachamento até a Cadeira',
        objetivo: 'Aumenta profundidade com segurança',
        duracao: '4 min',
        instrucoes: [
          'Fique de costas para uma cadeira.',
          'Desça até quase tocar a cadeira.',
          'Suba antes de sentar completamente.',
          'Faça 10 repetições.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'sentar completamente ou perder o controle.',
        dica: 'A cadeira dá segurança para você descer mais.',
        pernas: false,
      },
      {
        id: 'elevacao-lateral-lenta-d9',
        nome: 'Elevação Lateral Lenta',
        objetivo: 'Fortalece glúteo médio com controle',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de lado.',
          'Eleve a perna de cima lentamente (3 segundos).',
          'Desça lentamente (3 segundos).',
          'Faça 10 repetições por lado.',
        ],
        sensacao: 'queimação intensa na lateral do quadril.',
        evitar: 'movimentos rápidos ou compensações.',
        dica: 'Lento = mais difícil = mais efetivo.',
        pernas: true,
      },
      {
        id: 'along-posterior-d9',
        nome: 'Alongamento Posterior',
        objetivo: 'Mantém flexibilidade',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve uma perna estendida.',
          'Segure por 30 segundos.',
          'Repita 3 vezes por perna.',
        ],
        sensacao: 'alongamento atrás da coxa.',
        evitar: 'dobrar o joelho.',
        dica: 'Flexibilidade é essencial para agachamento profundo.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Pé firme, joelho estável',
      conteudo: [
        'A estabilidade do joelho começa no pé!',
        'Distribuição correta do peso:',
        '• 1/3 no calcanhar',
        '• 1/3 na base dos dedos',
        '• 1/3 na lateral externa',
        'Erros comuns:',
        '❌ Peso só no calcanhar → joelho vai muito para frente',
        '❌ Peso só na ponta → instabilidade',
        '❌ Pé virando para dentro → valgo dinâmico',
        '✅ Correto: peso distribuído, pé firme no chão, dedos relaxados.',
        'Pratique sentir o peso em todo o pé durante o agachamento!',
      ],
    },
  },

  dia10: {
    exercicios: [
      {
        id: 'step-up-baixo-d10',
        nome: 'Step-up Baixo',
        objetivo: 'Fortalece pernas em movimento funcional',
        duracao: '4 min',
        instrucoes: [
          'Use um degrau de 15-20 cm.',
          'Suba com uma perna.',
          'Desça com controle.',
          'Faça 10 repetições por perna.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'empurrar com a perna de baixo.',
        dica: 'Use a perna de cima para subir, não a de baixo para empurrar.',
        pernas: true,
      },
      {
        id: 'abducao-faixa-d10',
        nome: 'Abdução com Faixa',
        objetivo: 'Fortalece glúteo médio com resistência',
        duracao: '3 min',
        instrucoes: [
          'Coloque uma faixa acima dos joelhos.',
          'Em pé, afaste uma perna lateralmente.',
          'Mantenha o tronco ereto.',
          'Faça 12 repetições por lado.',
        ],
        sensacao: 'queimação na lateral do quadril.',
        evitar: 'inclinar o tronco.',
        dica: 'A resistência da faixa aumenta a ativação muscular.',
        pernas: true,
      },
      {
        id: 'along-quadriceps-d10',
        nome: 'Alongamento de Quadríceps',
        objetivo: 'Reduz tensão anterior',
        duracao: '3 min',
        instrucoes: [
          'Em pé, segure um pé atrás.',
          'Traga o calcanhar ao glúteo.',
          'Segure 30 segundos por perna.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento na frente da coxa.',
        evitar: 'arquear a lombar.',
        dica: 'Mantenha o core ativado durante o alongamento.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Força lateral protege a patela',
      conteudo: [
        'O glúteo médio é o músculo mais importante para proteger seu joelho.',
        'Por quê?',
        '• Ele mantém o joelho alinhado durante movimentos',
        '• Evita que o joelho caia para dentro',
        '• Reduz pressão anormal na patela',
        'Quando o glúteo médio está fraco:',
        '→ Joelho cai para dentro',
        '→ Patela sofre pressão lateral',
        '→ Dor na frente do joelho',
        'Continue fortalecendo este músculo - ele é seu melhor aliado!',
      ],
    },
  },

  dia11: {
    exercicios: [
      {
        id: 'agach-parcial-30-40-d11',
        nome: 'Agachamento Parcial 30–40º',
        objetivo: 'Aumenta profundidade progressivamente',
        duracao: '4 min',
        instrucoes: [
          'Pés afastados na largura do quadril.',
          'Desça 30-40 graus (um pouco mais que antes).',
          'Mantenha joelhos alinhados.',
          'Suba com controle.',
          'Faça 10 repetições.',
        ],
        sensacao: 'ativação nas pernas sem dor.',
        evitar: 'joelho cair para dentro ou dor aguda.',
        dica: 'Se sentir dor, volte para amplitude menor.',
        pernas: false,
      },
      {
        id: 'ponte-unilateral-d11',
        nome: 'Ponte Unilateral',
        objetivo: 'Fortalece glúteos de forma avançada',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Estenda uma perna.',
          'Eleve o quadril com a perna apoiada.',
          'Segure 3 segundos.',
          'Faça 10 repetições por lado.',
        ],
        sensacao: 'ativação forte no glúteo.',
        evitar: 'dor lombar ou perder o alinhamento.',
        dica: 'Este exercício é desafiador - vá no seu ritmo.',
        pernas: true,
      },
      {
        id: 'mob-quadril-d11',
        nome: 'Mobilidade de Quadril',
        objetivo: 'Prepara para agachamento mais profundo',
        duracao: '3 min',
        instrucoes: [
          'Em pé, segure em algo.',
          'Faça círculos com o quadril.',
          'Faça 10 círculos cada lado.',
          'Troque de perna.',
        ],
        sensacao: 'mobilidade no quadril.',
        evitar: 'movimentos bruscos.',
        dica: 'Quanto mais móvel o quadril, mais profundo você agacha.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Desaceleração e controle',
      conteudo: [
        'A fase de descida do agachamento é tão importante quanto a subida.',
        'Descer rápido = perda de controle = risco de lesão.',
        'Descer devagar (fase excêntrica):',
        '✅ Fortalece mais os músculos',
        '✅ Melhora o controle motor',
        '✅ Reduz impacto no joelho',
        '✅ Previne lesões',
        'Dica prática: conte 3 segundos na descida.',
        'Controle na descida = joelho protegido!',
      ],
    },
  },

  dia12: {
    exercicios: [
      {
        id: 'agach-isometrico-15s-d12',
        nome: 'Agachamento Isométrico 15s',
        objetivo: 'Aumenta resistência muscular',
        duracao: '4 min',
        instrucoes: [
          'Desça até 30-40 graus.',
          'Segure a posição por 15 segundos.',
          'Suba e descanse 10 segundos.',
          'Faça 5 repetições.',
        ],
        sensacao: 'queimação intensa nas pernas.',
        evitar: 'prender a respiração ou sentir dor no joelho.',
        dica: 'Respire normalmente durante a contração.',
        pernas: false,
      },
      {
        id: 'ext-joelho-faixa-d12',
        nome: 'Extensão de Joelho com Faixa',
        objetivo: 'Fortalece quadríceps com resistência',
        duracao: '3 min',
        instrucoes: [
          'Sentado, coloque uma faixa no tornozelo.',
          'Estenda o joelho contra a resistência.',
          'Segure 2 segundos.',
          'Volte devagar.',
          'Faça 12 repetições por perna.',
        ],
        sensacao: 'queimação no quadríceps.',
        evitar: 'movimentos bruscos.',
        dica: 'Controle o movimento na volta (fase excêntrica).',
        pernas: true,
      },
      {
        id: 'along-posterior-profundo-d12',
        nome: 'Alongamento Posterior Profundo',
        objetivo: 'Aumenta flexibilidade',
        duracao: '3 min',
        instrucoes: [
          'Sentado, pernas estendidas.',
          'Incline o tronco para frente.',
          'Mantenha 40 segundos.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento forte atrás das coxas.',
        evitar: 'arredondar demais as costas.',
        dica: 'A flexibilidade melhora com consistência.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Por que dói na frente do joelho?',
      conteudo: [
        'A dor na frente do joelho (região da patela) tem causas específicas:',
        '1. Pressão excessiva na patela',
        '2. Desalinhamento patelofemoral',
        '3. Fraqueza do quadríceps',
        '4. Sobrecarga repetitiva',
        'O que estamos fazendo para resolver:',
        '✅ Fortalecendo quadríceps e glúteos',
        '✅ Melhorando alinhamento do joelho',
        '✅ Aumentando mobilidade',
        '✅ Corrigindo padrão de movimento',
        'Continue - você está tratando a causa, não só o sintoma!',
      ],
    },
  },

  dia13: {
    exercicios: [
      {
        id: 'step-lateral-medio-d13',
        nome: 'Step Lateral Médio',
        objetivo: 'Fortalece glúteo médio em movimento',
        duracao: '4 min',
        instrucoes: [
          'Dê um passo lateral maior.',
          'Flexione o joelho da perna que recebe o peso.',
          'Empurre o chão para voltar.',
          'Alterne os lados.',
          'Faça 12 repetições cada lado.',
        ],
        sensacao: 'ativação forte na lateral do quadril.',
        evitar: 'joelho cair para dentro.',
        dica: 'Mantenha o joelho alinhado com o pé.',
        pernas: true,
      },
      {
        id: 'elevacao-perna-estendida-d13',
        nome: 'Elevação de Perna Estendida',
        objetivo: 'Fortalece quadríceps sem flexionar joelho',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Flexione uma perna.',
          'Eleve a outra perna estendida.',
          'Segure 3 segundos.',
          'Faça 12 repetições por perna.',
        ],
        sensacao: 'ativação no quadríceps.',
        evitar: 'dobrar o joelho da perna elevada.',
        dica: 'Este exercício é seguro para quem tem dor ao flexionar.',
        pernas: true,
      },
      {
        id: 'mob-tornozelo-d13',
        nome: 'Mobilidade de Tornozelo',
        objetivo: 'Mantém dorsiflexão',
        duracao: '3 min',
        instrucoes: [
          'Em pé, pé à frente.',
          'Leve o joelho para frente.',
          'Faça 15 repetições por perna.',
        ],
        sensacao: 'alongamento na panturrilha.',
        evitar: 'tirar o calcanhar do chão.',
        dica: 'Faça este exercício diariamente.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Biomecânica correta do agachamento',
      conteudo: [
        'Entenda a biomecânica para agachar sem dor:',
        '1. Início: quadril vai para trás (como sentar)',
        '2. Descida: joelhos flexionam e vão para frente',
        '3. Profundidade: quadril desce mantendo costas retas',
        '4. Subida: empurre o chão, ative glúteos',
        'Pontos-chave:',
        '• Peso no meio do pé',
        '• Joelhos alinhados com os pés',
        '• Tronco ereto (não arredonde as costas)',
        '• Olhar para frente',
        'Pratique na frente do espelho!',
      ],
    },
  },

  dia14: {
    exercicios: [
      {
        id: 'agach-peso-corporal-d14',
        nome: 'Agachamento com Peso Corporal (parcial)',
        objetivo: 'Consolida padrão de movimento',
        duracao: '4 min',
        instrucoes: [
          'Pés afastados na largura do quadril.',
          'Desça 40-50 graus (se sem dor).',
          'Mantenha controle total.',
          'Suba empurrando o chão.',
          'Faça 12 repetições.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'perder o alinhamento ou sentir dor.',
        dica: 'Você evoluiu muito! Compare com a semana 1.',
        pernas: false,
      },
      {
        id: 'ponte-avancada-d14',
        nome: 'Ponte Avançada',
        objetivo: 'Fortalece glúteos ao máximo',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve o quadril.',
          'Segure 8 segundos no topo.',
          'Desça devagar.',
          'Faça 10 repetições.',
        ],
        sensacao: 'queimação forte nos glúteos.',
        evitar: 'dor lombar.',
        dica: 'Glúteos fortes = joelho protegido para sempre.',
        pernas: false,
      },
      {
        id: 'along-global-d14',
        nome: 'Alongamento Global',
        objetivo: 'Relaxa todo o corpo',
        duracao: '3 min',
        instrucoes: [
          'Alongamento posterior: 30s cada perna.',
          'Alongamento de quadríceps: 30s cada perna.',
          'Alongamento de quadril: 30s cada lado.',
        ],
        sensacao: 'relaxamento geral.',
        evitar: 'forçar demais.',
        dica: 'Celebre sua evolução - você está incrível!',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Semana 2 — reprogramando o movimento',
      conteudo: [
        'Parabéns por completar a segunda semana! 🎉',
        'Você já conseguiu:',
        '✅ Aumentar a profundidade do agachamento',
        '✅ Fortalecer glúteos e quadríceps significativamente',
        '✅ Corrigir padrões de movimento',
        '✅ Melhorar controle e estabilidade',
        'Na próxima semana (fase final):',
        '• Vamos aumentar ainda mais a profundidade',
        '• Trabalhar confiança no movimento',
        '• Preparar você para agachar sem medo',
        'Você está quase lá - continue firme!',
      ],
    },
  },

  // Importar dados da Fase 3 (dias 15-21)
  ...dadosFase3,
};

// Função auxiliar para pegar dados de um dia específico
export function getDadosDia(dia: number): DadosDia | null {
  const chave = `dia${dia}`;
  return dadosTrilha[chave] || null;
}
