// Dados da Fase 3 (dias 15-21) da trilha Dor ao Agachar
import { DadosDia } from './dados';

export const dadosFase3: Record<string, DadosDia> = {
  // ========== FASE 3 - Dias 15 a 21 ==========
  dia15: {
    exercicios: [
      {
        id: 'agach-foco-quadril-d15',
        nome: 'Agachamento Focado no Quadril (sentar para trás)',
        objetivo: 'Ativa glúteos e reduz sobrecarga no joelho',
        duracao: '5 min',
        instrucoes: [
          'Pés afastados na largura do quadril.',
          'Inicie o movimento empurrando o quadril para trás.',
          'Imagine que vai sentar em uma cadeira atrás de você.',
          'Desça 40-50 graus mantendo o tronco inclinado.',
          'Suba empurrando o chão com os pés.',
          'Faça 12 repetições.',
        ],
        sensacao: 'ativação forte nos glúteos e posterior.',
        evitar: 'joelhos irem muito para frente ou perder o equilíbrio.',
        dica: 'Quadril para trás primeiro = menos pressão no joelho.',
        pernas: false,
      },
      {
        id: 'gluteo-medio-faixa-media-d15',
        nome: 'Glúteo Médio com Faixa (média)',
        objetivo: 'Fortalece estabilizador lateral',
        duracao: '3 min',
        instrucoes: [
          'Coloque faixa acima dos joelhos.',
          'Em pé, afaste uma perna lateralmente.',
          'Mantenha resistência constante.',
          'Faça 15 repetições por lado.',
        ],
        sensacao: 'queimação intensa na lateral do quadril.',
        evitar: 'inclinar o tronco ou compensar.',
        dica: 'Resistência maior = glúteo mais forte.',
        pernas: true,
      },
      {
        id: 'mob-quadril-d15',
        nome: 'Mobilidade de Quadril',
        objetivo: 'Prepara para agachamento profundo',
        duracao: '3 min',
        instrucoes: [
          'Em pé, segure em algo.',
          'Faça círculos amplos com o quadril.',
          'Faça 12 círculos cada lado.',
        ],
        sensacao: 'mobilidade e soltura no quadril.',
        evitar: 'movimentos bruscos.',
        dica: 'Quadril móvel = agachamento mais profundo e seguro.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Como ativar o glúteo no agachamento',
      conteudo: [
        'Muitas pessoas agacham usando principalmente quadríceps, sobrecarregando o joelho.',
        'Para ativar os glúteos corretamente:',
        '1. Inicie empurrando o quadril para trás',
        '2. Pense em "sentar" em vez de "descer"',
        '3. Mantenha o peso no calcanhar e meio do pé',
        '4. Na subida, aperte os glúteos conscientemente',
        'Dica mental: "empurre o chão para baixo" ao subir.',
        'Glúteos ativados = joelho protegido!',
      ],
    },
  },

  dia16: {
    exercicios: [
      {
        id: 'agach-40-60-d16',
        nome: 'Agachamento 40–60° (se sem dor)',
        objetivo: 'Aumenta profundidade progressivamente',
        duracao: '5 min',
        instrucoes: [
          'Pés afastados na largura do quadril.',
          'Desça até 40-60 graus (coxa quase paralela ao chão).',
          'APENAS se não sentir dor.',
          'Mantenha controle total.',
          'Suba empurrando o chão.',
          'Faça 10 repetições.',
        ],
        sensacao: 'ativação forte em toda a perna.',
        evitar: 'forçar se sentir dor - volte para amplitude menor.',
        dica: 'Profundidade vem com o tempo. Não force.',
        pernas: false,
      },
      {
        id: 'step-alternado-d16',
        nome: 'Step Alternado',
        objetivo: 'Fortalece pernas de forma funcional',
        duracao: '3 min',
        instrucoes: [
          'Use um degrau de 20 cm.',
          'Suba alternando as pernas.',
          'Mantenha controle.',
          'Faça 10 repetições cada perna.',
        ],
        sensacao: 'ativação em toda a perna.',
        evitar: 'subir rápido ou perder o equilíbrio.',
        dica: 'Este movimento simula subir escadas.',
        pernas: true,
      },
      {
        id: 'along-posterior-d16',
        nome: 'Alongamento Posterior',
        objetivo: 'Mantém flexibilidade',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve uma perna estendida.',
          'Segure 30 segundos.',
          'Repita 3 vezes por perna.',
        ],
        sensacao: 'alongamento atrás da coxa.',
        evitar: 'dobrar o joelho.',
        dica: 'Flexibilidade é essencial para agachamento profundo.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Ganhando profundidade sem dor',
      conteudo: [
        'Aumentar a profundidade do agachamento requer:',
        '1. Mobilidade adequada (tornozelo + quadril)',
        '2. Força suficiente (glúteos + quadríceps)',
        '3. Controle motor (padrão correto)',
        '4. Ausência de dor',
        'Sinais de que você está pronto para descer mais:',
        '✅ Sem dor na amplitude atual',
        '✅ Controle total do movimento',
        '✅ Joelhos alinhados',
        '✅ Mobilidade adequada',
        'Se ainda não está pronto, não tem problema! Continue praticando.',
      ],
    },
  },

  dia17: {
    exercicios: [
      {
        id: 'agach-pausa-meio-d17',
        nome: 'Agachamento com Pausa no Meio',
        objetivo: 'Aumenta controle e força excêntrica',
        duracao: '5 min',
        instrucoes: [
          'Desça até 40 graus.',
          'Pause por 3 segundos no meio.',
          'Continue descendo mais 10-20 graus.',
          'Suba com controle.',
          'Faça 8 repetições.',
        ],
        sensacao: 'queimação intensa nas pernas.',
        evitar: 'perder o equilíbrio ou sentir dor.',
        dica: 'A pausa aumenta muito a dificuldade e o ganho de força.',
        pernas: false,
      },
      {
        id: 'ponte-unilateral-avancada-d17',
        nome: 'Ponte Unilateral Avançada',
        objetivo: 'Fortalece glúteos ao máximo',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Estenda uma perna.',
          'Eleve o quadril alto.',
          'Segure 5 segundos.',
          'Faça 10 repetições por lado.',
        ],
        sensacao: 'ativação máxima no glúteo.',
        evitar: 'dor lombar ou perder o alinhamento.',
        dica: 'Este é um dos exercícios mais efetivos para glúteos.',
        pernas: true,
      },
      {
        id: 'mob-tornozelo-d17',
        nome: 'Mobilidade de Tornozelo',
        objetivo: 'Mantém dorsiflexão',
        duracao: '3 min',
        instrucoes: [
          'Em pé, pé à frente.',
          'Leve o joelho para frente.',
          'Faça 15 repetições por perna.',
        ],
        sensacao: 'alongamento na panturrilha.',
        evitar: 'tirar o calcanhar do chão.',
        dica: 'Mobilidade de tornozelo nunca é demais.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Força excêntrica no agachamento',
      conteudo: [
        'Força excêntrica = força durante o alongamento do músculo (fase de descida).',
        'Por que é importante?',
        '• Protege articulações',
        '• Previne lesões',
        '• Aumenta força geral',
        '• Melhora controle motor',
        'Como treinar:',
        '→ Desça devagar (3-4 segundos)',
        '→ Use pausas no meio do movimento',
        '→ Controle total em toda amplitude',
        'Resultado: joelho mais forte e protegido!',
      ],
    },
  },

  dia18: {
    exercicios: [
      {
        id: 'agach-parcial-banda-d18',
        nome: 'Agachamento Parcial com Banda',
        objetivo: 'Corrige valgo e fortalece',
        duracao: '5 min',
        instrucoes: [
          'Coloque banda acima dos joelhos.',
          'Desça 40-50 graus.',
          'Empurre joelhos para fora contra a banda.',
          'Mantenha alinhamento perfeito.',
          'Faça 12 repetições.',
        ],
        sensacao: 'ativação forte nos glúteos.',
        evitar: 'deixar joelhos caírem para dentro.',
        dica: 'A banda força o padrão correto de movimento.',
        pernas: false,
      },
      {
        id: 'abducao-pausa-d18',
        nome: 'Abdução com Pausa',
        objetivo: 'Aumenta resistência do glúteo médio',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de lado.',
          'Eleve a perna.',
          'Pause 5 segundos no topo.',
          'Desça devagar.',
          'Faça 10 repetições por lado.',
        ],
        sensacao: 'queimação intensa na lateral do quadril.',
        evitar: 'compensar com o tronco.',
        dica: 'A pausa aumenta muito a efetividade.',
        pernas: true,
      },
      {
        id: 'along-quadriceps-d18',
        nome: 'Alongamento de Quadríceps',
        objetivo: 'Reduz tensão anterior',
        duracao: '3 min',
        instrucoes: [
          'Em pé, segure um pé atrás.',
          'Traga o calcanhar ao glúteo.',
          'Segure 30 segundos por perna.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento na frente da coxa.',
        evitar: 'arquear a lombar.',
        dica: 'Mantenha o core ativado.',
        pernas: true,
      },
    ],
    aula: {
      titulo: 'Joelho entrando: como corrigir',
      conteudo: [
        'O joelho caindo para dentro (valgo dinâmico) é o erro mais comum no agachamento.',
        'Como corrigir:',
        '1. Fortaleça glúteo médio (você já está fazendo!)',
        '2. Use banda elástica para treinar o padrão correto',
        '3. Pense em "empurrar o chão para fora"',
        '4. Grave-se agachando e observe',
        '5. Pratique na frente do espelho',
        'Dica mental: imagine que está abrindo o chão com os pés.',
        'Com prática, o movimento correto se torna automático!',
      ],
    },
  },

  dia19: {
    exercicios: [
      {
        id: 'step-alto-d19',
        nome: 'Step Alto',
        objetivo: 'Fortalece pernas em amplitude maior',
        duracao: '5 min',
        instrucoes: [
          'Use um degrau de 25-30 cm.',
          'Suba com controle.',
          'Desça devagar.',
          'Faça 10 repetições por perna.',
        ],
        sensacao: 'ativação forte em toda a perna.',
        evitar: 'subir rápido ou perder o controle.',
        dica: 'Se estiver difícil, use degrau mais baixo.',
        pernas: true,
      },
      {
        id: 'ext-faixa-media-d19',
        nome: 'Extensão com Faixa Média',
        objetivo: 'Fortalece quadríceps com resistência',
        duracao: '3 min',
        instrucoes: [
          'Sentado, faixa no tornozelo.',
          'Estenda o joelho contra resistência.',
          'Segure 3 segundos.',
          'Faça 12 repetições por perna.',
        ],
        sensacao: 'queimação no quadríceps.',
        evitar: 'movimentos bruscos.',
        dica: 'Controle o movimento na volta.',
        pernas: true,
      },
      {
        id: 'along-posterior-profundo-d19',
        nome: 'Alongamento Posterior Profundo',
        objetivo: 'Maximiza flexibilidade',
        duracao: '3 min',
        instrucoes: [
          'Sentado, pernas estendidas.',
          'Incline o tronco para frente.',
          'Mantenha 45 segundos.',
          'Repita 2 vezes.',
        ],
        sensacao: 'alongamento forte atrás das coxas.',
        evitar: 'arredondar demais as costas.',
        dica: 'Flexibilidade máxima = agachamento profundo.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Agachamento sem medo',
      conteudo: [
        'Muitas pessoas desenvolvem medo de agachar por causa da dor.',
        'Como superar:',
        '1. Entenda que você está mais forte agora',
        '2. Confie no processo - você evoluiu muito',
        '3. Comece com amplitude confortável',
        '4. Aumente progressivamente',
        '5. Celebre cada conquista',
        'Lembre-se:',
        '✅ Você fortaleceu glúteos e quadríceps',
        '✅ Melhorou mobilidade',
        '✅ Corrigiu padrão de movimento',
        'Você está pronto para agachar com confiança!',
      ],
    },
  },

  dia20: {
    exercicios: [
      {
        id: 'agach-60-70-d20',
        nome: 'Agachamento 60–70°',
        objetivo: 'Atinge profundidade funcional',
        duracao: '5 min',
        instrucoes: [
          'Pés afastados na largura do quadril.',
          'Desça até 60-70 graus (coxa quase paralela).',
          'APENAS se não sentir dor.',
          'Mantenha controle perfeito.',
          'Suba empurrando o chão.',
          'Faça 10 repetições.',
        ],
        sensacao: 'ativação máxima em toda a perna.',
        evitar: 'forçar se sentir dor.',
        dica: 'Esta é uma profundidade funcional excelente!',
        pernas: false,
      },
      {
        id: 'mob-ativa-d20',
        nome: 'Mobilidade Ativa',
        objetivo: 'Prepara corpo para movimento',
        duracao: '3 min',
        instrucoes: [
          'Rotação de tornozelo: 10 vezes.',
          'Círculos de quadril: 10 vezes.',
          'Agachamento leve: 5 vezes.',
        ],
        sensacao: 'corpo preparado e aquecido.',
        evitar: 'movimentos bruscos.',
        dica: 'Faça esta sequência antes de qualquer atividade.',
        pernas: false,
      },
      {
        id: 'panturrilha-d20',
        nome: 'Panturrilha',
        objetivo: 'Fortalece panturrilha',
        duracao: '3 min',
        instrucoes: [
          'Em pé, eleve os calcanhares.',
          'Suba na ponta dos pés.',
          'Desça devagar.',
          'Faça 15 repetições.',
        ],
        sensacao: 'queimação na panturrilha.',
        evitar: 'perder o equilíbrio.',
        dica: 'Panturrilha forte ajuda na estabilidade do tornozelo.',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Preparando seu joelho para qualquer movimento',
      conteudo: [
        'Você está quase no final da trilha!',
        'Seu joelho agora está preparado para:',
        '✅ Agachar com profundidade funcional',
        '✅ Subir e descer escadas',
        '✅ Caminhar longas distâncias',
        '✅ Praticar atividades físicas',
        'Como manter os resultados:',
        '• Continue fortalecendo glúteos 2-3x/semana',
        '• Mantenha mobilidade de tornozelo e quadril',
        '• Pratique o padrão correto de agachamento',
        '• Ouça seu corpo',
        'Você conquistou um joelho forte e saudável!',
      ],
    },
  },

  dia21: {
    exercicios: [
      {
        id: 'agach-completo-leve-d21',
        nome: 'Agachamento Completo Leve',
        objetivo: 'Celebra sua evolução',
        duracao: '5 min',
        instrucoes: [
          'Pés afastados na largura do quadril.',
          'Desça até onde for confortável.',
          'Mantenha controle perfeito.',
          'Suba com força.',
          'Faça 10 repetições.',
        ],
        sensacao: 'confiança e força.',
        evitar: 'forçar além do confortável.',
        dica: 'Compare com o Dia 1 - você evoluiu muito!',
        pernas: false,
      },
      {
        id: 'ponte-avancada-pausa-d21',
        nome: 'Ponte Avançada com Pausa',
        objetivo: 'Fortalece glúteos ao máximo',
        duracao: '3 min',
        instrucoes: [
          'Deite-se de costas.',
          'Eleve o quadril.',
          'Segure 10 segundos no topo.',
          'Desça devagar.',
          'Faça 8 repetições.',
        ],
        sensacao: 'queimação máxima nos glúteos.',
        evitar: 'dor lombar.',
        dica: 'Glúteos fortes = joelho protegido para sempre.',
        pernas: false,
      },
      {
        id: 'along-global-d21',
        nome: 'Alongamento Global',
        objetivo: 'Relaxa e celebra',
        duracao: '3 min',
        instrucoes: [
          'Alongamento posterior: 30s cada perna.',
          'Alongamento de quadríceps: 30s cada perna.',
          'Alongamento de quadril: 30s cada lado.',
          'Respire profundamente e celebre!',
        ],
        sensacao: 'relaxamento e gratidão.',
        evitar: 'forçar demais.',
        dica: 'Você completou a trilha! Parabéns! 🎉',
        pernas: false,
      },
    ],
    aula: {
      titulo: 'Como manter seu agachamento saudável para sempre',
      conteudo: [
        'Parabéns por completar a trilha de 21 dias! 🎉',
        'Você conquistou:',
        '✅ Mobilidade de tornozelo e quadril',
        '✅ Glúteos e quadríceps fortes',
        '✅ Padrão correto de agachamento',
        '✅ Confiança para se movimentar sem dor',
        'Para manter os resultados:',
        '1. Continue fortalecendo glúteos 2-3x/semana',
        '2. Pratique mobilidade diariamente (5 min)',
        '3. Agache com técnica correta sempre',
        '4. Ouça seu corpo e respeite seus limites',
        '5. Se a dor voltar, retorne aos exercícios básicos',
        'Você tem agora as ferramentas para um joelho saudável para sempre!',
      ],
    },
  },
};
