export const dadosTrilhaEscadas = {
  nome: 'Dor ao Subir e Descer Escadas',
  descricao: 'Programa de 21 dias para recuperar sua capacidade de subir e descer escadas sem dor',
  totalDias: 21,
  fases: [
    {
      numero: 1,
      nome: 'Redução de Dor + Controle Inicial',
      descricao: 'Reduzir dor, ativar musculatura protetora e iniciar controle de movimento',
      dias: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      numero: 2,
      nome: 'Força + Estabilidade Funcional',
      descricao: 'Fortalecer quadríceps e glúteos, melhorar controle excêntrico',
      dias: [8, 9, 10, 11, 12, 13, 14],
    },
    {
      numero: 3,
      nome: 'Função Real',
      descricao: 'Retorno ao movimento funcional de escadas com confiança e segurança',
      dias: [15, 16, 17, 18, 19, 20, 21],
    },
  ],
  dias: {
    1: {
      titulo: 'Dia 1 — Dor ao Subir e Descer Escadas',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Melhora dorsiflexão e prepara o tornozelo para o degrau',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Coloque um pé à frente, joelho levemente flexionado',
            'Empurre o joelho para frente, mantendo o calcanhar no chão',
            'Segure por 5 segundos e retorne',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir um alongamento suave na parte de trás da panturrilha e tornozelo, sem dor no joelho.',
          evitar: 'Não force o movimento se sentir dor aguda. Não tire o calcanhar do chão.',
          dica: 'A mobilidade do tornozelo é essencial para distribuir bem a carga ao subir e descer escadas.',
        },
        {
          titulo: 'Isometria de Quadríceps',
          subtitulo: 'Ativa o músculo da coxa sem sobrecarregar a patela',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira com as costas retas',
            'Estenda uma perna à frente, mantendo-a reta',
            'Contraia o músculo da coxa (quadríceps) por 8 segundos',
            'Relaxe por 3 segundos',
            'Faça 8 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da frente da coxa trabalhando intensamente, sem dor no joelho.',
          evitar: 'Não prenda a respiração. Não force se sentir dor na patela.',
          dica: 'Este exercício fortalece o quadríceps de forma segura, preparando-o para os degraus.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Relaxa a musculatura posterior e melhora flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com as pernas estendidas',
            'Incline o tronco para frente, tentando alcançar os pés',
            'Mantenha a posição por 20-30 segundos',
            'Respire profundamente durante o alongamento',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir um alongamento suave na parte de trás das coxas e panturrilhas.',
          evitar: 'Não force o alongamento ao ponto de dor. Mantenha os joelhos levemente flexionados se necessário.',
          dica: 'Músculos posteriores flexíveis ajudam a reduzir a tensão no joelho durante o movimento de escadas.',
        },
      ],
      aula: {
        titulo: 'Por que descer escadas dói mais?',
        conteudo: `Descer escadas é mais desafiador para o joelho porque exige controle excêntrico — o músculo precisa trabalhar enquanto se alonga para frear o movimento do corpo. Isso gera mais pressão na patela do que subir.

Além disso, ao descer, todo o peso do corpo é transferido para um joelho de cada vez, aumentando a carga. Por isso, fortalecer o quadríceps e melhorar o controle de movimento são essenciais para reduzir a dor.`,
      },
    },
    2: {
      titulo: 'Dia 2 — Dor ao Subir e Descer Escadas',
      fase: 1,
      exercicios: [
        {
          titulo: 'Ponte',
          subtitulo: 'Fortalece glúteos e protege a patela',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados e pés apoiados no chão',
            'Eleve o quadril, formando uma linha reta dos ombros aos joelhos',
            'Contraia os glúteos no topo do movimento',
            'Segure por 3 segundos e desça lentamente',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente, não a lombar.',
          evitar: 'Não arqueie demais as costas. Mantenha o core ativado.',
          dica: 'Glúteos fortes reduzem a sobrecarga no joelho ao subir e descer escadas.',
        },
        {
          titulo: 'Abdução Lateral',
          subtitulo: 'Fortalece glúteo médio e estabiliza o joelho',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com as pernas estendidas',
            'Eleve a perna de cima lateralmente, mantendo-a reta',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril (glúteo médio) trabalhando.',
          evitar: 'Não rode o quadril para trás. Mantenha o movimento controlado.',
          dica: 'O glúteo médio evita que o joelho "entre" durante o movimento de escadas.',
        },
        {
          titulo: 'Alongamento de Quadril',
          subtitulo: 'Melhora mobilidade do quadril e reduz tensão no joelho',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente em 90 graus',
            'Empurre o quadril para frente suavemente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir um alongamento na frente do quadril da perna de trás.',
          evitar: 'Não arqueie as costas. Mantenha o core ativado.',
          dica: 'Quadril móvel permite melhor distribuição de carga ao subir escadas.',
        },
      ],
      aula: {
        titulo: 'Glúteos protegem sua patela',
        conteudo: `Os glúteos são fundamentais para proteger o joelho durante o movimento de escadas. Quando os glúteos estão fracos, o joelho tende a "entrar" (valgo dinâmico), aumentando a pressão na patela e causando dor.

Fortalecer os glúteos — especialmente o glúteo médio — ajuda a manter o joelho alinhado, distribuindo melhor a carga e reduzindo o atrito na articulação patelofemoral.`,
      },
    },
    3: {
      titulo: 'Dia 3 — Dor ao Subir e Descer Escadas',
      fase: 1,
      exercicios: [
        {
          titulo: 'Step Baixo Controlado (Subida Leve)',
          subtitulo: 'Inicia o movimento funcional de subir degraus',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo (10-15 cm) ou caixa',
            'Suba com um pé, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado com o pé',
            'Desça lentamente com controle',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Comece com altura baixa e foque no controle do movimento.',
        },
        {
          titulo: 'Mobilidade Tornozelo com Avanço',
          subtitulo: 'Melhora amplitude de movimento para o degrau',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Coloque um pé à frente e empurre o joelho para frente',
            'Tente tocar a parede com o joelho sem tirar o calcanhar do chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha, sem dor no joelho.',
          evitar: 'Não force além do confortável. Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo permite melhor posicionamento no degrau.',
        },
        {
          titulo: 'Quadríceps Leve',
          subtitulo: 'Fortalece a coxa de forma segura',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Estenda uma perna à frente',
            'Contraia o quadríceps por 6 segundos',
            'Relaxe por 3 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da coxa trabalhando intensamente.',
          evitar: 'Não prenda a respiração. Não force se sentir dor na patela.',
          dica: 'Quadríceps forte é essencial para controlar o movimento de escadas.',
        },
      ],
      aula: {
        titulo: 'Como distribuir carga no degrau',
        conteudo: `A forma como você pisa no degrau faz toda a diferença. Ao subir, empurre pelo calcanhar e use o quadril — isso ativa os glúteos e reduz a pressão no joelho. Evite empurrar apenas pela ponta dos pés.

Ao descer, controle o movimento com o quadríceps, descendo lentamente. Não "caia" no degrau. Esse controle excêntrico protege a patela e reduz o impacto na articulação.`,
      },
    },
    4: {
      titulo: 'Dia 4 — Dor ao Subir e Descer Escadas',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mini-Agachamento na Parede',
          subtitulo: 'Fortalece quadríceps com suporte',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Encoste as costas na parede',
            'Deslize para baixo até 30-40 graus de flexão',
            'Mantenha os joelhos alinhados com os pés',
            'Segure por 10 segundos',
            'Faça 8 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando, sem dor no joelho.',
          evitar: 'Não desça muito se sentir dor. Não deixe os joelhos ultrapassarem os pés.',
          dica: 'Este exercício simula o controle necessário para descer escadas.',
        },
        {
          titulo: 'Ponte Unilateral Leve',
          subtitulo: 'Fortalece glúteos de forma unilateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Segure por 3 segundos no topo',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando intensamente.',
          evitar: 'Não torça o quadril. Mantenha o core ativado.',
          dica: 'Força unilateral é essencial para escadas, onde cada perna trabalha individualmente.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Relaxa musculatura posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento suave na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Como alinhar o joelho no degrau?',
        conteudo: `O alinhamento do joelho é crucial para evitar dor. Ao subir ou descer escadas, o joelho deve seguir a linha do segundo dedo do pé — não deve "entrar" nem "sair" demais.

Para manter esse alinhamento, ative conscientemente os glúteos e mantenha o peso distribuído no pé todo, não apenas na ponta. Pratique esse controle nos exercícios de step para transferir para as escadas reais.`,
      },
    },
    5: {
      titulo: 'Dia 5 — Dor ao Subir e Descer Escadas',
      fase: 1,
      exercicios: [
        {
          titulo: 'Descendo o Degrau sem Peso e com Apoio',
          subtitulo: 'Treina controle excêntrico de forma segura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo e apoie-se em um corrimão ou parede',
            'Desça lentamente, controlando o movimento',
            'Foque em frear o movimento com o quadríceps',
            'Não "caia" no degrau',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando para controlar a descida.',
          evitar: 'Não desça rápido. Não deixe o joelho "entrar".',
          dica: 'O controle excêntrico é a chave para descer escadas sem dor.',
        },
        {
          titulo: 'Isometria de Quadríceps',
          subtitulo: 'Fortalece o músculo da coxa',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Estenda uma perna à frente',
            'Contraia o quadríceps por 8 segundos',
            'Relaxe por 3 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da coxa trabalhando intensamente.',
          evitar: 'Não prenda a respiração.',
          dica: 'Quadríceps forte é essencial para controlar a descida de escadas.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Melhora amplitude de movimento do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Por que dói na descida?',
        conteudo: `A descida de escadas é mais desafiadora porque exige contração excêntrica — o músculo trabalha enquanto se alonga para frear o corpo. Isso gera mais pressão na patela do que a subida.

Além disso, na descida, você transfere todo o peso do corpo para um joelho de cada vez, aumentando a carga. Por isso, fortalecer o quadríceps e treinar o controle excêntrico são fundamentais para reduzir a dor.`,
      },
    },
    6: {
      titulo: 'Dia 6 — Dor ao Subir e Descer Escadas',
      fase: 1,
      exercicios: [
        {
          titulo: 'Step Lateral Leve',
          subtitulo: 'Fortalece glúteo médio e estabiliza o joelho',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo',
            'Suba lateralmente, mantendo o joelho alinhado',
            'Desça lentamente',
            'Foque no controle do movimento',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Força lateral protege o joelho durante o movimento de escadas.',
        },
        {
          titulo: 'Elevação de Perna Estendida',
          subtitulo: 'Fortalece quadríceps sem sobrecarregar a patela',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com uma perna flexionada',
            'Mantenha a outra perna estendida',
            'Eleve a perna estendida até a altura do joelho oposto',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando.',
          evitar: 'Não arqueie as costas. Mantenha o core ativado.',
          dica: 'Este exercício fortalece o quadríceps de forma segura.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Relaxa a musculatura da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé, apoiando-se em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas. Mantenha o quadril neutro.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Evite o joelho entrar — valgo dinâmico',
        conteudo: `O valgo dinâmico acontece quando o joelho "entra" durante o movimento, aumentando a pressão na patela e causando dor. Isso geralmente ocorre por fraqueza do glúteo médio.

Para corrigir, fortaleça o glúteo médio com exercícios laterais e pratique manter o joelho alinhado com o segundo dedo do pé durante todos os movimentos. Essa correção é essencial para subir e descer escadas sem dor.`,
      },
    },
    7: {
      titulo: 'Dia 7 — Dor ao Subir e Descer Escadas',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade Global',
          subtitulo: 'Prepara todas as articulações para o movimento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Faça círculos com os tornozelos (10 cada lado)',
            'Flexione e estenda os joelhos suavemente (10 vezes)',
            'Faça círculos com os quadris (10 cada lado)',
            'Movimente-se de forma fluida e controlada',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações aquecendo e ficando mais soltas.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade global prepara o corpo para movimentos funcionais.',
        },
        {
          titulo: 'Step Baixo Completo (Subida e Descida com Apoio)',
          subtitulo: 'Integra subida e descida de forma controlada',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo e apoie-se se necessário',
            'Suba com controle, empurrando pelo calcanhar',
            'Desça lentamente, controlando o movimento',
            'Mantenha o joelho alinhado durante todo o movimento',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir controle e estabilidade durante todo o movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Este exercício simula o movimento real de escadas.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura trabalhada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (20-30s cada lado)',
            'Alongue posterior (20-30s)',
            'Alongue quadril (20-30s cada lado)',
            'Respire profundamente durante os alongamentos',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação e previne rigidez.',
        },
      ],
      aula: {
        titulo: 'Semana 1 — evolução do seu joelho',
        conteudo: `Parabéns por completar a primeira semana! Nesta fase, você trabalhou mobilidade, ativação muscular e controle inicial de movimento. Seu joelho já está mais preparado para os desafios das escadas.

Na próxima semana, vamos aumentar a intensidade, focando em força e estabilidade funcional. Continue prestando atenção ao alinhamento do joelho e ao controle dos movimentos — esses detalhes fazem toda a diferença.`,
      },
    },
    8: {
      titulo: 'Dia 8 — Dor ao Subir e Descer Escadas',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Baixo com Pausa',
          subtitulo: 'Melhora controle e estabilidade no degrau',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo',
            'Suba e pause por 3 segundos no topo',
            'Desça lentamente',
            'Mantenha o joelho alinhado durante a pausa',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir controle e estabilidade durante a pausa.',
          evitar: 'Não deixe o joelho "entrar" durante a pausa.',
          dica: 'A pausa treina estabilidade, essencial para escadas.',
        },
        {
          titulo: 'Abdução com Faixa',
          subtitulo: 'Fortalece glúteo médio com resistência',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque uma faixa elástica acima dos joelhos',
            'Fique em pé com pés afastados na largura dos ombros',
            'Dê um passo lateral contra a resistência',
            'Mantenha os joelhos alinhados',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando contra a resistência.',
          evitar: 'Não deixe os joelhos "entrarem". Mantenha a tensão na faixa.',
          dica: 'Glúteo médio forte previne o valgo dinâmico nas escadas.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Relaxa musculatura posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento suave na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Controle excêntrico — chave da descida',
        conteudo: `O controle excêntrico é a capacidade do músculo de controlar o movimento enquanto se alonga — exatamente o que acontece ao descer escadas. Quando esse controle é fraco, o corpo "cai" no degrau, aumentando o impacto na patela.

Treinar o controle excêntrico com exercícios de descida lenta e pausada fortalece o quadríceps de forma específica para esse movimento, reduzindo significativamente a dor ao descer escadas.`,
      },
    },
    9: {
      titulo: 'Dia 9 — Dor ao Subir e Descer Escadas',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Baixo (Descida Lenta com Apoio)',
          subtitulo: 'Treina controle excêntrico específico',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo e apoie-se se necessário',
            'Suba normalmente',
            'Desça muito lentamente (4-5 segundos)',
            'Controle o movimento com o quadríceps',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente para controlar a descida.',
          evitar: 'Não "caia" no degrau. Não deixe o joelho "entrar".',
          dica: 'Descida lenta fortalece o controle excêntrico.',
        },
        {
          titulo: 'Ponte com Pausa',
          subtitulo: 'Fortalece glúteos com ênfase na contração',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril',
            'Pause por 5 segundos no topo, contraindo os glúteos',
            'Desça lentamente',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente durante a pausa.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes reduzem a sobrecarga no joelho.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Melhora dorsiflexão para o degrau',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo permite melhor posicionamento no degrau.',
        },
      ],
      aula: {
        titulo: 'Ativando quadríceps corretamente',
        conteudo: `Muitas pessoas têm dificuldade em ativar o quadríceps corretamente, especialmente após períodos de dor. Isso leva a compensações e sobrecarga em outras estruturas.

Para ativar bem o quadríceps, foque em "empurrar o joelho para trás" durante os exercícios de extensão. Visualize o músculo contraindo e mantenha a contração por alguns segundos. Com o tempo, essa ativação se torna automática e protege o joelho durante as escadas.`,
      },
    },
    10: {
      titulo: 'Dia 10 — Dor ao Subir e Descer Escadas',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Lateral Médio',
          subtitulo: 'Fortalece glúteo médio com altura maior',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau de altura média (15-20 cm)',
            'Suba lateralmente, mantendo o joelho alinhado',
            'Desça lentamente',
            'Foque no controle lateral',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Força lateral é essencial para estabilidade nas escadas.',
        },
        {
          titulo: 'Extensão com Faixa',
          subtitulo: 'Fortalece quadríceps com resistência',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira com faixa elástica no tornozelo',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando contra a resistência.',
          evitar: 'Não use impulso. Mantenha o movimento controlado.',
          dica: 'Resistência progressiva fortalece o quadríceps de forma eficaz.',
        },
        {
          titulo: 'Alongamento Quadril',
          subtitulo: 'Melhora mobilidade do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Força lateral = joelho firme',
        conteudo: `A força lateral do quadril (glúteo médio) é fundamental para manter o joelho estável durante o movimento de escadas. Quando essa musculatura é fraca, o joelho tende a "entrar", aumentando a pressão na patela.

Exercícios laterais, como step lateral e abdução com faixa, fortalecem especificamente essa musculatura, criando uma base sólida de estabilidade que protege o joelho em todos os movimentos funcionais.`,
      },
    },
    11: {
      titulo: 'Dia 11 — Dor ao Subir e Descer Escadas',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Alternado (Subida)',
          subtitulo: 'Simula movimento real de escadas',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo a médio',
            'Suba alternando as pernas',
            'Mantenha ritmo controlado',
            'Foque no alinhamento do joelho',
            'Faça 10 repetições (5 cada perna)',
          ],
          sensacaoCorreta: 'Você deve sentir controle e fluidez no movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento alternado prepara para escadas reais.',
        },
        {
          titulo: 'Glúteo Médio com Faixa Média',
          subtitulo: 'Aumenta resistência para o glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica acima dos joelhos',
            'Fique em pé com pés afastados',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante na faixa',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Resistência média aumenta a força lateral.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Melhora amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Controle lateral do joelho',
        conteudo: `O controle lateral do joelho é essencial para prevenir o valgo dinâmico (joelho "entrando") durante o movimento de escadas. Esse controle vem principalmente do glúteo médio.

Quando você sobe ou desce escadas, o glúteo médio trabalha para manter o joelho alinhado com o pé. Se essa musculatura é fraca, o joelho colapsa para dentro, aumentando a pressão na patela e causando dor. Fortalecer o glúteo médio é fundamental para escadas sem dor.`,
      },
    },
    12: {
      titulo: 'Dia 12 — Dor ao Subir e Descer Escadas',
      fase: 2,
      exercicios: [
        {
          titulo: 'Descendo o Degrau com Técnica',
          subtitulo: 'Aperfeiçoa controle excêntrico',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio',
            'Desça muito lentamente (5-6 segundos)',
            'Mantenha o joelho alinhado',
            'Controle o movimento com o quadríceps',
            'Apoie-se minimamente',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente para controlar a descida.',
          evitar: 'Não "caia" no degrau. Não deixe o joelho "entrar".',
          dica: 'Técnica correta na descida protege a patela.',
        },
        {
          titulo: 'Quadríceps Isométrico 12s',
          subtitulo: 'Aumenta tempo de contração',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Estenda uma perna à frente',
            'Contraia o quadríceps por 12 segundos',
            'Relaxe por 5 segundos',
            'Faça 8 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da coxa trabalhando intensamente.',
          evitar: 'Não prenda a respiração.',
          dica: 'Contrações mais longas aumentam resistência muscular.',
        },
        {
          titulo: 'Posterior Profundo',
          subtitulo: 'Alongamento intenso da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente, tentando alcançar os pés',
            'Mantenha por 30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento intenso na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor aguda.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Evite sobrecarregar a patela',
        conteudo: `A patela é um osso pequeno que suporta grandes forças durante o movimento de escadas. Para evitar sobrecarga, é essencial distribuir bem a carga entre todas as estruturas do joelho.

Use o quadril para gerar força (ativando os glúteos), mantenha o joelho alinhado (evitando valgo dinâmico) e controle o movimento com o quadríceps. Essa combinação reduz significativamente a pressão na patela, permitindo subir e descer escadas sem dor.`,
      },
    },
    13: {
      titulo: 'Dia 13 — Dor ao Subir e Descer Escadas',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Alto Assistido',
          subtitulo: 'Aumenta altura com suporte',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau alto (20-25 cm)',
            'Apoie-se em um corrimão ou parede',
            'Suba com controle, empurrando pelo calcanhar',
            'Desça lentamente',
            'Faça 8 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Altura maior prepara para escadas reais.',
        },
        {
          titulo: 'Abdução Lenta',
          subtitulo: 'Fortalece glúteo médio com controle',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima muito lentamente (4 segundos)',
            'Pause por 2 segundos no topo',
            'Desça lentamente (4 segundos)',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não rode o quadril. Mantenha o movimento controlado.',
          dica: 'Movimento lento aumenta o tempo sob tensão.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Melhora dorsiflexão',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo permite melhor posicionamento no degrau.',
        },
      ],
      aula: {
        titulo: 'A importância do pé na escada',
        conteudo: `O pé é a base de todo o movimento de escadas. A forma como você posiciona e usa o pé no degrau afeta diretamente o joelho. Um pé bem posicionado distribui a carga de forma equilibrada, reduzindo a pressão na patela.

Ao subir, coloque o pé todo no degrau (não apenas a ponta) e empurre pelo calcanhar. Ao descer, controle o movimento com o pé todo apoiado. Boa mobilidade de tornozelo é essencial para esse posicionamento correto.`,
      },
    },
    14: {
      titulo: 'Dia 14 — Dor ao Subir e Descer Escadas',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Médio Completo',
          subtitulo: 'Integra subida e descida em altura média',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio (15-20 cm)',
            'Suba e desça de forma fluida',
            'Mantenha controle durante todo o movimento',
            'Foque no alinhamento do joelho',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir controle, estabilidade e confiança no movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento completo prepara para escadas reais.',
        },
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Fortalece glúteos com maior intensidade',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 5 segundos no topo',
            'Desça muito lentamente (5 segundos)',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para escadas sem dor.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (20-30s cada lado)',
            'Alongue posterior (20-30s)',
            'Alongue quadril (20-30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Semana 2 — movimento corrigido',
        conteudo: `Parabéns por completar a segunda semana! Nesta fase, você trabalhou força, estabilidade e controle excêntrico — elementos essenciais para subir e descer escadas sem dor.

Seu joelho agora está mais forte e estável. Na próxima semana, vamos focar no retorno à função real, praticando movimentos de escadas com maior intensidade e confiança. Continue prestando atenção ao alinhamento e ao controle — você está no caminho certo!`,
      },
    },
    15: {
      titulo: 'Dia 15 — Dor ao Subir e Descer Escadas',
      fase: 3,
      exercicios: [
        {
          titulo: 'Escada Real: Subida Controlada',
          subtitulo: 'Inicia prática em escadas reais',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use uma escada real (2-4 degraus)',
            'Suba lentamente, um degrau de cada vez',
            'Empurre pelo calcanhar, ativando os glúteos',
            'Mantenha o joelho alinhado',
            'Apoie-se no corrimão se necessário',
            'Faça 5-8 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança ao subir.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Comece com poucos degraus e aumente gradualmente.',
        },
        {
          titulo: 'Glúteo Médio com Banda Forte',
          subtitulo: 'Aumenta resistência para máxima força lateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica forte acima dos joelhos',
            'Fique em pé com pés afastados',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando muito intensamente.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Resistência forte maximiza a força do glúteo médio.',
        },
        {
          titulo: 'Mobilidade Quadril Avançada',
          subtitulo: 'Melhora amplitude máxima do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente com mais intensidade',
            'Mantenha as costas retas',
            'Segure por 30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento intenso na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite usar o quadril para aliviar o joelho.',
        },
      ],
      aula: {
        titulo: 'Use o quadril para aliviar o joelho',
        conteudo: `Uma das chaves para subir e descer escadas sem dor é usar o quadril como gerador principal de força, em vez de sobrecarregar o joelho. Quando você ativa os glúteos e empurra pelo calcanhar, o quadril faz a maior parte do trabalho.

Isso reduz significativamente a pressão na patela. Pratique conscientemente ativar os glúteos durante o movimento de escadas — com o tempo, isso se torna automático e protege seu joelho de forma natural.`,
      },
    },
    16: {
      titulo: 'Dia 16 — Dor ao Subir e Descer Escadas',
      fase: 3,
      exercicios: [
        {
          titulo: 'Escada Real: Descida com Apoio',
          subtitulo: 'Pratica controle excêntrico em escadas reais',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use uma escada real (2-4 degraus)',
            'Desça muito lentamente, um degrau de cada vez',
            'Controle o movimento com o quadríceps',
            'Mantenha o joelho alinhado',
            'Apoie-se no corrimão',
            'Faça 5-8 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando para controlar a descida.',
          evitar: 'Não "caia" nos degraus. Não deixe o joelho "entrar".',
          dica: 'Descida lenta e controlada protege a patela.',
        },
        {
          titulo: 'Step Lateral Alto',
          subtitulo: 'Máxima força lateral com altura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau alto (20-25 cm)',
            'Suba lateralmente com controle',
            'Mantenha o joelho alinhado',
            'Desça lentamente',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Força lateral máxima garante estabilidade em escadas.',
        },
        {
          titulo: 'Posterior',
          subtitulo: 'Alongamento da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Controle excêntrico = descida sem dor',
        conteudo: `O controle excêntrico é a habilidade mais importante para descer escadas sem dor. Quando você desce lentamente, controlando o movimento com o quadríceps, você treina o músculo de forma específica para essa função.

Com o tempo, esse controle se torna automático e natural. Seu joelho aprende a "frear" o corpo de forma eficiente, reduzindo drasticamente a pressão na patela e eliminando a dor na descida de escadas.`,
      },
    },
    17: {
      titulo: 'Dia 17 — Dor ao Subir e Descer Escadas',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Alto Lento',
          subtitulo: 'Combina altura com controle máximo',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau alto (20-25 cm)',
            'Suba muito lentamente (4-5 segundos)',
            'Pause por 2 segundos no topo',
            'Desça muito lentamente (5-6 segundos)',
            'Faça 8 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir controle total durante todo o movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento lento em altura máxima prepara para qualquer escada.',
        },
        {
          titulo: 'Extensão com Resistência Média',
          subtitulo: 'Fortalece quadríceps com resistência',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com faixa elástica média no tornozelo',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente.',
          evitar: 'Não use impulso.',
          dica: 'Quadríceps forte é essencial para escadas sem dor.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Mobilidade de tornozelo é essencial para escadas.',
        },
      ],
      aula: {
        titulo: 'Fortalecendo para a vida real',
        conteudo: `Nesta fase final, estamos fortalecendo seu joelho para as demandas da vida real. Escadas variam em altura, inclinação e número de degraus — seu joelho precisa estar preparado para todas essas variações.

Os exercícios desta semana simulam essas diferentes demandas, garantindo que você tenha força, controle e confiança para subir e descer qualquer escada sem dor. Continue focando na técnica correta — ela é sua melhor proteção.`,
      },
    },
    18: {
      titulo: 'Dia 18 — Dor ao Subir e Descer Escadas',
      fase: 3,
      exercicios: [
        {
          titulo: 'Escada Real: Subida e Descida Alternadas',
          subtitulo: 'Simula uso real de escadas',
          duracao: '6-7 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use uma escada real (3-5 degraus)',
            'Suba alternando as pernas',
            'Desça alternando as pernas',
            'Mantenha ritmo controlado',
            'Use corrimão minimamente',
            'Faça 5-8 repetições completas',
          ],
          sensacaoCorreta: 'Você deve sentir confiança e controle durante todo o movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento alternado é o padrão natural de escadas.',
        },
        {
          titulo: 'Glúteo Médio Unilateral',
          subtitulo: 'Força lateral máxima em cada lado',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma perna',
            'Mantenha o joelho alinhado',
            'Segure por 15 segundos',
            'Faça pequenos movimentos laterais',
            'Faça 8 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando para manter o equilíbrio.',
          evitar: 'Não deixe o joelho "entrar".',
          dica: 'Força unilateral é essencial para escadas.',
        },
        {
          titulo: 'Quadríceps Alongamento',
          subtitulo: 'Relaxa a musculatura da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Mini ajustes que fazem diferença',
        conteudo: `Pequenos ajustes na técnica podem fazer uma grande diferença na dor ao subir e descer escadas. Empurrar pelo calcanhar em vez da ponta do pé, manter o joelho alinhado, controlar a velocidade da descida — esses detalhes parecem pequenos, mas têm grande impacto.

Preste atenção a esses mini ajustes durante as escadas do dia a dia. Com o tempo, eles se tornam automáticos e protegem seu joelho de forma natural, permitindo que você use escadas sem pensar ou sentir dor.`,
      },
    },
    19: {
      titulo: 'Dia 19 — Dor ao Subir e Descer Escadas',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Alto Circuito',
          subtitulo: 'Treina resistência em altura máxima',
          duracao: '6-7 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau alto (20-25 cm)',
            'Faça 10 subidas e descidas de cada lado',
            'Mantenha ritmo controlado mas contínuo',
            'Foque no alinhamento durante todo o circuito',
            'Descanse 1 minuto e repita 2-3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir resistência muscular, mas com controle.',
          evitar: 'Não sacrifique a técnica pela velocidade.',
          dica: 'Circuito treina resistência para múltiplos degraus.',
        },
        {
          titulo: 'Ponte Unilateral com Pausa',
          subtitulo: 'Máxima força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Pause por 5 segundos no topo',
            'Desça lentamente',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo trabalhando muito intensamente.',
          evitar: 'Não torça o quadril.',
          dica: 'Glúteos fortes são essenciais para escadas sem dor.',
        },
        {
          titulo: 'Alongamento Profundo',
          subtitulo: 'Relaxamento completo da musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (30s cada lado)',
            'Alongue posterior (30s)',
            'Alongue quadril (30s cada lado)',
            'Alongue panturrilha (30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento profundo.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento profundo ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Como evitar a volta da dor',
        conteudo: `Para manter seu joelho saudável e evitar que a dor volte, é essencial manter os hábitos que você desenvolveu neste programa: fortalecer regularmente quadríceps e glúteos, manter boa mobilidade e prestar atenção à técnica.

Além disso, se você sentir um leve desconforto ao usar escadas, não ignore — volte aos exercícios básicos por alguns dias. Prevenção é sempre mais fácil que tratamento. Mantenha seu joelho forte e ele te servirá bem por toda a vida.`,
      },
    },
    20: {
      titulo: 'Dia 20 — Dor ao Subir e Descer Escadas',
      fase: 3,
      exercicios: [
        {
          titulo: 'Escada Real Completa (2-4 Degraus)',
          subtitulo: 'Teste funcional completo',
          duracao: '6-7 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use uma escada real (4-6 degraus se possível)',
            'Suba e desça de forma natural',
            'Use corrimão minimamente ou não use',
            'Mantenha técnica correta',
            'Faça 5-8 repetições completas',
          ],
          sensacaoCorreta: 'Você deve sentir confiança, controle e mínima ou nenhuma dor.',
          evitar: 'Não force se sentir dor significativa.',
          dica: 'Este é o teste final — você está pronto para escadas reais!',
        },
        {
          titulo: 'Abdução com Banda Forte',
          subtitulo: 'Mantém força lateral máxima',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica forte acima dos joelhos',
            'Fique em pé com pés afastados',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Força lateral protege o joelho em todas as atividades.',
        },
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade regular mantém o joelho saudável.',
        },
      ],
      aula: {
        titulo: 'Seu joelho está mais estável?',
        conteudo: `Após 20 dias de trabalho consistente, seu joelho deve estar significativamente mais estável e forte. Você fortaleceu os músculos que protegem a patela, melhorou o controle de movimento e corrigiu padrões que causavam dor.

Reflita sobre sua evolução: você consegue subir e descer escadas com mais facilidade? Sente mais controle e menos dor? Essas melhorias são resultado do seu esforço e dedicação. Continue mantendo esses hábitos para resultados duradouros.`,
      },
    },
    21: {
      titulo: 'Dia 21 — Dor ao Subir e Descer Escadas',
      fase: 3,
      exercicios: [
        {
          titulo: 'Escada Real: Subida e Descida sem Apoio (se sem dor)',
          subtitulo: 'Teste final de independência funcional',
          duracao: '6-7 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use uma escada real (4-6 degraus)',
            'Suba e desça sem usar corrimão (se confortável)',
            'Mantenha técnica perfeita',
            'Foque no alinhamento e controle',
            'Faça 5-8 repetições completas',
          ],
          sensacaoCorreta: 'Você deve sentir confiança total, controle e mínima ou nenhuma dor.',
          evitar: 'Se ainda sentir dor, continue usando apoio — não há pressa.',
          dica: 'Parabéns! Você recuperou sua capacidade de usar escadas!',
        },
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Mantém força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 5 segundos no topo',
            'Desça muito lentamente',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Continue fortalecendo os glúteos regularmente.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Celebração e relaxamento final',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (30s cada lado)',
            'Alongue posterior (30s)',
            'Alongue quadril (30s cada lado)',
            'Alongue panturrilha (30s cada lado)',
            'Respire profundamente e celebre sua conquista',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento, satisfação e orgulho.',
          evitar: 'Não pare de se cuidar — mantenha os hábitos!',
          dica: 'Você completou o programa! Continue forte!',
        },
      ],
      aula: {
        titulo: 'Como manter escadas sem dor para sempre',
        conteudo: `Parabéns por completar os 21 dias! Você fortaleceu seu joelho, corrigiu padrões de movimento e recuperou sua capacidade de subir e descer escadas sem dor. Mas o trabalho não termina aqui.

Para manter esses resultados, continue fazendo exercícios de fortalecimento 2-3 vezes por semana, mantenha boa mobilidade e preste atenção à técnica nas escadas do dia a dia. Se sentir um leve desconforto, volte aos exercícios básicos. Seu joelho agora é forte e saudável — mantenha-o assim!`,
      },
    },
  },
};
