export const dadosTrilhaCondromalacia = {
  nome: 'Condromalácia',
  descricao: 'Programa de 30 dias para reduzir dor, fortalecer e corrigir o movimento da patela',
  totalDias: 30,
  fases: [
    {
      numero: 1,
      nome: 'Redução de Dor + Mobilidade',
      descricao: 'Reduzir dor, ganhar mobilidade e ativar musculatura protetora',
      dias: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      numero: 2,
      nome: 'Fortalecimento',
      descricao: 'Fortalecer quadríceps, glúteos e core',
      dias: [8, 9, 10, 11, 12, 13, 14],
    },
    {
      numero: 3,
      nome: 'Correção de Movimento',
      descricao: 'Corrigir mecânica de movimento e reduzir atrito patelofemoral',
      dias: [15, 16, 17, 18, 19, 20, 21],
    },
    {
      numero: 4,
      nome: 'Retorno à Função',
      descricao: 'Retorno à função completa — subir escada, agachar, caminhar',
      dias: [22, 23, 24, 25, 26, 27, 28, 29, 30],
    },
  ],
  dias: {
    // FASE 1 - Dias 1 a 7
    1: {
      titulo: 'Dia 1 — Condromalácia',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade do Joelho',
          subtitulo: 'Melhora amplitude de movimento e reduz rigidez',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira com as costas retas',
            'Flexione e estenda o joelho suavemente',
            'Faça movimentos lentos e controlados',
            'Repita 15 vezes de cada lado',
            'Respire naturalmente durante o movimento',
          ],
          sensacaoCorreta: 'Você deve sentir o joelho se movendo livremente, sem dor aguda.',
          evitar: 'Não force o movimento além do confortável. Não faça movimentos bruscos.',
          dica: 'Mobilidade é o primeiro passo para reduzir a dor na patela.',
        },
        {
          titulo: 'Isometria de Quadríceps',
          subtitulo: 'Ativa o músculo da coxa sem sobrecarregar a patela',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com as costas apoiadas',
            'Estenda uma perna à frente, mantendo-a reta',
            'Contraia o músculo da coxa por 6 segundos',
            'Relaxe por 3 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da frente da coxa trabalhando intensamente.',
          evitar: 'Não prenda a respiração. Não force se sentir dor na patela.',
          dica: 'Este exercício fortalece o quadríceps de forma segura para a patela.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Relaxa a musculatura posterior e melhora flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com as pernas estendidas',
            'Incline o tronco para frente suavemente',
            'Tente alcançar os pés sem forçar',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir um alongamento suave na parte de trás das coxas.',
          evitar: 'Não force o alongamento ao ponto de dor. Mantenha os joelhos levemente flexionados se necessário.',
          dica: 'Músculos posteriores flexíveis reduzem a tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Por que seu joelho dói?',
        conteudo: `A condromalácia patelar acontece quando a cartilagem atrás da patela (rótula) fica desgastada ou irritada. Isso causa dor ao subir escadas, agachar ou ficar sentado por muito tempo.

A boa notícia é que, na maioria dos casos, você pode melhorar significativamente com exercícios específicos que fortalecem os músculos ao redor do joelho e corrigem o alinhamento da patela. Este programa foi criado para guiá-lo nessa jornada de recuperação.`,
      },
    },
    2: {
      titulo: 'Dia 2 — Condromalácia',
      fase: 1,
      exercicios: [
        {
          titulo: 'Ponte (Elevação de Quadril)',
          subtitulo: 'Fortalece glúteos e protege a patela',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados e pés apoiados',
            'Eleve o quadril, formando uma linha reta dos ombros aos joelhos',
            'Contraia os glúteos no topo',
            'Segure por 3 segundos e desça lentamente',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente, não a lombar.',
          evitar: 'Não arqueie demais as costas. Mantenha o core ativado.',
          dica: 'Glúteos fortes reduzem a sobrecarga na patela.',
        },
        {
          titulo: 'Extensão de Joelho Sentado',
          subtitulo: 'Fortalece quadríceps de forma controlada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira com as costas retas',
            'Estenda uma perna à frente até ficar reta',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da coxa trabalhando.',
          evitar: 'Não use impulso. Mantenha o movimento controlado.',
          dica: 'Movimento controlado protege a patela durante o fortalecimento.',
        },
        {
          titulo: 'Alongamento de Quadríceps',
          subtitulo: 'Relaxa a musculatura da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé, apoiando-se em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas. Mantenha o quadril neutro.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Glúteos e patela — qual a relação?',
        conteudo: `Os glúteos desempenham um papel fundamental na saúde da patela. Quando os glúteos estão fracos, o fêmur (osso da coxa) tende a rodar para dentro, desalinhando a patela e aumentando o atrito na articulação.

Fortalecer os glúteos ajuda a manter o fêmur em posição correta, permitindo que a patela deslize suavemente no sulco femoral. Isso reduz significativamente a dor e o desgaste da cartilagem.`,
      },
    },
    3: {
      titulo: 'Dia 3 — Condromalácia',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mini Agachamento na Parede',
          subtitulo: 'Fortalece quadríceps com suporte',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Encoste as costas na parede',
            'Deslize para baixo até 30 graus de flexão (mini agachamento)',
            'Mantenha os joelhos alinhados com os pés',
            'Segure por 8 segundos',
            'Faça 8 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando, sem dor no joelho.',
          evitar: 'Não desça muito se sentir dor. Não deixe os joelhos ultrapassarem os pés.',
          dica: 'Comece com ângulo pequeno e aumente gradualmente.',
        },
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Melhora dorsiflexão e distribui carga no joelho',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Coloque um pé à frente, joelho levemente flexionado',
            'Empurre o joelho para frente, mantendo o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
        {
          titulo: 'Alongamento de Glúteo',
          subtitulo: 'Relaxa musculatura do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Cruze um tornozelo sobre o joelho oposto',
            'Puxe a coxa em direção ao peito',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento no glúteo.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Glúteos flexíveis melhoram o alinhamento do joelho.',
        },
      ],
      aula: {
        titulo: 'O que piora a condromalácia?',
        conteudo: `Algumas atividades podem piorar a dor na patela: subir e descer escadas, agachar profundamente, ficar sentado por muito tempo (dor de cinema), correr em superfícies duras e usar salto alto.

Durante este programa, evite essas atividades ou faça-as com moderação. À medida que seu joelho ficar mais forte, você poderá retornar gradualmente a essas atividades sem dor.`,
      },
    },
    4: {
      titulo: 'Dia 4 — Condromalácia',
      fase: 1,
      exercicios: [
        {
          titulo: 'Isometria de Glúteo Médio',
          subtitulo: 'Fortalece estabilizador lateral do quadril',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Segure por 8 segundos no topo',
            'Desça lentamente',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não rode o quadril para trás. Mantenha o movimento controlado.',
          dica: 'Glúteo médio forte evita que o joelho "entre" durante movimentos.',
        },
        {
          titulo: 'Extensão com Toalha',
          subtitulo: 'Fortalece quadríceps com resistência leve',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com uma toalha enrolada sob o joelho',
            'Pressione o joelho contra a toalha',
            'Estenda a perna, mantendo pressão na toalha',
            'Segure por 5 segundos',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente.',
          evitar: 'Não tire a pressão da toalha.',
          dica: 'A toalha ajuda a ativar o quadríceps corretamente.',
        },
        {
          titulo: 'Alongamento de Quadril',
          subtitulo: 'Melhora mobilidade do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente em 90 graus',
            'Empurre o quadril para frente suavemente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor distribuição de carga no joelho.',
        },
      ],
      aula: {
        titulo: 'Postura e alinhamento da patela',
        conteudo: `A postura e o alinhamento dos membros inferiores afetam diretamente a patela. Quando o joelho "entra" (valgo dinâmico), a patela é puxada para fora do sulco femoral, aumentando o atrito e a dor.

Preste atenção ao alinhamento do joelho durante os exercícios e atividades diárias. O joelho deve seguir a linha do segundo dedo do pé. Fortalecer o glúteo médio ajuda a manter esse alinhamento correto.`,
      },
    },
    5: {
      titulo: 'Dia 5 — Condromalácia',
      fase: 1,
      exercicios: [
        {
          titulo: 'Step Baixo (10-15 cm)',
          subtitulo: 'Inicia movimento funcional controlado',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo (10-15 cm) ou caixa',
            'Suba com um pé, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado com o pé',
            'Desça lentamente com controle',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Comece com altura baixa e foque no controle.',
        },
        {
          titulo: 'Ponte Unilateral Leve',
          subtitulo: 'Fortalece glúteos de forma unilateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Segure por 3 segundos no topo',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando.',
          evitar: 'Não torça o quadril. Mantenha o core ativado.',
          dica: 'Força unilateral é essencial para atividades do dia a dia.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Relaxa musculatura posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Dor boa x dor perigosa',
        conteudo: `É importante distinguir entre desconforto muscular (dor boa) e dor articular (dor perigosa). Desconforto muscular durante e após os exercícios é normal e indica que os músculos estão trabalhando.

Dor aguda, pontada ou dor que piora progressivamente durante o exercício são sinais de alerta. Se sentir esse tipo de dor, pare o exercício e use o Plano de Crise. Aprenda a ouvir seu corpo e respeitar seus limites.`,
      },
    },
    6: {
      titulo: 'Dia 6 — Condromalácia',
      fase: 1,
      exercicios: [
        {
          titulo: 'Agachamento com Cadeira',
          subtitulo: 'Fortalece membros inferiores com segurança',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma cadeira',
            'Desça lentamente como se fosse sentar',
            'Toque levemente o assento e volte',
            'Mantenha os joelhos alinhados com os pés',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando.',
          evitar: 'Não deixe os joelhos ultrapassarem muito os pés. Não caia na cadeira.',
          dica: 'A cadeira oferece segurança para aprender o movimento correto.',
        },
        {
          titulo: 'Abdução de Quadril em Pé',
          subtitulo: 'Fortalece glúteo médio em posição funcional',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve uma perna lateralmente, mantendo-a reta',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não incline o tronco. Mantenha o movimento controlado.',
          dica: 'Glúteo médio forte protege o joelho em todas as atividades.',
        },
        {
          titulo: 'Alongamento de Panturrilha',
          subtitulo: 'Melhora flexibilidade da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma parede',
            'Coloque um pé atrás, mantendo-o reto',
            'Empurre o calcanhar de trás no chão',
            'Incline o corpo para frente',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Panturrilha flexível melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Por que escadas doem?',
        conteudo: `Subir e descer escadas é particularmente doloroso na condromalácia porque aumenta significativamente a pressão na patela. Ao subir, a pressão pode ser 3-4 vezes o peso corporal; ao descer, pode chegar a 5-7 vezes.

Além disso, descer escadas exige controle excêntrico (músculo trabalhando enquanto se alonga), que é mais desafiador. À medida que você fortalecer o quadríceps e os glúteos, essa atividade ficará mais fácil e menos dolorosa.`,
      },
    },
    7: {
      titulo: 'Dia 7 — Condromalácia',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade Global',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Faça círculos com os tornozelos (10 cada lado)',
            'Flexione e estenda os joelhos suavemente (10 vezes)',
            'Faça círculos com os quadris (10 cada lado)',
            'Movimente-se de forma fluida e controlada',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações aquecendo e ficando mais soltas.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade global prepara o corpo para movimentos funcionais.',
        },
        {
          titulo: 'Agachamento Isométrico Leve',
          subtitulo: 'Fortalece em posição estática',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Encoste as costas na parede',
            'Deslize para baixo até 30 graus',
            'Segure a posição por 15 segundos',
            'Descanse 10 segundos',
            'Faça 6 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Isometria fortalece sem movimento, protegendo a patela.',
        },
        {
          titulo: 'Alongamento Completo',
          subtitulo: 'Relaxa toda a musculatura trabalhada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (20-30s cada lado)',
            'Alongue posterior (20-30s)',
            'Alongue quadril (20-30s cada lado)',
            'Respire profundamente durante os alongamentos',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação e previne rigidez.',
        },
      ],
      aula: {
        titulo: 'Resumo da primeira semana',
        conteudo: `Parabéns por completar a primeira semana! Você trabalhou mobilidade, ativação muscular e controle inicial de movimento. Seu joelho já está mais preparado para os desafios das próximas semanas.

Na próxima fase, vamos aumentar a intensidade, focando em fortalecimento mais específico do quadríceps, glúteos e core. Continue prestando atenção ao alinhamento do joelho e ao controle dos movimentos — esses detalhes fazem toda a diferença na sua recuperação.`,
      },
    },

    // FASE 2 - Dias 8 a 14
    8: {
      titulo: 'Dia 8 — Condromalácia',
      fase: 2,
      exercicios: [
        {
          titulo: 'Ponte com Pausa de 5s',
          subtitulo: 'Aumenta tempo sob tensão dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril',
            'Pause por 5 segundos no topo, contraindo os glúteos',
            'Desça lentamente',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente durante a pausa.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Pausa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Extensão de Joelho com Resistência Leve',
          subtitulo: 'Fortalece quadríceps com carga progressiva',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com uma faixa elástica leve no tornozelo',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando contra a resistência.',
          evitar: 'Não use impulso.',
          dica: 'Resistência progressiva fortalece o quadríceps de forma eficaz.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Como fortalecer sem piorar a dor',
        conteudo: `Fortalecer o joelho com condromalácia requer equilíbrio. Você precisa desafiar os músculos o suficiente para fortalecê-los, mas sem sobrecarregar a patela. A chave é progressão gradual e atenção aos sinais do corpo.

Se um exercício causa dor aguda na patela, reduza a amplitude, a carga ou o número de repetições. Desconforto muscular é normal, mas dor articular é sinal de alerta. Respeite seus limites e progrida no seu ritmo.`,
      },
    },
    9: {
      titulo: 'Dia 9 — Condromalácia',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento Parcial (30º)',
          subtitulo: 'Fortalece com amplitude controlada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça apenas 30 graus (mini agachamento)',
            'Mantenha os joelhos alinhados com os pés',
            'Suba empurrando pelos calcanhares',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando.',
          evitar: 'Não desça muito se sentir dor. Não deixe os joelhos "entrarem".',
          dica: 'Amplitude pequena protege a patela enquanto fortalece.',
        },
        {
          titulo: 'Abdução de Quadril + Isometria',
          subtitulo: 'Combina movimento com contração mantida',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Segure por 5 segundos no topo',
            'Desça lentamente',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Isometria aumenta a força do glúteo médio.',
        },
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
      ],
      aula: {
        titulo: 'A importância da mobilidade',
        conteudo: `Mobilidade adequada das articulações adjacentes ao joelho (tornozelo e quadril) é fundamental para a saúde da patela. Quando o tornozelo ou quadril têm mobilidade limitada, o joelho compensa, aumentando o estresse na patela.

Manter boa mobilidade de tornozelo e quadril permite que o joelho se mova de forma mais eficiente e com menos compensações. Por isso, incluímos exercícios de mobilidade regularmente neste programa.`,
      },
    },
    10: {
      titulo: 'Dia 10 — Condromalácia',
      fase: 2,
      exercicios: [
        {
          titulo: 'Isometria de Quadríceps 8s',
          subtitulo: 'Aumenta tempo de contração',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Estenda uma perna à frente',
            'Contraia o quadríceps por 8 segundos',
            'Relaxe por 4 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da coxa trabalhando intensamente.',
          evitar: 'Não prenda a respiração.',
          dica: 'Contrações mais longas aumentam resistência muscular.',
        },
        {
          titulo: 'Step Baixo com Controle',
          subtitulo: 'Aperfeiçoa controle de movimento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo (10-15 cm)',
            'Suba lentamente (3 segundos)',
            'Pause por 2 segundos no topo',
            'Desça lentamente (3 segundos)',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir controle total durante todo o movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento lento aumenta o controle neuromuscular.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Mantém flexibilidade da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Como distribuir carga no joelho',
        conteudo: `A forma como você distribui a carga durante os movimentos afeta diretamente a pressão na patela. Ao agachar ou subir degraus, empurre pelos calcanhares e use o quadril — isso ativa os glúteos e reduz a sobrecarga no joelho.

Evite empurrar apenas pela ponta dos pés, pois isso aumenta a pressão na patela. Pratique conscientemente essa distribuição de carga durante os exercícios e atividades diárias.`,
      },
    },
    11: {
      titulo: 'Dia 11 — Condromalácia',
      fase: 2,
      exercicios: [
        {
          titulo: 'Ponte Unilateral',
          subtitulo: 'Fortalece glúteos de forma avançada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Segure por 4 segundos no topo',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito.',
          evitar: 'Não torça o quadril. Mantenha o core ativado.',
          dica: 'Força unilateral é essencial para atividades funcionais.',
        },
        {
          titulo: 'Elevação Lateral da Perna',
          subtitulo: 'Fortalece glúteo médio',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Segure por 3 segundos no topo',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não rode o quadril para trás.',
          dica: 'Glúteo médio forte previne valgo dinâmico.',
        },
        {
          titulo: 'Mobilidade de Quadril',
          subtitulo: 'Melhora amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Força lateral = joelho protegido',
        conteudo: `A força lateral do quadril (glúteo médio) é fundamental para manter o joelho estável durante movimentos. Quando essa musculatura é fraca, o joelho tende a "entrar" (valgo dinâmico), aumentando a pressão na patela.

Fortalecer o glúteo médio cria uma base sólida de estabilidade que protege o joelho em todos os movimentos funcionais — caminhar, subir escadas, agachar. Essa é uma das chaves para reduzir a dor na condromalácia.`,
      },
    },
    12: {
      titulo: 'Dia 12 — Condromalácia',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento com Pausa',
          subtitulo: 'Aumenta controle e força',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Pause por 3 segundos',
            'Suba empurrando pelos calcanhares',
            'Faça 10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando durante a pausa.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Pausa aumenta o tempo sob tensão.',
        },
        {
          titulo: 'Extensão de Joelho com Faixa',
          subtitulo: 'Fortalece quadríceps com resistência',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com faixa elástica no tornozelo',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando contra a resistência.',
          evitar: 'Não use impulso.',
          dica: 'Resistência progressiva fortalece de forma eficaz.',
        },
        {
          titulo: 'Alongamento Profundo Posterior',
          subtitulo: 'Alongamento intenso da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente, tentando alcançar os pés',
            'Mantenha por 30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento intenso na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor aguda.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Como evitar dor ao agachar',
        conteudo: `Agachar é um movimento fundamental que muitas pessoas com condromalácia evitam por causa da dor. A chave para agachar sem dor é técnica correta e progressão gradual.

Mantenha os joelhos alinhados com os pés, empurre pelos calcanhares, use o quadril para gerar força e não desça além do ponto de dor. Comece com amplitude pequena e aumente gradualmente à medida que ficar mais forte.`,
      },
    },
    13: {
      titulo: 'Dia 13 — Condromalácia',
      fase: 2,
      exercicios: [
        {
          titulo: 'Subida e Descida de Degrau',
          subtitulo: 'Treina movimento funcional completo',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo a médio',
            'Suba com controle, empurrando pelo calcanhar',
            'Desça lentamente, controlando o movimento',
            'Mantenha o joelho alinhado',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir controle durante todo o movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento completo prepara para escadas reais.',
        },
        {
          titulo: 'Glúteo Médio em Isometria Lateral',
          subtitulo: 'Fortalece estabilizador lateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma perna',
            'Mantenha o joelho alinhado',
            'Segure por 15 segundos',
            'Descanse 10 segundos',
            'Faça 6 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando para manter o equilíbrio.',
          evitar: 'Não deixe o joelho "entrar".',
          dica: 'Equilíbrio unilateral fortalece estabilizadores.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece musculatura da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Equilíbrio e propriocepção',
        conteudo: `Propriocepção é a capacidade do corpo de perceber sua posição no espaço. Na condromalácia, a propriocepção do joelho muitas vezes está comprometida, levando a movimentos descoordenados que aumentam a dor.

Exercícios de equilíbrio melhoram a propriocepção, ajudando o joelho a se mover de forma mais coordenada e eficiente. Isso reduz compensações e protege a patela durante atividades diárias.`,
      },
    },
    14: {
      titulo: 'Dia 14 — Condromalácia',
      fase: 2,
      exercicios: [
        {
          titulo: 'Mobilidade Completa',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade regular mantém o joelho saudável.',
        },
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Consolida técnica de agachamento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Técnica correta é mais importante que amplitude.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (20-30s cada lado)',
            'Alongue posterior (20-30s)',
            'Alongue quadril (20-30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Fechando a fase 2',
        conteudo: `Parabéns por completar a segunda semana! Você trabalhou fortalecimento específico do quadríceps, glúteos e core. Seu joelho agora está significativamente mais forte e estável.

Na próxima fase, vamos focar em correção de movimento e redução do atrito patelofemoral. Você aprenderá a mover-se de forma mais eficiente, reduzindo o estresse na patela. Continue com dedicação — você está fazendo um excelente progresso!`,
      },
    },

    // FASE 3 - Dias 15 a 21
    15: {
      titulo: 'Dia 15 — Condromalácia',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento com Joelho Alinhado',
          subtitulo: 'Foco em alinhamento correto',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para um espelho',
            'Desça até 30-40 graus',
            'Observe se os joelhos seguem a linha dos pés',
            'Corrija se os joelhos "entrarem"',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e alinhamento perfeito.',
          evitar: 'Não deixe os joelhos "entrarem" ou "saírem".',
          dica: 'Alinhamento correto reduz atrito na patela.',
        },
        {
          titulo: 'Ponte com Foco em Glúteos',
          subtitulo: 'Maximiza ativação dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Contraia os glúteos intensamente no topo',
            'Segure por 5 segundos',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para alinhamento correto.',
        },
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo permite melhor alinhamento.',
        },
      ],
      aula: {
        titulo: 'Alinhamento do joelho',
        conteudo: `O alinhamento correto do joelho é fundamental para reduzir o atrito na patela. O joelho deve seguir a linha do segundo dedo do pé durante todos os movimentos — não deve "entrar" (valgo) nem "sair" (varo) demais.

Quando o joelho está bem alinhado, a patela desliza suavemente no sulco femoral, reduzindo o atrito e a dor. Pratique conscientemente esse alinhamento durante os exercícios e atividades diárias.`,
      },
    },
    16: {
      titulo: 'Dia 16 — Condromalácia',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Lateral Suave',
          subtitulo: 'Fortalece glúteo médio lateralmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo',
            'Suba lateralmente, mantendo o joelho alinhado',
            'Desça lentamente',
            'Foque no controle lateral',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Força lateral protege o joelho durante movimentos.',
        },
        {
          titulo: 'Glúteo Médio com Faixa',
          subtitulo: 'Aumenta resistência para glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica acima dos joelhos',
            'Fique em pé com pés afastados',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando contra a resistência.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Glúteo médio forte previne valgo dinâmico.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Mantém flexibilidade da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Importância do glúteo médio',
        conteudo: `O glúteo médio é um dos músculos mais importantes para a saúde da patela. Ele controla a rotação do fêmur e evita que o joelho "entre" durante movimentos.

Quando o glúteo médio é fraco, o fêmur roda para dentro, desalinhando a patela e aumentando o atrito. Fortalecer esse músculo é uma das intervenções mais eficazes para reduzir a dor na condromalácia.`,
      },
    },
    17: {
      titulo: 'Dia 17 — Condromalácia',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento Isométrico 10s',
          subtitulo: 'Aumenta resistência em posição estática',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Encoste as costas na parede',
            'Deslize para baixo até 30-40 graus',
            'Segure a posição por 10 segundos',
            'Descanse 10 segundos',
            'Faça 8 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Isometria fortalece sem movimento, protegendo a patela.',
        },
        {
          titulo: 'Elevação de Perna Estendida',
          subtitulo: 'Fortalece quadríceps sem sobrecarregar patela',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com uma perna flexionada',
            'Mantenha a outra perna estendida',
            'Eleve a perna estendida até a altura do joelho oposto',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando.',
          evitar: 'Não arqueie as costas.',
          dica: 'Este exercício fortalece o quadríceps de forma segura.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Melhora amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Posições seguras para o joelho',
        conteudo: `Algumas posições são mais seguras para a patela do que outras. Agachamentos parciais (30-60 graus) geralmente causam menos dor do que agachamentos profundos. Subir escadas é menos estressante que descer.

Aprenda a identificar as posições que seu joelho tolera bem e use-as como base para progredir. Com o tempo, à medida que ficar mais forte, você poderá expandir seu repertório de movimentos sem dor.`,
      },
    },
    18: {
      titulo: 'Dia 18 — Condromalácia',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento Parcial + Pausa',
          subtitulo: 'Combina amplitude com tempo sob tensão',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Pause por 4 segundos',
            'Suba empurrando pelos calcanhares',
            'Faça 10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando durante a pausa.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Pausa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Ponte Unilateral',
          subtitulo: 'Fortalece glúteos de forma avançada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando apenas uma perna',
            'Segure por 4 segundos no topo',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito.',
          evitar: 'Não torça o quadril.',
          dica: 'Força unilateral é essencial para atividades funcionais.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Movimentos que aliviam dor',
        conteudo: `Alguns movimentos podem ajudar a aliviar a dor na patela. Mobilizações suaves do joelho, alongamentos da cadeia posterior e ativação dos glúteos podem reduzir a tensão e melhorar o alinhamento.

Quando sentir desconforto, experimente fazer alguns desses movimentos. Muitas vezes, movimento controlado é melhor que repouso completo para aliviar a dor na condromalácia.`,
      },
    },
    19: {
      titulo: 'Dia 19 — Condromalácia',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Alto Controlado',
          subtitulo: 'Aumenta altura com controle',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau alto (20-25 cm)',
            'Suba com controle, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado',
            'Desça lentamente',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Altura maior prepara para escadas reais.',
        },
        {
          titulo: 'Glúteo Médio com Repetição Lenta',
          subtitulo: 'Aumenta tempo sob tensão',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima muito lentamente (4 segundos)',
            'Pause por 2 segundos no topo',
            'Desça lentamente (4 segundos)',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Movimento lento aumenta a intensidade.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece musculatura da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Importância da panturrilha',
        conteudo: `A panturrilha desempenha um papel importante na mecânica do joelho. Quando a panturrilha é fraca ou rígida, o tornozelo compensa, afetando o alinhamento do joelho e aumentando o estresse na patela.

Fortalecer e alongar a panturrilha regularmente melhora a mecânica de toda a perna, reduzindo compensações e protegendo o joelho durante atividades diárias.`,
      },
    },
    20: {
      titulo: 'Dia 20 — Condromalácia',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento Médio (40-50º) se sem dor',
          subtitulo: 'Aumenta amplitude gradualmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus (se sem dor)',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do ponto de dor.',
          dica: 'Aumente amplitude apenas se estiver sem dor.',
        },
        {
          titulo: 'Mobilidade Ativa',
          subtitulo: 'Movimenta todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade regular mantém o joelho saudável.',
        },
        {
          titulo: 'Quadríceps Leve',
          subtitulo: 'Mantém ativação do quadríceps',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Estenda uma perna à frente',
            'Contraia o quadríceps por 6 segundos',
            'Relaxe por 3 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da coxa trabalhando.',
          evitar: 'Não prenda a respiração.',
          dica: 'Ativação regular mantém o quadríceps forte.',
        },
      ],
      aula: {
        titulo: 'Entenda sua evolução',
        conteudo: `Neste ponto do programa, você deve notar melhorias significativas: menos dor ao subir escadas, maior facilidade para agachar, menos desconforto ao ficar sentado. Essas melhorias são resultado do fortalecimento muscular e correção de movimento.

Reflita sobre sua evolução. Você está mais forte, mais estável e mais confiante. Continue com os exercícios — a consistência é a chave para resultados duradouros.`,
      },
    },
    21: {
      titulo: 'Dia 21 — Condromalácia',
      fase: 3,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade regular mantém o joelho saudável.',
        },
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Consolida técnica de agachamento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Técnica correta é mais importante que amplitude.',
        },
        {
          titulo: 'Alongamento Completo',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (20-30s cada lado)',
            'Alongue posterior (20-30s)',
            'Alongue quadril (20-30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Semana 3 — o que mudou no seu joelho?',
        conteudo: `Parabéns por completar a terceira semana! Você trabalhou correção de movimento e redução do atrito patelofemoral. Seu joelho agora se move de forma mais eficiente e com menos dor.

Na última fase, vamos focar no retorno à função completa — subir escadas, agachar com mais amplitude, caminhar longas distâncias. Você está quase lá! Continue com dedicação e logo estará de volta às suas atividades sem limitações.`,
      },
    },

    // FASE 4 - Dias 22 a 30
    22: {
      titulo: 'Dia 22 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Controlado',
          subtitulo: 'Aumenta amplitude com controle',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-60 graus (se sem dor)',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e força durante todo o movimento.',
          evitar: 'Não desça além do ponto de dor.',
          dica: 'Amplitude maior prepara para atividades funcionais.',
        },
        {
          titulo: 'Step Alternado',
          subtitulo: 'Simula movimento real de escadas',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio',
            'Suba alternando as pernas',
            'Mantenha ritmo controlado',
            'Foque no alinhamento do joelho',
            'Faça 10 repetições (5 cada perna)',
          ],
          sensacaoCorreta: 'Você deve sentir controle e fluidez no movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento alternado prepara para escadas reais.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Joelho forte no dia a dia',
        conteudo: `Nesta fase final, estamos preparando seu joelho para as demandas da vida real. Subir escadas, agachar para pegar objetos, caminhar longas distâncias — todas essas atividades exigem força, controle e confiança.

Os exercícios desta semana simulam essas demandas, garantindo que você tenha a capacidade física e a confiança mental para retornar às suas atividades sem medo ou dor.`,
      },
    },
    23: {
      titulo: 'Dia 23 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Maximiza força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 5 segundos no topo',
            'Desça muito lentamente (5 segundos)',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para joelho saudável.',
        },
        {
          titulo: 'Glúteo Médio em Pé com Faixa',
          subtitulo: 'Fortalece em posição funcional',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica acima dos joelhos',
            'Fique em pé com pés afastados',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Força lateral protege o joelho em todas as atividades.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé próximo a uma parede',
            'Empurre o joelho para frente',
            'Mantenha o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo é essencial.',
        },
      ],
      aula: {
        titulo: 'Transferindo força para movimento',
        conteudo: `Força muscular é importante, mas o que realmente importa é como você usa essa força durante movimentos funcionais. Nesta fase, estamos trabalhando a transferência da força que você desenvolveu para atividades reais.

Pratique usar conscientemente os glúteos ao subir escadas, manter o joelho alinhado ao agachar e controlar o movimento ao descer degraus. Com o tempo, esses padrões se tornam automáticos.`,
      },
    },
    24: {
      titulo: 'Dia 24 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Funcional',
          subtitulo: 'Simula movimento do dia a dia',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça como se fosse pegar um objeto',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Pratique este movimento para atividades diárias.',
        },
        {
          titulo: 'Elevação de Perna Estendida',
          subtitulo: 'Mantém força do quadríceps',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com uma perna flexionada',
            'Mantenha a outra perna estendida',
            'Eleve a perna estendida até a altura do joelho oposto',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando.',
          evitar: 'Não arqueie as costas.',
          dica: 'Este exercício mantém o quadríceps forte.',
        },
        {
          titulo: 'Alongamento de Quadril',
          subtitulo: 'Mantém mobilidade do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'O que é um movimento seguro?',
        conteudo: `Um movimento seguro para o joelho é aquele que mantém alinhamento correto, distribui a carga adequadamente e respeita os limites do seu corpo. Não existe um movimento "proibido" — existe movimento mal executado.

Aprenda a executar movimentos com técnica correta e você poderá fazer praticamente qualquer atividade sem dor. A chave é atenção ao alinhamento, controle do movimento e progressão gradual.`,
      },
    },
    25: {
      titulo: 'Dia 25 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Subir e Descer Escada',
          subtitulo: 'Treina movimento funcional completo',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use uma escada real (3-5 degraus)',
            'Suba com controle, empurrando pelo calcanhar',
            'Desça lentamente, controlando o movimento',
            'Mantenha o joelho alinhado',
            'Faça 5-8 repetições completas',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança durante todo o movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Pratique escadas reais para ganhar confiança.',
        },
        {
          titulo: 'Agachamento Parcial com Pausa',
          subtitulo: 'Aumenta tempo sob tensão',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus',
            'Pause por 4 segundos',
            'Suba empurrando pelos calcanhares',
            'Faça 10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando durante a pausa.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Pausa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Mantém força da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Como subir escadas sem dor',
        conteudo: `Subir escadas sem dor requer técnica correta: coloque o pé todo no degrau, empurre pelo calcanhar, use o quadril para gerar força e mantenha o joelho alinhado com o pé.

Ao descer, controle o movimento com o quadríceps, descendo lentamente. Não "caia" no degrau. Use o corrimão se necessário, mas tente depender cada vez menos dele à medida que ganhar confiança.`,
      },
    },
    26: {
      titulo: 'Dia 26 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Médio',
          subtitulo: 'Aumenta amplitude progressivamente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 50-60 graus (se sem dor)',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e força durante todo o movimento.',
          evitar: 'Não desça além do ponto de dor.',
          dica: 'Aumente amplitude apenas se estiver sem dor.',
        },
        {
          titulo: 'Glúteo Médio Isometria 15s',
          subtitulo: 'Aumenta resistência do glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma perna',
            'Mantenha o joelho alinhado',
            'Segure por 15 segundos',
            'Descanse 10 segundos',
            'Faça 6 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando para manter o equilíbrio.',
          evitar: 'Não deixe o joelho "entrar".',
          dica: 'Equilíbrio unilateral fortalece estabilizadores.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se no chão com pernas estendidas',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás das coxas.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Construindo estabilidade',
        conteudo: `Estabilidade do joelho vem de músculos fortes e controle neuromuscular. Você desenvolveu ambos ao longo deste programa. Agora, seu joelho é capaz de manter alinhamento correto mesmo durante movimentos desafiadores.

Continue praticando exercícios de equilíbrio e controle para manter essa estabilidade. Um joelho estável é um joelho protegido contra lesões e dor.`,
      },
    },
    27: {
      titulo: 'Dia 27 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento + Ponte (Circuito)',
          subtitulo: 'Combina exercícios para resistência',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Faça 10 agachamentos parciais',
            'Imediatamente faça 12 pontes',
            'Descanse 1 minuto',
            'Repita o circuito 2-3 vezes',
          ],
          sensacaoCorreta: 'Você deve sentir resistência muscular, mas com controle.',
          evitar: 'Não sacrifique a técnica pela velocidade.',
          dica: 'Circuito treina resistência para atividades prolongadas.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Mantém amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Ajoelhe-se com uma perna à frente',
            'Empurre o quadril para frente',
            'Mantenha as costas retas',
            'Segure por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente do quadril.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Mantém flexibilidade da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo',
            'Mantenha por 20-30 segundos',
            'Repita 3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Fortalecendo a base do movimento',
        conteudo: `A base de qualquer movimento funcional é força, mobilidade e controle. Você desenvolveu todos esses elementos ao longo deste programa. Agora, seu joelho tem uma base sólida para suportar as demandas da vida diária.

Mantenha essa base forte com exercícios regulares. Não precisa ser todos os dias, mas 2-3 vezes por semana é suficiente para manter os ganhos que você conquistou.`,
      },
    },
    28: {
      titulo: 'Dia 28 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Step Lateral',
          subtitulo: 'Fortalece glúteo médio lateralmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio',
            'Suba lateralmente, mantendo o joelho alinhado',
            'Desça lentamente',
            'Foque no controle lateral',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Força lateral protege o joelho durante movimentos.',
        },
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Mantém técnica de agachamento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Técnica correta é mais importante que amplitude.',
        },
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade regular mantém o joelho saudável.',
        },
      ],
      aula: {
        titulo: 'Controle e equilíbrio',
        conteudo: `Controle e equilíbrio são habilidades que você desenvolveu ao longo deste programa. Essas habilidades protegem seu joelho durante movimentos inesperados e situações desafiadoras.

Continue praticando exercícios de equilíbrio e controle regularmente. Eles mantêm seu sistema neuromuscular afiado e seu joelho protegido contra lesões.`,
      },
    },
    29: {
      titulo: 'Dia 29 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Agachamento Funcional Leve/Médio',
          subtitulo: 'Consolida movimento funcional',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Este movimento é essencial para atividades diárias.',
        },
        {
          titulo: 'Ponte com Foco em Glúteo',
          subtitulo: 'Mantém força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Contraia os glúteos intensamente no topo',
            'Segure por 5 segundos',
            'Faça 12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para joelho saudável.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (20-30s cada lado)',
            'Alongue posterior (20-30s)',
            'Alongue quadril (20-30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Consolidando resultados',
        conteudo: `Você está quase no final do programa! Ao longo destes 29 dias, você fortaleceu os músculos ao redor do joelho, corrigiu padrões de movimento e desenvolveu controle neuromuscular.

Os resultados que você conquistou são fruto do seu esforço e dedicação. Amanhã, no último dia, vamos consolidar tudo que você aprendeu e preparar você para manter esses resultados a longo prazo.`,
      },
    },
    30: {
      titulo: 'Dia 30 — Condromalácia',
      fase: 4,
      exercicios: [
        {
          titulo: 'Mobilidade Global',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Movimente-se de forma fluida e celebre sua conquista',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas, móveis e saudáveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Continue fazendo mobilidade regularmente.',
        },
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Celebra sua evolução',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até onde se sentir confortável',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12 repetições com confiança',
          ],
          sensacaoCorreta: 'Você deve sentir controle, força e orgulho da sua evolução.',
          evitar: 'Não desça além do confortável.',
          dica: 'Compare com o Dia 1 — você evoluiu muito!',
        },
        {
          titulo: 'Alongamento Completo',
          subtitulo: 'Celebração e relaxamento final',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (30s cada lado)',
            'Alongue posterior (30s)',
            'Alongue quadril (30s cada lado)',
            'Alongue panturrilha (30s cada lado)',
            'Respire profundamente e celebre sua conquista',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento, satisfação e orgulho.',
          evitar: 'Não pare de se cuidar — mantenha os hábitos!',
          dica: 'Você completou o programa! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Como manter seu joelho saudável para sempre',
        conteudo: `Parabéns por completar os 30 dias! Você fortaleceu seu joelho, corrigiu padrões de movimento e recuperou sua capacidade de fazer atividades sem dor. Mas o trabalho não termina aqui.

Para manter esses resultados, continue fazendo exercícios de fortalecimento 2-3 vezes por semana, mantenha boa mobilidade e preste atenção à técnica durante atividades diárias. Se sentir um leve desconforto, volte aos exercícios básicos. Seu joelho agora é forte e saudável — mantenha-o assim! Você conquistou isso com seu esforço e dedicação. Parabéns!`,
      },
    },
  },
};
