// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "Joelho Sem Dor",
  description: "Seu alívio começa aqui. Avalie sua dor e receba um plano personalizado.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}
