export const dadosTrilhaSobrepesoJoelho = {
  nome: 'Sobrepeso + Joelho',
  descricao: 'Programa de 21 dias para pessoas com sobrepeso que têm dor no joelho — exercícios sem impacto, progressão segura e acessível',
  totalDias: 21,
  fases: [
    {
      numero: 1,
      nome: 'Redução de Dor + Mobilidade',
      descricao: 'Exercícios sem impacto para reduzir dor e ganhar mobilidade',
      dias: [1, 2, 3, 4, 5, 6, 7],
    },
    {
      numero: 2,
      nome: 'Fortalecimento Progressivo',
      descricao: 'Fortalecer músculos protetores sem sobrecarregar o joelho',
      dias: [8, 9, 10, 11, 12, 13, 14],
    },
    {
      numero: 3,
      nome: 'Função e Confiança',
      descricao: 'Retorno a movimentos funcionais com segurança',
      dias: [15, 16, 17, 18, 19, 20, 21],
    },
  ],
  dias: {
    // FASE 1 - Dias 1 a 7
    1: {
      titulo: 'Dia 1 — Sobrepeso + Joelho',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade do Joelho',
          subtitulo: 'Melhora amplitude de movimento sem sobrecarga',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira confortável com as costas retas',
            'Flexione e estenda o joelho suavemente, sem forçar',
            'Faça movimentos lentos e controlados',
            'Repita 12-15 vezes de cada lado',
            'Respire naturalmente durante o movimento',
          ],
          sensacaoCorreta: 'Você deve sentir o joelho se movendo livremente, sem dor aguda.',
          evitar: 'Não force o movimento além do confortável. Não faça movimentos bruscos.',
          dica: 'Mobilidade é o primeiro passo para reduzir a dor e melhorar a função do joelho.',
        },
        {
          titulo: 'Isometria Leve de Quadríceps',
          subtitulo: 'Ativa o músculo da coxa sem sobrecarregar o joelho',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com as costas bem apoiadas',
            'Estenda uma perna à frente, mantendo-a reta',
            'Contraia o músculo da coxa por 5 segundos',
            'Relaxe por 3 segundos',
            'Faça 8-10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da frente da coxa trabalhando suavemente.',
          evitar: 'Não prenda a respiração. Não force se sentir dor na patela.',
          dica: 'Este exercício fortalece o quadríceps de forma segura, essencial para proteger o joelho.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Relaxa a musculatura posterior e melhora flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente com o calcanhar no chão',
            'Incline o tronco para frente suavemente',
            'Mantenha por 20-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir um alongamento suave na parte de trás da coxa.',
          evitar: 'Não force o alongamento ao ponto de dor. Mantenha o joelho levemente flexionado se necessário.',
          dica: 'Músculos posteriores flexíveis reduzem a tensão e pressão no joelho.',
        },
      ],
      aula: {
        titulo: 'Por que o peso aumenta a dor no joelho',
        conteudo: `O excesso de peso corporal aumenta significativamente a pressão nas articulações do joelho. A cada quilo extra, o joelho pode receber até 4 vezes mais carga durante atividades como caminhar ou subir escadas.\n\nA boa notícia é que fortalecer os músculos ao redor do joelho ajuda a distribuir melhor essa carga, reduzindo a pressão direta na articulação. Este programa foi criado especialmente para você, com exercícios sem impacto que fortalecem sem sobrecarregar.`,
      },
    },
    2: {
      titulo: 'Dia 2 — Sobrepeso + Joelho',
      fase: 1,
      exercicios: [
        {
          titulo: 'Ponte',
          subtitulo: 'Fortalece glúteos e protege o joelho',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados e pés apoiados',
            'Eleve o quadril, formando uma linha reta dos ombros aos joelhos',
            'Contraia os glúteos no topo',
            'Segure por 2-3 segundos e desça lentamente',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente, não a lombar.',
          evitar: 'Não arqueie demais as costas. Mantenha o core ativado.',
          dica: 'Glúteos fortes reduzem a sobrecarga no joelho durante todas as atividades.',
        },
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Melhora dorsiflexão e distribui carga no joelho',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Coloque um pé à frente, joelho levemente flexionado',
            'Empurre o joelho para frente, mantendo o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento suave na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
        {
          titulo: 'Alongamento de Quadril',
          subtitulo: 'Relaxa musculatura do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Cruze um tornozelo sobre o joelho oposto',
            'Incline o tronco suavemente para frente',
            'Mantenha por 20-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento no glúteo e lateral do quadril.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Quadril flexível melhora o alinhamento e função do joelho.',
        },
      ],
      aula: {
        titulo: 'Ativando glúteos para proteger o joelho',
        conteudo: `Os glúteos são músculos essenciais para proteger o joelho. Quando os glúteos estão fracos, o joelho tende a desalinhar durante movimentos, aumentando a pressão na articulação.\n\nFortalecer os glúteos ajuda a manter o joelho em posição correta, distribuindo melhor a carga e reduzindo significativamente a dor. Foque em sentir os glúteos trabalhando durante os exercícios.`,
      },
    },
    3: {
      titulo: 'Dia 3 — Sobrepeso + Joelho',
      fase: 1,
      exercicios: [
        {
          titulo: 'Extensão de Joelho Sentado',
          subtitulo: 'Fortalece quadríceps de forma controlada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira com as costas retas',
            'Estenda uma perna à frente até ficar reta',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o músculo da coxa trabalhando.',
          evitar: 'Não use impulso. Mantenha o movimento controlado.',
          dica: 'Movimento controlado protege a patela durante o fortalecimento.',
        },
        {
          titulo: 'Abdução Lateral em Pé',
          subtitulo: 'Fortalece glúteo médio em posição funcional',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma cadeira ou parede',
            'Eleve uma perna lateralmente, mantendo-a reta',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não incline o tronco. Mantenha o movimento controlado.',
          dica: 'Glúteo médio forte protege o joelho em todas as atividades.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente suavemente',
            'Mantenha por 20-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Importância do quadríceps',
        conteudo: `O quadríceps é o músculo mais importante para a estabilidade do joelho. Ele controla o movimento da patela e absorve impacto durante atividades diárias.\n\nQuando o quadríceps está forte, ele reduz significativamente a pressão na articulação do joelho. Por isso, fortalecê-lo de forma segura é essencial para reduzir a dor e melhorar sua qualidade de vida.`,
      },
    },
    4: {
      titulo: 'Dia 4 — Sobrepeso + Joelho',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mini-agachamento com Cadeira',
          subtitulo: 'Fortalece membros inferiores com segurança',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma cadeira',
            'Desça lentamente como se fosse sentar (apenas 1/4 do movimento)',
            'Toque levemente o assento e volte',
            'Mantenha os joelhos alinhados com os pés',
            'Faça 8-10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando.',
          evitar: 'Não desça muito se sentir dor. Não deixe os joelhos ultrapassarem muito os pés.',
          dica: 'A cadeira oferece segurança para aprender o movimento correto.',
        },
        {
          titulo: 'Elevação de Perna Estendida',
          subtitulo: 'Fortalece quadríceps sem sobrecarregar patela',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com uma perna flexionada',
            'Mantenha a outra perna estendida',
            'Eleve a perna estendida até a altura do joelho oposto',
            'Desça lentamente',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando.',
          evitar: 'Não arqueie as costas.',
          dica: 'Este exercício fortalece o quadríceps de forma muito segura.',
        },
        {
          titulo: 'Mobilidade de Quadril',
          subtitulo: 'Melhora amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos lentos com o joelho elevado',
            'Faça 10 círculos para cada lado',
            'Depois faça 10 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir o quadril se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Quadril móvel permite melhor distribuição de carga no joelho.',
        },
      ],
      aula: {
        titulo: 'Como agachar sem dor',
        conteudo: `Agachar é um movimento fundamental que muitas pessoas com sobrepeso evitam por causa da dor. A chave para agachar sem dor é começar com amplitude pequena e usar apoio.\n\nMantenha os joelhos alinhados com os pés, empurre pelos calcanhares e use o quadril para gerar força. Comece com mini-agachamentos e aumente gradualmente à medida que ficar mais forte e confiante.`,
      },
    },
    5: {
      titulo: 'Dia 5 — Sobrepeso + Joelho',
      fase: 1,
      exercicios: [
        {
          titulo: 'Step Baixo com Apoio',
          subtitulo: 'Inicia movimento funcional controlado',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau muito baixo (10 cm) ou livros empilhados',
            'Apoie-se em uma parede ou corrimão',
            'Suba com um pé, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado com o pé',
            'Desça lentamente com controle',
            'Faça 8 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Comece com altura muito baixa e foque no controle e apoio.',
        },
        {
          titulo: 'Ponte com Pausa',
          subtitulo: 'Aumenta tempo sob tensão dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril',
            'Pause por 3-4 segundos no topo, contraindo os glúteos',
            'Desça lentamente',
            'Faça 10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente durante a pausa.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Pausa aumenta a intensidade do exercício de forma segura.',
        },
        {
          titulo: 'Alongamento de Panturrilha',
          subtitulo: 'Melhora flexibilidade da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma parede',
            'Coloque um pé atrás, mantendo-o reto',
            'Empurre o calcanhar de trás no chão',
            'Incline o corpo para frente suavemente',
            'Mantenha por 20-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Panturrilha flexível melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Distribuição do peso corporal',
        conteudo: `A forma como você distribui o peso corporal durante movimentos afeta diretamente a pressão no joelho. Ao subir degraus ou agachar, empurre pelos calcanhares e use o quadril — isso ativa os glúteos e reduz a sobrecarga no joelho.\n\nEvite empurrar apenas pela ponta dos pés, pois isso aumenta a pressão na patela. Pratique conscientemente essa distribuição de carga durante os exercícios e atividades diárias.`,
      },
    },
    6: {
      titulo: 'Dia 6 — Sobrepeso + Joelho',
      fase: 1,
      exercicios: [
        {
          titulo: 'Marcha Estacionária com Apoio',
          subtitulo: 'Ativa musculatura sem impacto',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma cadeira ou parede',
            'Eleve um joelho de cada vez, como se estivesse marchando',
            'Mantenha o movimento controlado e lento',
            'Faça 20 repetições (10 cada perna)',
            'Descanse e repita mais uma série',
          ],
          sensacaoCorreta: 'Você deve sentir os músculos das pernas trabalhando sem impacto.',
          evitar: 'Não eleve o joelho muito alto se sentir dor. Não faça movimentos bruscos.',
          dica: 'Movimento sem impacto é ideal para fortalecer sem sobrecarregar.',
        },
        {
          titulo: 'Alongamento Posterior Profundo',
          subtitulo: 'Alongamento intenso da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente, tentando alcançar o pé',
            'Mantenha por 25-30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento intenso na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor aguda.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
        {
          titulo: 'Mobilidade de Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos com os tornozelos',
            'Faça 10 círculos para cada lado',
            'Depois faça 10 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir os tornozelos se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
      ],
      aula: {
        titulo: 'Movimento como alívio',
        conteudo: `Muitas pessoas com sobrepeso e dor no joelho acreditam que devem evitar movimento. Na verdade, movimento controlado e sem impacto é uma das melhores formas de aliviar a dor.\n\nMovimento aumenta a circulação, nutre a cartilagem e fortalece os músculos protetores. O segredo é escolher exercícios sem impacto e progredir gradualmente, como estamos fazendo neste programa.`,
      },
    },
    7: {
      titulo: 'Dia 7 — Sobrepeso + Joelho',
      fase: 1,
      exercicios: [
        {
          titulo: 'Mobilidade Geral',
          subtitulo: 'Prepara todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Faça círculos com os tornozelos (10 cada lado)',
            'Flexione e estenda os joelhos suavemente (10 vezes)',
            'Faça círculos com os quadris sentado (10 cada lado)',
            'Movimente-se de forma fluida e controlada',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações aquecendo e ficando mais soltas.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade global prepara o corpo para movimentos funcionais.',
        },
        {
          titulo: 'Mini-agachamento Leve',
          subtitulo: 'Consolida técnica de agachamento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma cadeira',
            'Desça apenas 1/4 do movimento',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Técnica correta é mais importante que amplitude.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura trabalhada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue posterior sentado (20-30s)',
            'Alongue quadril sentado (20-30s cada lado)',
            'Alongue panturrilha em pé (20-30s cada lado)',
            'Respire profundamente durante os alongamentos',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação e previne rigidez.',
        },
      ],
      aula: {
        titulo: 'Semana 1 — Sua evolução',
        conteudo: `Parabéns por completar a primeira semana! Você trabalhou mobilidade, ativação muscular e controle inicial de movimento. Seu joelho já está mais preparado para os desafios das próximas semanas.\n\nNa próxima fase, vamos aumentar gradualmente a intensidade, focando em fortalecimento mais específico do quadríceps, glúteos e estabilizadores. Continue prestando atenção ao alinhamento do joelho e ao controle dos movimentos — esses detalhes fazem toda a diferença na sua recuperação.`,
      },
    },

    // FASE 2 - Dias 8 a 14
    8: {
      titulo: 'Dia 8 — Sobrepeso + Joelho',
      fase: 2,
      exercicios: [
        {
          titulo: 'Ponte com Pausa',
          subtitulo: 'Aumenta tempo sob tensão dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril',
            'Pause por 4-5 segundos no topo, contraindo os glúteos',
            'Desça lentamente',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando intensamente durante a pausa.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Pausa aumenta a intensidade do exercício de forma segura.',
        },
        {
          titulo: 'Abdução com Faixa Leve',
          subtitulo: 'Fortalece glúteo médio com resistência',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Coloque uma faixa elástica leve acima dos joelhos (opcional)',
            'Eleve a perna de cima lateralmente',
            'Segure por 2-3 segundos no topo',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não rode o quadril para trás.',
          dica: 'Glúteo médio forte previne que o joelho "entre" durante movimentos.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Força lateral protege o joelho',
        conteudo: `A força lateral do quadril (glúteo médio) é fundamental para manter o joelho estável durante movimentos. Quando essa musculatura é fraca, o joelho tende a "entrar" (valgo dinâmico), aumentando a pressão na articulação.\n\nFortalecer o glúteo médio cria uma base sólida de estabilidade que protege o joelho em todos os movimentos funcionais — caminhar, subir escadas, agachar. Essa é uma das chaves para reduzir a dor.`,
      },
    },
    9: {
      titulo: 'Dia 9 — Sobrepeso + Joelho',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento com Cadeira',
          subtitulo: 'Fortalece membros inferiores com segurança',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé de frente para uma cadeira',
            'Desça lentamente como se fosse sentar',
            'Toque levemente o assento e volte',
            'Mantenha os joelhos alinhados com os pés',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando.',
          evitar: 'Não deixe os joelhos ultrapassarem muito os pés. Não caia na cadeira.',
          dica: 'A cadeira oferece segurança para aprender o movimento correto.',
        },
        {
          titulo: 'Extensão com Faixa Leve',
          subtitulo: 'Fortalece quadríceps com resistência progressiva',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com uma faixa elástica leve no tornozelo (opcional)',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando contra a resistência.',
          evitar: 'Não use impulso.',
          dica: 'Resistência progressiva fortalece o quadríceps de forma eficaz.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Empurre o joelho para frente mantendo o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
      ],
      aula: {
        titulo: 'Evoluindo sem dor',
        conteudo: `Evolução no fortalecimento não significa necessariamente fazer exercícios mais difíceis ou com mais peso. Para pessoas com sobrepeso e dor no joelho, evolução significa melhor controle, mais repetições e maior confiança.\n\nFoque em executar os movimentos com técnica perfeita e controle total. À medida que isso fica mais fácil, você pode aumentar gradualmente as repetições ou adicionar resistência leve. Sempre priorize qualidade sobre quantidade.`,
      },
    },
    10: {
      titulo: 'Dia 10 — Sobrepeso + Joelho',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Baixo Controlado',
          subtitulo: 'Aperfeiçoa controle de movimento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau baixo (10-12 cm)',
            'Suba lentamente (3 segundos) com apoio',
            'Pause por 2 segundos no topo',
            'Desça lentamente (3 segundos)',
            'Faça 8-10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir controle total durante todo o movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento lento aumenta o controle neuromuscular.',
        },
        {
          titulo: 'Elevação Lateral de Perna',
          subtitulo: 'Fortalece glúteo médio',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Segure por 3 segundos no topo',
            'Desça lentamente',
            'Faça 12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não rode o quadril para trás.',
          dica: 'Glúteo médio forte previne valgo dinâmico.',
        },
        {
          titulo: 'Alongamento Quadríceps',
          subtitulo: 'Mantém flexibilidade da coxa',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede ou cadeira',
            'Flexione um joelho, segurando o pé atrás',
            'Puxe o calcanhar em direção ao glúteo suavemente',
            'Mantenha por 20-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na frente da coxa.',
          evitar: 'Não arqueie as costas.',
          dica: 'Quadríceps flexível reduz tensão na patela.',
        },
      ],
      aula: {
        titulo: 'Alinhamento seguro',
        conteudo: `O alinhamento correto do joelho durante movimentos é fundamental para reduzir a pressão na articulação. O joelho deve seguir a linha do segundo dedo do pé — não deve "entrar" nem "sair" demais.\n\nQuando o joelho está bem alinhado, a carga é distribuída de forma mais uniforme, reduzindo o estresse em pontos específicos. Pratique conscientemente esse alinhamento durante os exercícios e atividades diárias.`,
      },
    },
    11: {
      titulo: 'Dia 11 — Sobrepeso + Joelho',
      fase: 2,
      exercicios: [
        {
          titulo: 'Ponte Unilateral Assistida',
          subtitulo: 'Fortalece glúteos de forma unilateral',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente (ou mantenha levemente apoiada)',
            'Eleve o quadril usando principalmente uma perna',
            'Segure por 3 segundos no topo',
            'Faça 8-10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando.',
          evitar: 'Não torça o quadril. Mantenha o core ativado.',
          dica: 'Força unilateral é essencial para atividades funcionais.',
        },
        {
          titulo: 'Marcha Estacionária Lenta',
          subtitulo: 'Ativa musculatura sem impacto',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma cadeira',
            'Eleve um joelho de cada vez muito lentamente',
            'Mantenha o movimento controlado',
            'Faça 20-30 repetições (10-15 cada perna)',
          ],
          sensacaoCorreta: 'Você deve sentir os músculos das pernas trabalhando sem impacto.',
          evitar: 'Não eleve o joelho muito alto se sentir dor.',
          dica: 'Movimento sem impacto fortalece sem sobrecarregar.',
        },
        {
          titulo: 'Mobilidade de Quadril',
          subtitulo: 'Melhora amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos lentos com o joelho elevado',
            'Faça 10 círculos para cada lado',
            'Depois faça 10 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir o quadril se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Quadril e joelho — conexão essencial',
        conteudo: `O quadril e o joelho trabalham juntos durante todos os movimentos. Quando o quadril está fraco ou rígido, o joelho compensa, aumentando o estresse na articulação.\n\nFortalecer e mobilizar o quadril permite que ele assuma sua parte da carga durante movimentos, reduzindo significativamente a pressão no joelho. Por isso, incluímos tantos exercícios de quadril neste programa.`,
      },
    },
    12: {
      titulo: 'Dia 12 — Sobrepeso + Joelho',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento Isométrico Leve',
          subtitulo: 'Fortalece em posição estática',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Encoste as costas na parede',
            'Deslize para baixo até 20-30 graus (mini agachamento)',
            'Segure a posição por 10-12 segundos',
            'Descanse 10 segundos',
            'Faça 6-8 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Isometria fortalece sem movimento, protegendo a patela.',
        },
        {
          titulo: 'Extensão com Pausa',
          subtitulo: 'Aumenta tempo sob tensão do quadríceps',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Estenda uma perna à frente',
            'Pause por 4-5 segundos no topo',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando durante a pausa.',
          evitar: 'Não prenda a respiração.',
          dica: 'Pausa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Alongamento Posterior Profundo',
          subtitulo: 'Alongamento intenso da cadeia posterior',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente, tentando alcançar o pé',
            'Mantenha por 25-30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento intenso na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor aguda.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Como não agravar a dor',
        conteudo: `Para não agravar a dor no joelho, é importante respeitar alguns princípios: não force movimentos que causem dor aguda, progrida gradualmente, mantenha sempre o joelho alinhado e use apoio quando necessário.\n\nSe um exercício causa dor, reduza a amplitude, o número de repetições ou use mais apoio. Desconforto muscular é normal, mas dor articular é sinal de alerta. Aprenda a ouvir seu corpo.`,
      },
    },
    13: {
      titulo: 'Dia 13 — Sobrepeso + Joelho',
      fase: 2,
      exercicios: [
        {
          titulo: 'Step Lateral Suave',
          subtitulo: 'Fortalece glúteo médio lateralmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau muito baixo',
            'Suba lateralmente com apoio, mantendo o joelho alinhado',
            'Desça lentamente',
            'Foque no controle lateral',
            'Faça 8-10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando.',
          evitar: 'Não deixe o joelho "entrar". Não use impulso.',
          dica: 'Força lateral protege o joelho durante movimentos.',
        },
        {
          titulo: 'Abdução com Pausa',
          subtitulo: 'Aumenta tempo sob tensão do glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de lado com pernas estendidas',
            'Eleve a perna de cima lateralmente',
            'Pause por 4-5 segundos no topo',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não rode o quadril.',
          dica: 'Pausa aumenta a intensidade do exercício.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos com os tornozelos',
            'Faça 10 círculos para cada lado',
            'Depois faça 10 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir os tornozelos se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
      ],
      aula: {
        titulo: 'Equilíbrio e estabilidade',
        conteudo: `Equilíbrio e estabilidade são essenciais para proteger o joelho durante movimentos. Quando você tem bom equilíbrio, o joelho se move de forma mais coordenada e eficiente, reduzindo compensações.\n\nExercícios que desafiam o equilíbrio melhoram a propriocepção (percepção do corpo no espaço), ajudando o joelho a se mover de forma mais segura durante atividades diárias.`,
      },
    },
    14: {
      titulo: 'Dia 14 — Sobrepeso + Joelho',
      fase: 2,
      exercicios: [
        {
          titulo: 'Agachamento Leve',
          subtitulo: 'Consolida técnica de agachamento',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 30-40 graus com apoio se necessário',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Técnica correta é mais importante que amplitude.',
        },
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Maximiza força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 5 segundos no topo',
            'Desça muito lentamente (4-5 segundos)',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para joelho saudável.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps em pé (20-30s cada lado)',
            'Alongue posterior sentado (20-30s)',
            'Alongue quadril sentado (20-30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Semana 2 — Sua evolução',
        conteudo: `Parabéns por completar a segunda semana! Você trabalhou fortalecimento específico do quadríceps, glúteos e estabilizadores. Seu joelho agora está significativamente mais forte e estável.\n\nNa próxima fase, vamos focar em retorno a movimentos funcionais com mais confiança. Você aprenderá a aplicar a força que desenvolveu em atividades do dia a dia. Continue com dedicação — você está fazendo um excelente progresso!`,
      },
    },

    // FASE 3 - Dias 15 a 21
    15: {
      titulo: 'Dia 15 — Sobrepeso + Joelho',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Médio com Apoio',
          subtitulo: 'Aumenta altura com controle',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio (15-18 cm) com apoio',
            'Suba com controle, empurrando pelo calcanhar',
            'Mantenha o joelho alinhado',
            'Desça lentamente',
            'Faça 8-10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir quadríceps e glúteos trabalhando, sem dor no joelho.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Altura maior prepara para escadas reais.',
        },
        {
          titulo: 'Glúteo Médio com Faixa',
          subtitulo: 'Aumenta resistência para glúteo médio',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica leve acima dos joelhos',
            'Fique em pé com pés afastados e apoio',
            'Dê passos laterais pequenos contra a resistência',
            'Mantenha tensão constante',
            'Faça 10-12 passos de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando contra a resistência.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Glúteo médio forte previne valgo dinâmico.',
        },
        {
          titulo: 'Mobilidade Quadril',
          subtitulo: 'Mantém amplitude do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Faça círculos lentos com o joelho elevado',
            'Faça 10 círculos para cada lado',
            'Depois faça 10 círculos no sentido contrário',
          ],
          sensacaoCorreta: 'Você deve sentir o quadril se movendo livremente.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Quadril móvel permite melhor distribuição de carga.',
        },
      ],
      aula: {
        titulo: 'Erros que aumentam a dor',
        conteudo: `Alguns erros comuns podem aumentar a dor no joelho: deixar o joelho "entrar" durante movimentos, usar impulso em vez de controle, descer escadas muito rápido e não usar apoio quando necessário.\n\nEvite esses erros prestando atenção ao alinhamento do joelho, movendo-se de forma controlada e usando apoio sempre que sentir insegurança. Esses pequenos ajustes fazem grande diferença.`,
      },
    },
    16: {
      titulo: 'Dia 16 — Sobrepeso + Joelho',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento 40 a 50 Graus',
          subtitulo: 'Aumenta amplitude gradualmente',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça até 40-50 graus (se sem dor) com apoio se necessário',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 8-10 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do ponto de dor.',
          dica: 'Aumente amplitude apenas se estiver sem dor.',
        },
        {
          titulo: 'Ponte Unilateral',
          subtitulo: 'Fortalece glúteos de forma avançada',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Estenda uma perna à frente',
            'Eleve o quadril usando principalmente uma perna',
            'Segure por 3-4 segundos no topo',
            'Faça 8-10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o glúteo da perna de apoio trabalhando muito.',
          evitar: 'Não torça o quadril.',
          dica: 'Força unilateral é essencial para atividades funcionais.',
        },
        {
          titulo: 'Alongamento Posterior',
          subtitulo: 'Mantém flexibilidade',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se na beira de uma cadeira',
            'Estenda uma perna à frente',
            'Incline o tronco para frente',
            'Mantenha por 20-30 segundos',
            'Respire profundamente',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na parte de trás da coxa.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Flexibilidade posterior reduz tensão no joelho.',
        },
      ],
      aula: {
        titulo: 'Construindo confiança',
        conteudo: `Confiança é tão importante quanto força física. Muitas pessoas com sobrepeso e dor no joelho desenvolvem medo de movimento, o que leva a mais fraqueza e mais dor.\n\nÀ medida que você fica mais forte e percebe que pode fazer movimentos sem dor, sua confiança aumenta. Essa confiança permite que você se mova mais, criando um ciclo positivo de melhora contínua.`,
      },
    },
    17: {
      titulo: 'Dia 17 — Sobrepeso + Joelho',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Alternado',
          subtitulo: 'Simula movimento real de escadas',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio com apoio',
            'Suba alternando as pernas',
            'Mantenha ritmo controlado',
            'Foque no alinhamento do joelho',
            'Faça 8-10 repetições (4-5 cada perna)',
          ],
          sensacaoCorreta: 'Você deve sentir controle e fluidez no movimento.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento alternado prepara para escadas reais.',
        },
        {
          titulo: 'Extensão com Resistência Média',
          subtitulo: 'Fortalece quadríceps com carga progressiva',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se com uma faixa elástica média no tornozelo',
            'Estenda o joelho contra a resistência',
            'Contraia o quadríceps no topo por 3 segundos',
            'Desça lentamente',
            'Faça 10-12 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando contra a resistência.',
          evitar: 'Não use impulso.',
          dica: 'Resistência progressiva fortalece de forma eficaz.',
        },
        {
          titulo: 'Mobilidade Tornozelo',
          subtitulo: 'Mantém amplitude de movimento',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Empurre o joelho para frente mantendo o calcanhar no chão',
            'Segure por 5 segundos',
            'Faça 10 repetições de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento na panturrilha.',
          evitar: 'Não tire o calcanhar do chão.',
          dica: 'Boa mobilidade de tornozelo reduz pressão na patela.',
        },
      ],
      aula: {
        titulo: 'Controle na descida',
        conteudo: `Descer escadas ou degraus é particularmente desafiador porque exige controle excêntrico (músculo trabalhando enquanto se alonga). Isso é mais difícil que subir e coloca mais pressão no joelho.\n\nPara descer com segurança, vá devagar, use apoio, mantenha o joelho alinhado e controle o movimento com o quadríceps. Com prática, isso ficará mais fácil e menos doloroso.`,
      },
    },
    18: {
      titulo: 'Dia 18 — Sobrepeso + Joelho',
      fase: 3,
      exercicios: [
        {
          titulo: 'Marcha Estacionária Lenta',
          subtitulo: 'Ativa musculatura sem impacto',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma cadeira',
            'Eleve um joelho de cada vez muito lentamente',
            'Mantenha o movimento controlado',
            'Faça 30-40 repetições (15-20 cada perna)',
          ],
          sensacaoCorreta: 'Você deve sentir os músculos das pernas trabalhando sem impacto.',
          evitar: 'Não eleve o joelho muito alto se sentir dor.',
          dica: 'Movimento sem impacto fortalece sem sobrecarregar.',
        },
        {
          titulo: 'Abdução com Banda',
          subtitulo: 'Fortalece glúteo médio com resistência',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Coloque faixa elástica acima dos joelhos',
            'Fique em pé com pés afastados e apoio',
            'Dê passos laterais contra a resistência',
            'Mantenha tensão constante',
            'Faça 12-15 passos de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir o lado do quadril trabalhando intensamente.',
          evitar: 'Não deixe os joelhos "entrarem".',
          dica: 'Força lateral protege o joelho em todas as atividades.',
        },
        {
          titulo: 'Alongamento de Glúteo',
          subtitulo: 'Relaxa musculatura do quadril',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Sente-se em uma cadeira',
            'Cruze um tornozelo sobre o joelho oposto',
            'Incline o tronco suavemente para frente',
            'Mantenha por 25-30 segundos',
            'Repita 2-3 vezes de cada lado',
          ],
          sensacaoCorreta: 'Você deve sentir alongamento no glúteo.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Glúteo flexível melhora o alinhamento do joelho.',
        },
      ],
      aula: {
        titulo: 'Joelho estável ao caminhar',
        conteudo: `Caminhar é uma das atividades mais importantes do dia a dia. Para caminhar sem dor, você precisa de joelhos estáveis que se movam de forma coordenada.\n\nOs exercícios deste programa fortaleceram os músculos que estabilizam o joelho durante a caminhada. Continue praticando e você notará que pode caminhar distâncias maiores com menos dor e mais confiança.`,
      },
    },
    19: {
      titulo: 'Dia 19 — Sobrepeso + Joelho',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento Apoiado na Parede',
          subtitulo: 'Fortalece com suporte',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Encoste as costas na parede',
            'Deslize para baixo até 40-50 graus',
            'Segure a posição por 12-15 segundos',
            'Descanse 10 segundos',
            'Faça 6-8 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir o quadríceps trabalhando intensamente.',
          evitar: 'Não desça muito se sentir dor.',
          dica: 'Parede oferece suporte para fortalecer com segurança.',
        },
        {
          titulo: 'Ponte Avançada com Pausa',
          subtitulo: 'Maximiza força dos glúteos',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 6-8 segundos no topo',
            'Desça muito lentamente (5 segundos)',
            'Faça 10-12 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando muito intensamente.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Glúteos fortes são essenciais para joelho saudável.',
        },
        {
          titulo: 'Alongamento Global',
          subtitulo: 'Relaxa toda a musculatura',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps em pé (20-30s cada lado)',
            'Alongue posterior sentado (20-30s)',
            'Alongue quadril sentado (20-30s cada lado)',
            'Alongue panturrilha em pé (20-30s cada lado)',
            'Respire profundamente',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento e alongamento suave.',
          evitar: 'Não force ao ponto de dor.',
          dica: 'Alongamento ajuda na recuperação.',
        },
      ],
      aula: {
        titulo: 'Evitando recidiva',
        conteudo: `Para evitar que a dor volte, é importante manter os hábitos que você desenvolveu neste programa: exercícios regulares de fortalecimento, atenção ao alinhamento do joelho e progressão gradual em atividades.\n\nNão pare de se exercitar quando a dor melhorar. Continue fazendo exercícios de fortalecimento 2-3 vezes por semana para manter os ganhos que você conquistou.`,
      },
    },
    20: {
      titulo: 'Dia 20 — Sobrepeso + Joelho',
      fase: 3,
      exercicios: [
        {
          titulo: 'Step Médio Contínuo',
          subtitulo: 'Aumenta resistência funcional',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Use um degrau médio com apoio',
            'Suba e desça continuamente por 2-3 minutos',
            'Mantenha ritmo controlado',
            'Foque no alinhamento do joelho',
            'Descanse 1 minuto e repita',
          ],
          sensacaoCorreta: 'Você deve sentir resistência muscular, mas com controle.',
          evitar: 'Não use impulso. Não deixe o joelho "entrar".',
          dica: 'Movimento contínuo treina resistência para atividades diárias.',
        },
        {
          titulo: 'Mobilidade Ativa',
          subtitulo: 'Movimenta todas as articulações',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Mobilidade de tornozelo (10 cada lado)',
            'Círculos de joelho (10 cada lado)',
            'Mobilidade de quadril (10 cada lado)',
            'Movimente-se de forma fluida',
          ],
          sensacaoCorreta: 'Você deve sentir as articulações soltas e móveis.',
          evitar: 'Não force movimentos que causem dor.',
          dica: 'Mobilidade regular mantém o joelho saudável.',
        },
        {
          titulo: 'Panturrilha',
          subtitulo: 'Fortalece musculatura da panturrilha',
          duracao: '3-4 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé apoiado em uma parede',
            'Eleve-se na ponta dos pés',
            'Segure por 2 segundos no topo',
            'Desça lentamente',
            'Faça 15-20 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir a panturrilha trabalhando.',
          evitar: 'Não use impulso.',
          dica: 'Panturrilha forte melhora a mecânica do joelho.',
        },
      ],
      aula: {
        titulo: 'Joelho mais resistente',
        conteudo: `Neste ponto do programa, seu joelho está significativamente mais resistente. Você desenvolveu força, controle e confiança. Atividades que antes causavam dor agora são mais fáceis.\n\nEssa resistência vem do fortalecimento dos músculos protetores e da melhora na mecânica de movimento. Continue praticando e você verá melhorias ainda maiores.`,
      },
    },
    21: {
      titulo: 'Dia 21 — Sobrepeso + Joelho',
      fase: 3,
      exercicios: [
        {
          titulo: 'Agachamento Funcional Leve',
          subtitulo: 'Consolida movimento funcional',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Fique em pé com pés na largura dos ombros',
            'Desça como se fosse pegar um objeto',
            'Mantenha os joelhos alinhados',
            'Suba empurrando pelos calcanhares',
            'Faça 12-15 repetições',
          ],
          sensacaoCorreta: 'Você deve sentir controle e confiança no movimento.',
          evitar: 'Não desça além do confortável.',
          dica: 'Este movimento é essencial para atividades diárias.',
        },
        {
          titulo: 'Ponte Avançada',
          subtitulo: 'Celebra sua evolução',
          duracao: '4-5 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Deite de costas com joelhos flexionados',
            'Eleve o quadril alto',
            'Pause por 5 segundos no topo',
            'Desça lentamente',
            'Faça 12-15 repetições com orgulho',
          ],
          sensacaoCorreta: 'Você deve sentir os glúteos trabalhando e orgulho da sua evolução.',
          evitar: 'Não arqueie demais as costas.',
          dica: 'Compare com o Dia 1 — você evoluiu muito!',
        },
        {
          titulo: 'Alongamento Geral',
          subtitulo: 'Celebração e relaxamento final',
          duracao: '5-6 min',
          videoUrl: '/videos/placeholder.mp4',
          comoFazer: [
            'Alongue quadríceps (30s cada lado)',
            'Alongue posterior (30s)',
            'Alongue quadril (30s cada lado)',
            'Alongue panturrilha (30s cada lado)',
            'Respire profundamente e celebre sua conquista',
          ],
          sensacaoCorreta: 'Você deve sentir relaxamento, satisfação e orgulho.',
          evitar: 'Não pare de se cuidar — mantenha os hábitos!',
          dica: 'Você completou o programa! Parabéns!',
        },
      ],
      aula: {
        titulo: 'Como manter joelhos saudáveis',
        conteudo: `Parabéns por completar os 21 dias! Você fortaleceu seu joelho, melhorou sua mobilidade e recuperou sua capacidade de fazer atividades sem dor. Mas o trabalho não termina aqui.\n\nPara manter esses resultados, continue fazendo exercícios de fortalecimento 2-3 vezes por semana, mantenha boa mobilidade e preste atenção à técnica durante atividades diárias. Se sentir um leve desconforto, volte aos exercícios básicos. Seu joelho agora é mais forte e saudável — mantenha-o assim! Você conquistou isso com seu esforço e dedicação. Parabéns!`,
      },
    },
  },
};
